files:
- name: ./logs/current-bass-rtlog
  send_delay: 5
  log_type: bass
  format: eventlog
  compression-out: 0
  ident: alicelogs@prod
- name: ./logs/current-bass_server_main-bass_server-100
  ident: bass-vins
  log_type: bass-vins-log
  sid: {content, lines: 1, host, file}
  pipe: ./bin/bass/bass_scripts/push_client_log_parsing.py --env prod_hollywood_music 2>pipe.err
logger:
  file: ./logs/push-client.log
  level: 5
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
  tvm-client-id: 2000464
  tvm-server-id: 2001059
  proto: pq
watcher:
  state: ./logs/push-client-state
