log:
  level: debug
  development: true
  encoding: json
  outputPaths:
    - stderr
  errorOutputPaths:
    - stderr
sdk_server:
  cache_size: 10000
webhook_server:
  echo_read_timeout: 500ms
  echo_write_timeout: 500ms
  storage:
    ydb:
      endpoint: "ydb-ru-prestable.yandex.net:2135"
      dial_timeout: 1s
      request_timeout: 300ms
      database: "/ru-prestable/alice/beta/gamma"
      table_path_prefix: "/ru-prestable/alice/beta/gamma/skills/"
  skills:
    - id: guess-animal
      addr: guess-animal.gamma-test.alice.yandex.net:8001
    - id: echo
      addr: echo.gamma-test.alice.yandex.net:8001
    - id: cheat-game
      addr: cheat-game.gamma-test.alice.yandex.net:8001
    - id: song-search
      addr: song-search.gamma-test.alice.yandex.net:8001
    - id: akinator
      addr: akinator.gamma-test.alice.yandex.net:8001
    - id: odd-word-game
      addr: odd-word-game.gamma-test.alice.yandex.net:8001
    - id: word_game
      addr: wordgame.gamma-test.alice.yandex.net:8001
    - id: magic-ball
      addr: magic-ball.gamma-test.alice.yandex.net:8001
    - id: zoology
      addr: zoology.gamma-test.alice.yandex.net:8001
    - id: battleship
      addr: battleship.gamma-test.alice.yandex.net:8001
  metrics:
    timers:
      default:
        unit: 1ms
        buckets: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 175, 200, 225, 250, 300, 500, 1000]
      gamma/server/webhook/serveSkill:
        unit: 1ms
        buckets: [20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 175, 200, 225, 250, 300, 400, 500, 600, 1000]
    histograms:
      default:
        buckets: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 175, 200, 225, 250, 300, 500, 1000]
