clear_history:
  nlu:
    - очисти кэш
    - очистить историю
    - очисти историю
    - где кнопка очистить историю
    - как удалить историю
    - как очистить историю
    - очисть историю
    - удали историю
    - очистить историю поиска
    - удалить историю
    - удалить всю историю
    - очисти историю в яндексе
    - очисти историю поиска
    - очисти историю браузера
    - очистить историю браузера
    - очисти историю запросов
    - очисти историю яндекса
    - очистить историю в яндексе
    - стереть историю
    - очистить историю запросов
    - найди кнопку очистить историю
    - алиса очисти историю
    - очистить историю яндекса
    - удалить историю запросов
    - удалить историю поиска
    - как очистить твою историю
    - очисть историю яндекса
    - алиса очисть историю
    - кнопка очистить историю
    - покажи кнопку очистить историю
    - как очистить историю запросов
    - алиса очисти историю в яндексе
    - алиса как очистить историю
    - очистить историю сообщений
    - очисти всю историю
    - очисти свою историю
    - удали историю яндекса
    - удали историю диалога
    - как очистить историю поиска
    - очистить историю просмотров
    - очисти историю яндекс
    - очисти историю в браузере
    - очистить папку загрузки
    - удалить все из папки загрузки
    - очистить загрузки
    - очистить кэш
    - как очистить кэш
    - как почистить кэш
    - очисти кэш
    - почисти кэш
    - почистить кэш
    - как очистить кэш браузера
    - показать историю
    - удалить всю историю просмотров браузер
    - очисти историю
    - почисти историю
    - очисти историю плиз
    - алиса почисть историю плиз
    - почисть историю


new_tab:
  nlu:
    - создай вкладку
    - создай новую вкладку
    - открой новую вкладку
    - открой вкладку
    - новая вкладка
    - открой вкладки
    - открой новую вкладку в браузере
    - открыть новую вкладку
    - открой вкладку яндекс
    - визуальные закладки
    - открой визуальные закладки
    - открыть визуальные закладки
    - открой мне вкладку
    - открой новую вкладку в google хром
    - открыть вкладки
    - открой новую вкладку в яндекс браузере
    - открыть вкладку
    - открой новую вкладку в яндексе
    - открыть вкладку яндекс
    - открыть табло
    - открой табло
    - открой вкладку в браузере
    - открой вкладку google
    - открой вкладку в яндексе
    - открой новую вкладку инкогнито
    - алиса открой новую вкладку
    - открой новую вкладку в хроме
    - вкладки открой
    - стартовая страница
    - яндекс стартовая страница
    - слушай яндекс стартовая страница
    - открой страничку
    - открой стартовую страницу
    - создай вкладку
    - новую вкладку создай
    - запусти новую вкладку
    - новую вкладку запусти
    - визуальные закладки яндекс
    - яндекс визуальные закладки
    - визуальные закладки яндекса
    - новую вкладку открыла
    - открой пожалуйста новую вкладку
    - перейди на новую вкладку
    - открыть новую вкладку
    - открой новое окно в браузере
    - открыть новое окно в браузере
    - открой новое окно
    - открыть новое окно
    - открой новый таб
    - открой новый таб в браузере
    - открой окно браузера


go_home:
  nlu:
    - на домашнюю страницу
    - перейти на главную страницу яндекса
    - главную страницу яндекс
    - главную страницу яндекса
    - открыть яндекс страницу
    - выйти на главную страницу
    - страницу яндекса
    - открой страничку яндекса
    - открыть страничку яндекс
    - открой домашнюю страницу яндекс
    - открыть главную страницу яндекса
    - открыть страничку яндекса
    - открыть страницу яндекса
    - открыть яндекс домашнюю страницу
    - начальная страница яндекс
    - открой мне главную страницу яндекс
    - перейти на главную страницу
    - домашняя страница яндекса
    - вернуться на главную страницу
    - открыть стартовую страницу яндекс
    - главную страницу
    - яндекс главная страница
    - главная страница яндекс
    - главная страница
    - главная страница яндекса
    - открой главную страницу яндекс
    - открой главную страницу яндекса
    - открой главную страницу
    - яндекс открой главную страницу
    - слушай яндекс открой главную страницу
    - открыть главную страницу
    - открыть главную страницу яндекс
    - главную страницу яндекс
    - главную страницу яндекса
    - слушай яндекс главная страница
    - на главную страницу
    - выйти на главную страницу
    - открыть главную страницу яндекса
    - открой мне главную страницу яндекс
    - перейти на главную страницу
    - слушай яндекс главную страницу
    - слушай яндекс главная страница яндекс
    - вернуться на главную страницу
    - главную страницу
    - домашняя страница
    - открой домашнюю страницу
    - яндекс домашняя страница
    - домашняя страница яндекс
    - открой домашнюю страницу яндекс
    - открыть яндекс домашнюю страницу
    - панель управления домашняя страница
    - домашняя страница яндекса


open_incognito_mode:
  nlu:
    - открой новую вкладку инкогнито
    - режим инкогнито
    - открой вкладку инкогнито
    - инкогнито
    - открой инкогнито
    - открой браузер в режиме инкогнито
    - открой яндекс браузер в режиме инкогнито
    - открой режим инкогнито
    - включить режим инкогнито
    - включи режим инкогнито
    - открой вкладку в режиме инкогнито
    - новое окно в режиме инкогнито
    - открыть вкладку инкогнито
    - открой хром в режиме инкогнито
    - открыть режим инкогнито
    - запусти браузер в режиме инкогнито
    - запусти яндекс браузер в режиме инкогнито
    - открой браузер инкогнито
    - яндекс инкогнито
    - открой новую вкладку в режиме инкогнито
    - открой новое окно в режиме инкогнито
    - открой яндекс инкогнито
    - открой новую вкладку инкогнито
    - открой яндекс браузер инкогнито
    - открой яндекс в режиме инкогнито
    - включи инкогнито
    - вкладка инкогнито
    - открой вконтакте в режиме инкогнито
    - открыть браузер в режиме инкогнито
    - открой приватное окно
    - приватное окно
    - открой браузер в приватном режиме
    - приватный режим
    - яндекс браузер инкогнито
    - скрытый режим
    - открой вкладку в скрытом режиме
    - включи скрытый режим
    - запусти скрытный режим
    - открой браузер в скрытном режиме
    - открой браузер в скрытом режиме
    - в скрытный режим перейди


open_bookmarks_manager:
  nlu:
    - сверни панель закладок
    - закрой панель закладок
    - открой закладки
    - панель закладок
    - открыть панель закладок
    - запусти панель закладок
    - открой мне панель закладок
    - включи панель закладок
    - алиса открой панель закладок
    - панель закладок открой
    - открой пожалуйста панель закладок
    - открой панель закладок
    - панель закладок открыть
    - открыть панель закладок
    - запустить панель закладок
    - зайди в панель закладок
    - открой закладки
    - закладки
    - открыть закладки
    - открой мои закладки
    - мои закладки
    - открой закладку
    - открыть мои закладки
    - закладки открой
    - открой мне закладки
    - алиса открой закладки
    - яндекс закладки
    - открой закладки в браузере
    - открой все закладки
    - открой другие закладки
    - открой закладки браузера
    - найди закладку
    - покажи мои закладки
    - открой закладки яндекс
    - открой папку закладки
    - покажи закладки
    - включи закладки
    - открой менеджера браузер
    - открой менеджер закладок
    - менеджер закладок открой
    - запусти менеджер закладок


open_history:
  nlu:
    - открой историю браузера
    - история браузера
    - открой историю
    - история просмотров
    - открыть историю
    - открой историю яндекс браузера
    - история запросов
    - история поиска
    - открой историю в яндексе
    - покажи историю браузера
    - открой мне историю
    - показать историю
    - открой историю яндекс
    - история посещений
    - покажи мне историю
    - история яндекс браузера
    - история посещаемых страниц
    - открыть историю яндекса
    - открой историю браузера хром
    - браузер история открыть


close_browser:
  nlu:
    - закрой браузер
    - закрой все страницы
    - закрой все вкладки и выключи компьютер
    - закрыть все вкладки в яндексе
    - закрой все вкладки в яндексе
    - закрой все вкладки в браузере
    - закрыть все вкладки
    - закрой все вкладки
    - закрыть все страницы
    - выключи бразуер
    - браузер выключи
    - браузер закрой
    - пожалуйста закрой браузер
    - выключи все страницы
    - выключи все вкладки
    - выключи все вкладки браузера
    - закрой все вкладки браузера
    - прекратить работу браузер
    - завершить работу браузера
    - прекратить работу браузера
    - браузер закройся
    - слушай яндекс закрыть яндекс браузер
    - слушай яндекс отключить яндекс браузер
    - слушай яндекс убрать яндекс браузер
    - слушай яндекс закрыть браузер
    - слушай яндекс убрать браузер
    - слушай яндекс закрыть браузер опера
    - слушай яндекс отключить браузер
    - закрой яндекс
    - закрой яндекс браузер
    - закрой пожалуйста браузер
    - браузер закрой
    - закрыть браузер яндекс
    - закрой браузер яндекс
    - закрой пожалуйста браузер яндекс
    - пожалуйста закрой браузер
    - браузер яндекс закрой
    - яндекс браузер закрыть
    - закрой программу яндекс браузер
    - закрой браузер яндекс браузер
    - закрой приложение яндекс браузер


restore_tab:
  nlu:
    - открой старую вкладку
    - восстанови закрытую вкладку
    - восстановить вкладки
    - восстановить все вкладки
    - открой последние вкладки
    - вернуть страницу
    - открыть последнюю страницу
    - восстановить страницу
    - верни вкладку
    - верни страницу
    - вкладку верни
    - страницу верни
