files:
- name: /logs/current-gproxy.eventlog
  send_delay: 5
  topic: /alice-production/grpcproxy
  format: eventlog
  compression-out: 0
- name: /logs/current-gproxy.rtlog
  send_delay: 5
  topic: /alice-production/grpcproxy
  compression-out: 0
logger:
  file: /logs/push-client.log
  level: 5
  remote: 0
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
  proto: pq
  tvm-server-id: 2001059
  tvm-client-id: 2034161
watcher:
  state: /logs/push-client-state
