#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_yandex_alice_nlu_libs_fstnormalizer_FstNormalizer */

#ifndef _Included_ru_yandex_alice_nlu_libs_fstnormalizer_FstNormalizer
#define _Included_ru_yandex_alice_nlu_libs_fstnormalizer_FstNormalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_yandex_alice_nlu_libs_fstnormalizer_FstNormalizer
 * Method:    normalize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_yandex_alice_nlu_libs_fstnormalizer_FstNormalizer_normalize
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
