OWNER(
    g:alice_quality
)

RECURSE(
    ar_fst_entities
    binary_classifier
    build_entity_trie
    build_type_parser_dict
    entities
    fetch_diff
    gen_intent_classification_dataset
    gen_granet_test_config
    gen_ngram_frequency
    get_intent_guidelines
    handcrafted_phrases_checker
    lstm_classifier_trainer
    merge_dataset_info
    normalizer
    paraphrase_finder
    scripts
    test_begemot_parsing
    test_fst_entities
    tagger
    yt_respect_rewriter
    yt_tokenizer
)
