---
component:
  nanny:
    #https://abc.yandex-team.ru/services/dialogmanager/
    abc_group: 1459
    owners:
      #other id for the same group
      #https://abc.yandex-team.ru/services/dialogmanager/
      groups: [61987]
  sandboxResources:
    -
      dynamic: "false"
      id: "341072995"
      task_id: "146741790"
      task_type: "BUILD_STATBOX_PUSHCLIENT"
      resource_type: "STATBOX_PUSHCLIENT"
      localName: "push-client"
      extract: "false"
  environmentVariables:
    QLOUD_LOGGER_STDOUT_PARSER: "json_raw"
    VINS_QLOUD_PROJECT: "alice"
    VINS_QLOUD_APPLICATION: "vins"
    VINS_PUSH_LOGS_TO_YT: "0"
    VINS_LOG_FILE: "/logs/vins.push_client.out"
    VINS_RTLOG_FILE: '/logs/current-vins-rtlog'
    VINS_FEATURES_LOG_FILE: '/logs/vins-features.log'
