#pragma once

//////////////////////////////////////////////////////////////////////
// WARNING: this code was automatically generated by alice/json_schema_builder/tool,
// don't edit it manually.
//////////////////////////////////////////////////////////////////////

#include <alice/json_schema_builder/runtime/runtime.h>

namespace NAlice::NJsonSchemaBuilder::NDiv1 {

enum class EDivPredefinedSizeValue {
    WrapContent = 0 /* "wrap_content" */,
    MatchParent = 1 /* "match_parent" */,
};

enum class EDivContainerBlockDirection {
    Vertical = 0 /* "vertical" */,
    Horizontal = 1 /* "horizontal" */,
};

enum class EDivAlignmentVertical {
    Top = 0 /* "top" */,
    Center = 1 /* "center" */,
    Bottom = 2 /* "bottom" */,
};

enum class EDivAlignment {
    Left = 0 /* "left" */,
    Center = 1 /* "center" */,
    Right = 2 /* "right" */,
};

enum class EDivContainerBlockFrameStyle {
    Border = 0 /* "border" */,
    Shadow = 1 /* "shadow" */,
    OnlyRoundCorners = 2 /* "only_round_corners" */,
};

enum class EDivTextStyle {
    TextS = 0 /* "text_s" */,
    TextM = 1 /* "text_m" */,
    TextMMedium = 2 /* "text_m_medium" */,
    TextL = 3 /* "text_l" */,
    TitleS = 4 /* "title_s" */,
    TitleM = 5 /* "title_m" */,
    TitleL = 6 /* "title_l" */,
    NumbersS = 7 /* "numbers_s" */,
    NumbersM = 8 /* "numbers_m" */,
    NumbersL = 9 /* "numbers_l" */,
    CardHeader = 10 /* "card_header" */,
    Button = 11 /* "button" */,
};

enum class EDivSize {
    Zero = 0 /* "zero" */,
    Xxs = 1 /* "xxs" */,
    Xs = 2 /* "xs" */,
    S = 3 /* "s" */,
    M = 4 /* "m" */,
    L = 5 /* "l" */,
    Xl = 6 /* "xl" */,
    Xxl = 7 /* "xxl" */,
    MatchParent = 8 /* "match_parent" */,
};

enum class EDivPosition {
    Left = 0 /* "left" */,
    Right = 1 /* "right" */,
};

enum class EDivCustomTextStyleFontStyle {
    Light = 0 /* "light" */,
    Medium = 1 /* "medium" */,
    Regular = 2 /* "regular" */,
    Bold = 3 /* "bold" */,
};

enum class EDivSizeUnit {
    Sp = 0 /* "sp" */,
    Dp = 1 /* "dp" */,
};

}  // namespace NAlice::NJsonSchemaBuilder::NDiv1
