#pragma once

//////////////////////////////////////////////////////////////////////
// WARNING: this code was automatically generated by alice/json_schema_builder/tool,
// don't edit it manually.
//////////////////////////////////////////////////////////////////////

#include <alice/json_schema_builder/runtime/runtime.h>

namespace NAlice::NJsonSchemaBuilder::NDiv1 {

}  // namespace NAlice::NJsonSchemaBuilder::NDiv1
