//////////////////////////////////////////////////////////////////////
// WARNING: this code was automatically generated by alice/json_schema_builder/tool,
// don't edit it manually.
//////////////////////////////////////////////////////////////////////

#include "validate.h"

namespace NAlice::NJsonSchemaBuilder::NDiv1 {

NJson::TJsonValue Validate(NAlice::NJsonSchemaBuilder::NRuntime::TBuilder&& builder) {
    return std::move(builder).ValueWithoutValidation();
}

}  // namespace NAlice::NJsonSchemaBuilder::NDiv1
