"
"   VUNDLE configuration first
"
set nocompatible
filetype off
filetype plugin indent on


"
"   GENERIC VIM SETTINGS
"
ret 4
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent
set number
set numberwidth=8
sy on
set backspace=indent,eol,start
nnoremap <F3> :nohlsearch<CR>

nnoremap <F7> :tabp<CR>
nnoremap <F8> :tabn<CR>
