nirvana:
  quota: voice-core
  hitman_guid:


yt:
  token: robot-acoustic-team_yt_token
  proxy: hahn
  pool: voice
  mr_account: voice
  mr_output_ttl: 1
  mr_output_path: 'home[#if param["mr-account"] != meta.owner]/${param["mr-account"]}[/#if]/${meta.owner}/nirvana/marker_tests/${meta.operation_uid}'

yql:
  token: robot-acoustic-team_yql_token

arcanum:
  token: robot-acoustic-team-arcanum-token

soy:
  token: robot-voice-qa-soy-token

alice:
  uniproxy_url: 'wss://beta.uniproxy.alice.yandex.net/alice-uniproxy-asr-rm/uni.ws'
  vins_url: 'http://vins.hamster.alice.yandex.net/speechkit/app/pa/'
  oauth: bass_testing_analyst_token
  scraper_timeout: '12h'
  scraper_pool: alice
  asr_chunk_size: -1
  experiments:
