nirvana:
  quota: voice-analytics
  hitman_guid: 41f39437-f9fc-4ecf-b0de-7c8729a506b3


yt:
  token: robot-voice-qa_yt_token
  proxy: hahn
  pool: voice
  mr_account: alice
  mr_output_ttl: 1
  mr_output_path: 'home[#if param["mr-account"] != meta.owner]/${param["mr-account"]}[/#if]/${meta.owner}/nirvana/marker_tests/${meta.operation_uid}'

yql:
  token: robot-voice-qa_yql_token

arcanum:
  token: robot-voice-qa_arcanum_token

soy:
  token: robot-alicesoykpi-soy-token

alice:
  uniproxy_url: 'ws://uniproxy-kpi.alice.yandex.net/uni.ws'
  vins_url: 'http://vins.alice.yandex.net/speechkit/app/pa/'
  oauth: bass_testing_analyst_token
  scraper_timeout: '4h'
  scraper_pool: alice-kpi
  asr_chunk_size: -1
  experiments:
