---
rps: 1

# steelix_url: "https://dialogs.yandex.net/api"
steelix_url: "https://dialogs.priemka.voicetech.yandex.net/api"

steelix_tvm_id: 2016427

#skill_id: T
skill_id: ad26f8c2-fc31-4928-a653-d829fda7e6c2

#steelix_auth_type: tvm
#tvm_config:
#  client_name: bulbasaur
#  port: 18080
#  token: token_for_local_interaction_1234

steelix_auth_type: oauth
oauth_config:
  token: cool-developer-token

# datasource_type: db
# datasource_parameters:
#     prefix: "/ru/quasar/production/iotdb"
#     endpoint: ydb-ru.yandex.net:2135

datasource_type: config
datasource_parameters:
  users_id:
    - 78442638
