Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/home/vagrant/vins-dm"
  config.vm.synced_folder "~/.gnupg", "/home/vagrant/.gnupg"

  config.vm.network "forwarded_port",
                    guest: 8000, host: 8000,
                    auto_correct: true

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 5120
  end

  config.vm.provision :shell, path: "env_scripts/setup-env.sh"
end
