annotations:
  project: iot-steelix
meta:
  acl:
    - action: allow
      permissions:
        - read
        - write
        - create
        - ssh_access
        - root_ssh_access
        - read_secrets
      subjects:
        - abc:service:15893
        - abc:service:5558
  inherit_acl: true
  id: iot-steelix-testing
spec:
  account_id: abc:service:5558
  deploy_units:
    sas:
      images_for_boxes:
        steelix_server:
          name: quasar/steelix
          registry_host: registry.yandex.net
          tag: "5985872"
      network_defaults:
        network_id: _QUASAR_IOT_STEELIX_TEST_NETS_
      replica_set:
        per_cluster_settings:
          sas:
            pod_count: 1
        replica_set_template:
          constraints:
            antiaffinity_constraints:
              - key: rack
                max_pods: 1
          deployment_strategy:
            max_unavailable: 1
          pod_template_spec:
            spec:
              disk_volume_requests:
                - id: iot-steelix-testing-disk-0
                  labels:
                    used_by_infra: true
                  quota_policy:
                    capacity: 5368709120
                  storage_class: hdd
              host_infra:
                monitoring: {}
              ip6_address_requests:
                - enable_dns: true
                  network_id: _QUASAR_IOT_STEELIX_TEST_NETS_
                  vlan_id: backbone
                - enable_dns: true
                  network_id: _QUASAR_IOT_STEELIX_TEST_NETS_
                  vlan_id: fastbone
              pod_agent_payload:
                spec:
                  boxes:
                    - id: steelix_server
                      rootfs: {}
                  mutable_workloads:
                    - workload_ref: steelix
                  resources: {}
                  workloads:
                    - box_ref: steelix_server
                      env:
                        - name: CLOUD_TYPE
                          value:
                            literal_env:
                              value: deploy
                        - name: ENV_TYPE
                          value:
                            literal_env:
                              value: testing
                        - name: TVM_CLIENT_SECRET_2016205
                          value:
                            secret_env:
                              alias: tvm.secret.2016205:sec-01dpbhwa60y882afzmp2k6d60k:ver-01dpbhwacb640ph8tfpnzq4ykc
                              id: client_secret
                      id: steelix
                      liveness_check:
                        tcp_check:
                          port: 8080
                      readiness_check:
                        tcp_check:
                          port: 8080
                      start:
                        command_line: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
                      transmit_logs: true
              resource_requests:
                memory_guarantee: 536870912
                memory_limit: 536870912
                vcpu_guarantee: 250
                vcpu_limit: 250
              secrets:
                tvm.secret.2016205:sec-01dpbhwa60y882afzmp2k6d60k:ver-01dpbhwacb640ph8tfpnzq4ykc:
                  delegation_token: ZWFG4IPH6uX6_dEMy8Rd9LzzFRIMxYtJ0Rnl84svuJc.1.ae4f9bcaf025637c
                  secret_id: sec-01dpbhwa60y882afzmp2k6d60k
                  secret_version: ver-01dpbhwacb640ph8tfpnzq4ykc
