ydb:
    endpoint: ydb-ru.yandex.net:2135
    database: /ru/alice/prod/paskills_penguinary
    timeout: 5
    max_retries: 5
    root_folder: peng
    connect_params:
        use_tvm: True
        self_tvm_id: 2018900
        tvm_secret_env: TVM_SECRET

nodes_storage:
    cache_size: 256
    ttl: 6000
    warm_up:
        nodes_idx: [ skill_activation ]
        sleep_time: 60

logging:
    kikimr_level: WARN
    common_level: INFO

dssm:
    path: /dssm_model
    input_name: query
    output_name: query_embedding
    empty_inputs: [ expansion ]
    cache_size: 10000

model:
    thresh: 0.4
    dist_thresh_rel: lt
    metric: minkowski
    n_neighbors: 5
    p: 2

server:
    host: '[::]'
    port: '80'
    workers: 5
    timeout: 60

redis:
    turned_on: True
    address: 'redis://localhost'
    maxsize: 100000
