topic: /paskills/prod/penguinarium/logs

network:
    master-addr: logbroker.yandex.net
    proto: pq
    tvm-server-id: 2001059
    tvm-client-id: 2018900

watcher:
    state: /state/push-client

logger:
    mode: stderr

files:
    - name: /logs/server_logs.out
      topic: /paskills/prod/penguinarium/logs
    - name: /logs/server_logs.err
      topic: /paskills/prod/penguinarium/logs
