files:
- name: ./logs/current-hollywood-rtlog
  send_delay: 5
  log_type: hollywood-general_conversation
  format: eventlog
  compression-out: 0
  ident: alicelogs@prod
  streams: 5
logger:
  file: ./logs/push-client.log
  level: 5
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
  tvm-client-id: 2000464
  tvm-server-id: 2001059
  proto: pq
watcher:
  state: ./logs/push-client-state
