//
// Autogenerated file
// This file was created from directives.proto and directives.jinja2 template
//
// Don't edit it manually!
// Please refer to doc: https://TODO for more information about custom codegeneration
//

class TDirectivesWrapper {

    
    
    
    // Global methods
    void AddTCallbackDirectiveSample(const TStringBuf name = "callback_directive_sample");
    void AddTOpenDialogDirectiveSample(const TStringBuf name = "open_dialog_directive_sample");
    void AddTUpdateDialogInfoDirectiveSample(const TStringBuf name = "update_dialog_info_directive_sample");
    void AddTOpenUriDirectiveSample(const TStringBuf name = "open_uri_directive_sample");
    void AddTEndDialogSessionDirectiveSample(const TStringBuf name = "end_dialog_session_directive_sample");
    void AddTTypeTextDirectiveSample(const TStringBuf name = "type_text_directive_sample");
    void AddTStopBluetoothDirectiveSample(const TStringBuf name = "stop_bluetooth_directive");
    void AddTStartBluetoothDirectiveSample(const TStringBuf name = "start_bluetooth_directive");
    void AddTReadPageDirectiveSample(const TStringBuf name = "read_page_directive");
    void AddTReadPagePauseDirectiveSample(const TStringBuf name = "read_page_pause_directive");
    void AddTReadPageContinueDirectiveSample(const TStringBuf name = "read_page_continue_directive");
private:
    TDirectivesWrapperImpl* Impl_;
};

