lang: ru
shard_config: ../../extsearch/shard/data.yaml
inf_model: ed39ca24-9c30-441b-adfc-db48d0b5a793
inf_negatives_table: //home/voice/krom/mutual_information/negatives
indexes:
    base:
        table: //home/voice/dialog/indexes/base/2shards_20112019_factorDssmBertDistill2/context_and_reply
        used: //home/voice/dialog/indexes/base/shard0_20112019_factorDssmBertDistill2/context_and_reply
    assessors:
        table: //home/voice/krom/assessors_index_28012020_factorDssmBertDistill2/context_and_reply
    movie:
        table: //home/voice/alzaharov/boltalka-66/all_segmented_review_yandex_only/context_and_reply
        index_type: reply
pools:
    - //home/voice/dialog/reranker_pools/selective/pool11_20190314_20190612_searchappprod
    - //home/voice/dialog/reranker_pools/selective/pool12_logs_20190613_20190813_searchappprod
    - //home/voice/dialog/reranker_pools/selective/pool13
    - //home/voice/dialog/reranker_pools/selective/pool14
    - //home/voice/dialog/reranker_pools/seq2seq/pool11
    - //home/voice/dialog/reranker_pools/seq2seq/pool12
    - //home/voice/dialog/reranker_pools/seq2seq/pool13
    - //home/voice/dialog/reranker_pools/seq2seq/pool14
validation_pools:
    - //home/voice/dialog/reranker_pools/selective/pool12_logs_20190613_20190813_searchappprod
    - //home/voice/dialog/reranker_pools/seq2seq/pool12