- name: personal_assistant.handcrafted.quasar
  pattern: ^personal_assistant.handcrafted.quasar.*
- name: personal_assistant.handcrafted
  pattern: ^personal_assistant.handcrafted.*
- name: personal_assistant.scenarios.hny
  pattern: ^personal_assistant.scenarios.(hny|happy_new_year).*
- name: personal_assistant.stroka
  pattern: ^personal_assistant.stroka.*
- name: personal_assistant.scenarios.market
  pattern: ^personal_assistant.scenarios.market.*
- name: personal_assistant.scenarios.serp_gallery
  pattern: ^personal_assistant.scenarios.serp_gallery.*
- name: personal_assistant.navi
  pattern: personal_assistant.navi.*
- name: personal_assistant.scenarios.alarm
  pattern: personal_assistant.scenarios.alarm.*
- name: personal_assistant.scenarios.music
  pattern: personal_assistant.scenarios.music.*
- name: personal_assistant.scenarios.player
  pattern: personal_assistant.scenarios.player.*
- name: personal_assistant.scenarios.quasar
  pattern: personal_assistant.scenarios.quasar.*
- name: personal_assistant.scenarios.sound
  pattern: personal_assistant.scenarios.sound.*
- name: personal_assistant.scenarios.taxi_new
  pattern: personal_assistant.scenarios.taxi_new.*
- name: personal_assistant.scenarios.timer
  pattern: personal_assistant.scenarios.timer.*
