children:
  classifiers:
    children:
      scenarios:
        patterns_file: 'personal_assistant/config/chunk_patterns.yaml'
        prune_suffix_by: __
      search_or_converse:
        depth: 0
  custom_entities:
    ignore: True
  tagger:
    children:
      tagger.data:
        patterns_file: 'personal_assistant/config/chunk_patterns.yaml'
        prune_suffix_by: __
