feedback_negative_buttons:
- &feedback_negative__asr_error
  title: "Моя речь не распозналась"
  text: "Не нравится: моя речь не распозналась"
  name: feedback_negative__asr_error
- &feedback_negative__bad_answer
  title: "Ответ не соответствует запросу"
  text: "Не нравится: ответ не соответствует запросу"
  name: feedback_negative__bad_answer
- &feedback_negative__offensive_answer
  title: "Ответ обидный или оскорбительный"
  text: "Не нравится: ответ обидный или оскорбительный"
  name: feedback_negative__offensive_answer
- &feedback_negative__other
  title: "Проблема в другом"
  text: "Не нравится: проблема в другом"
  name: feedback_negative__other
- &feedback_negative__tts_error
  title: "Неверно озвучен текст"
  text: "Не нравится: неверно озвучен текст"
  name: feedback_negative__tts_error
- &feedback_negative_images__barcode_wrong
  title: "Код распознан неправильно"
  text: "Не нравится: код распознан неправильно"
  name: feedback_negative_images__barcode_wrong
- &feedback_negative_images__barcode_unwanted
  title: "Не нужно было распознавать код"
  text: "Не нравится: не нужно было распознавать код"
  name: feedback_negative_images__barcode_unwanted
- &feedback_negative_images__clothes_unwanted
  title: "Мне не нужно искать одежду"
  text: "Не нравится: не нужно искать одежду"
  name: feedback_negative_images__clothes_unwanted
- &feedback_negative_images__market_link
  title: "По ссылке неправильные товары"
  text: "Не нравится: по ссылке неправильные товары"
  name: feedback_negative_images__market_link
- &feedback_negative_images__market_poor
  title: "Товары не похожи на то, что мне нужно"
  text: "Не нравится: товары не похожи на то, что нужно"
  name: feedback_negative_images__market_poor
- &feedback_negative_images__market_unwanted
  title: "Мне не нужны товары"
  text: "Не нравится: товары не нужны"
  name: feedback_negative_images__market_unwanted
- &feedback_negative_images__ocr_poor
  title: "Текст распознался плохо"
  text: "Не нравится: текст распознался плохо"
  name: feedback_negative_images__ocr_poor
- &feedback_negative_images__ocr_translate
  title: "Плохой перевод"
  text: "Не нравится: плохой перевод"
  name: feedback_negative_images__ocr_translate
- &feedback_negative_images__ocr_unwanted
  title: "Мне не нужно распознавать текст"
  text: "Не нравится: не нужно распознавать текст"
  name: feedback_negative_images__ocr_unwanted
- &feedback_negative_images__tag_wrong
  title: "Объект распознан неверно"
  text: "Не нравится: объект распознан неверно"
  name: feedback_negative_images__tag_wrong
- &feedback_negative_images__unsimilar
  title: "Нашлись непохожие картинки"
  text: "Не нравится: непохожие картинки"
  name: feedback_negative_images__unsimilar
- &feedback_negative_images__useless
  title: "Ответ бесполезен"
  text: "Не нравится: ответ бесполезен"
  name: feedback_negative_images__useless

special_buttons:
- type: like_button
  text: "Нравится"
  name: feedback_positive
- type: dislike_button
  text: "Не нравится"
  name: feedback_negative
  sub_list:
    title: "Что вам не понравилось?"
    default_buttons:
      - *feedback_negative__bad_answer
      - *feedback_negative__asr_error
      - *feedback_negative__tts_error
      - *feedback_negative__offensive_answer
      - *feedback_negative__other
    default:
      title: "Не хочу уточнять"
      text: "Не нравится"
      name: feedback_negative__other
