rules:
- type: logic_rule
  operation: and
  boost: 0
  children:
  - prev_intent: personal_assistant.scenarios.list_reminders
    curr_intent: personal_assistant.scenarios.list_reminders__scroll_next
    type: check_prev_curr_intent
  - type: logic_rule
    operation: or
    children:
    - slot: answer
      slot_value_key: type
      value: textandvoice
      type: check_form_slot_value
    - type: logic_rule
      operation: and
      children:
      - slot: answer
        slot_value_key: total_reminders_count
        value: 0
        type: check_form_slot_value
      - slot: answer
        slot_value_key: type
        value: voice
        type: check_form_slot_value

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.list_reminders
  curr_intent: personal_assistant.scenarios.list_reminders__scroll_next
  boost: 1.1

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.create_reminder__cancel
  curr_intent: personal_assistant.scenarios.create_reminder__cancel
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.create_reminder__cancel
  curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.create_todo__cancel
  curr_intent: personal_assistant.scenarios.create_todo__cancel
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.create_todo__cancel
  curr_intent: personal_assistant.scenarios.create_todo__ellipsis
  boost: 0

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: logic_rule
    operation: or
    children:
    - prev_intent: personal_assistant.scenarios.list_reminders__scroll_next
      curr_intent: personal_assistant.scenarios.list_reminders__scroll_next
      type: check_prev_curr_intent
    - prev_intent: personal_assistant.scenarios.list_reminders__scroll_next
      curr_intent: personal_assistant.scenarios.list_reminders__scroll_reset
      type: check_prev_curr_intent
    - prev_intent: personal_assistant.scenarios.list_reminders__scroll_next
      curr_intent: personal_assistant.scenarios.list_reminders__scroll_stop
      type: check_prev_curr_intent
  - slot: answer
    slot_value_key: is_finish
    value: 'yes'
    type: check_form_slot_value

- type: logic_rule
  operation: or
  boost: 0
  children:
  - prev_intent: personal_assistant.scenarios.list_reminders__scroll_stop
    curr_intent: personal_assistant.scenarios.list_reminders__scroll_next
    type: check_prev_curr_intent
  - prev_intent: personal_assistant.scenarios.list_reminders__scroll_stop
    curr_intent: personal_assistant.scenarios.list_reminders__scroll_reset
    type: check_prev_curr_intent
  - prev_intent: personal_assistant.scenarios.list_reminders__scroll_stop
    curr_intent: personal_assistant.scenarios.list_reminders__scroll_stop
    type: check_prev_curr_intent

- type: logic_rule
  operation: and
  boost: 0
  children:
  - prev_intent: personal_assistant.scenarios.list_todo
    curr_intent: personal_assistant.scenarios.list_todo__scroll_next
    type: check_prev_curr_intent
  - type: logic_rule
    operation: or
    children:
    - slot: answer
      slot_value_key: type
      value: textandvoice
      type: check_form_slot_value
    - type: logic_rule
      operation: and
      children:
      - slot: answer
        slot_value_key: total_todo_count
        value: 0
        type: check_form_slot_value
      - slot: answer
        slot_value_key: type
        value: voice
        type: check_form_slot_value


- type: logic_rule
  operation: and
  boost: 0
  children:
  - prev_intent: personal_assistant.scenarios.list_todo__scroll_next
    curr_intent: personal_assistant.scenarios.list_todo__scroll_next
    type: check_prev_curr_intent
  - slot: answer
    slot_value_key: is_finish
    value: 'yes'
    type: check_form_slot_value

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_reminder
  curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
  boost: 4.0

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_reminder
  curr_intent: personal_assistant.scenarios.create_reminder__cancel
  boost: 3.0

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_reminder__ellipsis
  curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
  boost: 2.0

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: logic_rule
    operation: or
    children:
    - prev_intent: personal_assistant.scenarios.create_reminder__ellipsis
      curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
      type: check_prev_curr_intent
    - prev_intent: personal_assistant.scenarios.create_reminder
      curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
      type: check_prev_curr_intent
  - slot: answer
    slot_value_key: type
    value: 'ok'
    type: check_form_slot_value


- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_reminder__ellipsis
  curr_intent: personal_assistant.scenarios.create_reminder__cancel
  boost: 1.5

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: logic_rule
    operation: or
    children:
    - prev_intent: personal_assistant.scenarios.create_reminder
      curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
      type: check_prev_curr_intent
    - prev_intent: personal_assistant.scenarios.create_reminder
      curr_intent: personal_assistant.scenarios.create_reminder__cancel
      type: check_prev_curr_intent
  - slot: is_forbidden
    value: true
    type: check_form_slot_value

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_todo
  curr_intent: personal_assistant.scenarios.create_todo__ellipsis
  boost: 4.0

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_todo
  curr_intent: personal_assistant.scenarios.create_todo__cancel
  boost: 3.0

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_todo__ellipsis
  curr_intent: personal_assistant.scenarios.create_todo__ellipsis
  boost: 2.0

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: logic_rule
    operation: or
    children:
    - prev_intent: personal_assistant.scenarios.create_todo__ellipsis
      curr_intent: personal_assistant.scenarios.create_todo__ellipsis
      type: check_prev_curr_intent
    - prev_intent: personal_assistant.scenarios.create_todo
      curr_intent: personal_assistant.scenarios.create_todo__ellipsis
      type: check_prev_curr_intent
  - slot: answer
    slot_value_key: type
    value: 'ok'
    type: check_form_slot_value

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.create_todo__ellipsis
  curr_intent: personal_assistant.scenarios.create_todo__cancel
  boost: 1.5

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.onboarding__cancel
  curr_intent: personal_assistant.scenarios.onboarding__cancel
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.onboarding__cancel
  curr_intent: personal_assistant.scenarios.onboarding__next
  boost: 0

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: unconditional
    curr_intent: personal_assistant.scenarios.search__related
  - type: check_form_slot_value
    slot: related_query
    value: null

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: logic_rule
    operation: or
    children:
    - prev_intent: personal_assistant.scenarios.skill_recommendation__next
      curr_intent: personal_assistant.scenarios.skill_recommendation__next
      type: check_prev_curr_intent
    - prev_intent: personal_assistant.scenarios.skill_recommendation
      curr_intent: personal_assistant.scenarios.skill_recommendation__next
      type: check_prev_curr_intent
  - slot: card_name
    value: '^(?!(onboarding|games_onboarding)$).*$'
    type: check_form_slot_value

- type: logic_rule
  operation: and
  boost: 5.0
  children:
  - type: logic_rule
    operation: or
    children:
    - type: check_form_active_slots
      prev_intent: personal_assistant.navi.add_point
      curr_intent: personal_assistant.navi.add_point__ellipsis
    - type: check_form_active_slots
      prev_intent: personal_assistant.navi.add_point
      curr_intent: personal_assistant.navi.add_point__cancel
  - type: logic_rule
    operation: or
    children:
    - slot: road_event
      value: 'talk'
      type: check_form_slot_value
    - slot: road_event
      value: 'error'
      type: check_form_slot_value
    - slot: road_event
      value: 'other'
      type: check_form_slot_value

- type: check_prev_curr_intent
  prev_intent:
  - personal_assistant.scenarios.create_reminder
  - personal_assistant.scenarios.create_reminder__ellipsis
  curr_intent: personal_assistant.scenarios.create_reminder__ellipsis
  boost: 1.1

- type: check_prev_curr_intent
  prev_intent:
  - personal_assistant.scenarios.alarm_cancel
  - personal_assistant.scenarios.alarm_cancel__ellipsis
  - personal_assistant.scenarios.alarm_show
  - personal_assistant.scenarios.alarm_show__cancel
  - personal_assistant.scenarios.timer_cancel
  - personal_assistant.scenarios.timer_cancel__ellipsis
  - personal_assistant.scenarios.timer_resume
  - personal_assistant.scenarios.timer_resume__ellipsis
  - personal_assistant.scenarios.timer_pause
  - personal_assistant.scenarios.timer_pause__ellipsis
  - personal_assistant.scenarios.timer_show
  - personal_assistant.scenarios.timer_show__cancel
  - personal_assistant.scenarios.timer_show__pause
  - personal_assistant.scenarios.timer_show__resume
  curr_intent: personal_assistant.scenarios.common.cancel_list
  boost: 1.03

- type: allow_prev_intents
  prev_intents:
  - personal_assistant.scenarios.taxi_new_after_order_actions
  - personal_assistant.scenarios.taxi_new_call_to_driver
  - personal_assistant.scenarios.taxi_new_call_to_driver_internal
  - personal_assistant.scenarios.taxi_new_call_to_support
  - personal_assistant.scenarios.taxi_new_cancel__confirmation_no
  - personal_assistant.scenarios.taxi_new_cancel__confirmation_yes
  - personal_assistant.scenarios.taxi_new_change
  - personal_assistant.scenarios.taxi_new_disabled
  - personal_assistant.scenarios.taxi_new_open_app
  - personal_assistant.scenarios.taxi_new_order
  - personal_assistant.scenarios.taxi_new_order__change_card
  - personal_assistant.scenarios.taxi_new_order__change_payment_or_tariff
  - personal_assistant.scenarios.taxi_new_order__confirmation_no
  - personal_assistant.scenarios.taxi_new_order__confirmation_wrong
  - personal_assistant.scenarios.taxi_new_order__confirmation_yes
  - personal_assistant.scenarios.taxi_new_order__select_card
  - personal_assistant.scenarios.taxi_new_show_driver_info
  - personal_assistant.scenarios.taxi_new_show_legal
  - personal_assistant.scenarios.taxi_new_status
  - personal_assistant.scenarios.taxi_new_status_address
  - personal_assistant.scenarios.taxi_new_status_price
  - personal_assistant.scenarios.taxi_new_status_time
  curr_intent: personal_assistant.scenarios.common.cancel_order
  boost: 1.000000001

- type: allow_prev_intents
  prev_intents:
  - personal_assistant.scenarios.taxi_new_after_order_actions
  - personal_assistant.scenarios.taxi_new_call_to_driver
  - personal_assistant.scenarios.taxi_new_call_to_driver_internal
  - personal_assistant.scenarios.taxi_new_call_to_support
  - personal_assistant.scenarios.taxi_new_cancel__confirmation_no
  - personal_assistant.scenarios.taxi_new_cancel__confirmation_yes
  - personal_assistant.scenarios.taxi_new_change
  - personal_assistant.scenarios.taxi_new_disabled
  - personal_assistant.scenarios.taxi_new_open_app
  - personal_assistant.scenarios.taxi_new_order
  - personal_assistant.scenarios.taxi_new_order__change_card
  - personal_assistant.scenarios.taxi_new_order__change_payment_or_tariff
  - personal_assistant.scenarios.taxi_new_order__confirmation_no
  - personal_assistant.scenarios.taxi_new_order__confirmation_wrong
  - personal_assistant.scenarios.taxi_new_order__confirmation_yes
  - personal_assistant.scenarios.taxi_new_order__select_card
  - personal_assistant.scenarios.taxi_new_show_driver_info
  - personal_assistant.scenarios.taxi_new_show_legal
  - personal_assistant.scenarios.taxi_new_status
  - personal_assistant.scenarios.taxi_new_status_address
  - personal_assistant.scenarios.taxi_new_status_price
  - personal_assistant.scenarios.taxi_new_status_time
  curr_intent: personal_assistant.scenarios.common.open_app
  boost: 1.000000001

- type: allow_prev_intents
  prev_intents:
  - personal_assistant.scenarios.taxi_new_after_order_actions
  - personal_assistant.scenarios.taxi_new_call_to_driver
  - personal_assistant.scenarios.taxi_new_call_to_driver_internal
  - personal_assistant.scenarios.taxi_new_call_to_support
  - personal_assistant.scenarios.taxi_new_cancel__confirmation_no
  - personal_assistant.scenarios.taxi_new_cancel__confirmation_yes
  - personal_assistant.scenarios.taxi_new_change
  - personal_assistant.scenarios.taxi_new_disabled
  - personal_assistant.scenarios.taxi_new_open_app
  - personal_assistant.scenarios.taxi_new_order
  - personal_assistant.scenarios.taxi_new_order__change_card
  - personal_assistant.scenarios.taxi_new_order__change_payment_or_tariff
  - personal_assistant.scenarios.taxi_new_order__confirmation_no
  - personal_assistant.scenarios.taxi_new_order__confirmation_wrong
  - personal_assistant.scenarios.taxi_new_order__confirmation_yes
  - personal_assistant.scenarios.taxi_new_order__select_card
  - personal_assistant.scenarios.taxi_new_show_driver_info
  - personal_assistant.scenarios.taxi_new_show_legal
  - personal_assistant.scenarios.taxi_new_status
  - personal_assistant.scenarios.taxi_new_status_address
  - personal_assistant.scenarios.taxi_new_status_price
  - personal_assistant.scenarios.taxi_new_status_time
  curr_intent: personal_assistant.scenarios.common.call_to_support
  boost: 1.000000001

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.taxi_new_order
  curr_intent: personal_assistant.scenarios.taxi_new_order__specify
  boost: 1.4

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.taxi_new_order__confirmation_wrong
  curr_intent: personal_assistant.scenarios.taxi_new_order__specify
  boost: 1.4

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.taxi_new_order__specify
  curr_intent: personal_assistant.scenarios.taxi_new_order__specify
  boost: 1.4

- type: check_prev_curr_intent
  prev_intent:
  - personal_assistant.scenarios.taxi_new_order__change_payment_or_tariff
  - personal_assistant.scenarios.taxi_new_order__confirmation_wrong
  - personal_assistant.scenarios.taxi_new_order__specify
  - personal_assistant.scenarios.taxi_new_order
  curr_intent: personal_assistant.scenarios.taxi_new_order__change_payment_or_tariff
  boost: 1.00001

# can be activated only after taxi_new intents
- type: unconditional
  curr_intent: personal_assistant.scenarios.taxi_new_where_is_my_car
  boost: 1.000002

- type: unconditional
  curr_intent: personal_assistant.scenarios.taxi_new_status_price
  boost: 1.000001

- type: unconditional
  curr_intent: personal_assistant.scenarios.taxi_new_status_time
  boost: 1.000001

- type: unconditional
  curr_intent: personal_assistant.scenarios.ether_show
  boost: 1.000002

- type: allow_prev_intents
  prev_intents:
  - personal_assistant.scenarios.common.change # disabled intent
  curr_intent: personal_assistant.scenarios.common.change
  boost: 1.03

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.taxi_order
  curr_intent: personal_assistant.scenarios.taxi_order__ellipsis
  boost: 1.3

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.show_route
  curr_intent: personal_assistant.scenarios.show_route__ellipsis
  boost: 2.

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.avia
  curr_intent: personal_assistant.scenarios.avia__ask_to
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.avia__ask_to
  curr_intent: personal_assistant.scenarios.avia__ask_to
  boost: 1.40

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.serp_gallery__item_continuation
  curr_intent: personal_assistant.scenarios.serp_gallery__item_continuation
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.serp_gallery__item_continuation
  curr_intent: personal_assistant.scenarios.serp_gallery__item_stop
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.serp_gallery__item_stop
  curr_intent: personal_assistant.scenarios.serp_gallery__item_continuation
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.serp_gallery__item_stop
  curr_intent: personal_assistant.scenarios.serp_gallery__item_stop
  boost: 0

- type: check_form_active_slots
  prev_intent: personal_assistant.scenarios.open_site_or_app
  curr_intent: personal_assistant.scenarios.open_site_or_app__ellipsis
  boost: 2.1

- type: unconditional
  curr_intent: personal_assistant.scenarios.open_site_or_app__ellipsis
  boost: 0.5

- type: unconditional
  curr_intent: personal_assistant.scenarios.market__garbage
  boost: 0.99

- type: unconditional
  curr_intent: personal_assistant.scenarios.recurring_purchase__garbage
  boost: 0.99

- type: unconditional
  curr_intent: personal_assistant.scenarios.confirmation_yes
  boost: 1.000001

- type: unconditional
  curr_intent: personal_assistant.scenarios.confirmation_no
  boost: 1.000001

- type: unconditional
  curr_intent: personal_assistant.stroka.open_settings
  boost: 1.000001

- type: unconditional
  curr_intent: personal_assistant.scenarios.market__checkout_delivery_intervals
  boost: 0.9999

- type: unconditional
  curr_intent: personal_assistant.scenarios.recurring_purchase__checkout_delivery_intervals
  boost: 0.9999

- type: logic_rule
  operation: and
  boost: 0
  children:
  - type: unconditional
    curr_intent: personal_assistant.scenarios.music_what_is_playing__play
  - type: check_form_slot_value
    slot: answer
    value: null

# it already checks for prev intents and active slots in VinsProjectfile
- type: unconditional
  curr_intent: personal_assistant.scenarios.alarm_ask_sound
  boost: 1.37

# it already checks for prev intents and active slots in VinsProjectfile
- type: unconditional
  curr_intent: personal_assistant.scenarios.alarm_ask_time
  boost: 1.17

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.alarm_cancel
  curr_intent: personal_assistant.scenarios.quasar.select_ether_from_gallery_by_text
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.cancel_todo
  curr_intent: personal_assistant.scenarios.quasar.select_ether_from_gallery_by_text
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.timer_cancel
  curr_intent: personal_assistant.scenarios.quasar.select_ether_from_gallery_by_text
  boost: 0

- type: check_prev_curr_intent
  prev_intent: personal_assistant.scenarios.list_reminders
  curr_intent: personal_assistant.scenarios.quasar.select_ether_from_gallery_by_text
  boost: 0

- type: logic_rule
  operation: and
  children:
  - type: logic_rule
    operation: or
    children:
    - type: check_prev_curr_intent
      prev_intent: personal_assistant.internal.bugreport
      curr_intent: personal_assistant.internal.bugreport__continue
    - type: check_prev_curr_intent
      prev_intent: personal_assistant.internal.bugreport
      curr_intent: personal_assistant.internal.bugreport__deactivate
  - type: check_form_slot_value
    slot: report_id
    value: null
  boost: 0
