TwoNamesakeEgors = {
    'data': {
        'is_known_uuid': True,
        'contacts': [
            {
                'last_time_contacted': 0,
                'contact_id': 149,
                'account_name': 'Skype',
                'second_name': 'Сосед',
                '_id': 596,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск',
                'middle_name': 'По',
                'times_contacted': 0,
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'account_type': 'com.skype.raider',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 149,
                'account_name': 'primary.sim2.account_name',
                'second_name': 'Сосед',
                '_id': 597,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск',
                'middle_name': 'По',
                'times_contacted': 0,
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 149,
                'account_name': 'WhatsApp',
                'second_name': 'Сосед',
                '_id': 598,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск',
                'middle_name': 'По',
                'times_contacted': 0,
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'account_type': 'com.whatsapp',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 149,
                'account_name': '872adf6db7ba4b0ee30239329203d7c8@gmail.com',
                'second_name': 'Сосед',
                '_id': 599,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск',
                'middle_name': 'По',
                'times_contacted': 0,
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'account_type': 'com.google',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 10,
                'account_name': 'Skype',
                'second_name': 'Мурманск',
                '_id': 40,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск Пархоменко',
                'middle_name': 'Пархоменко',
                'times_contacted': 0,
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'account_type': 'com.skype.raider',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 10,
                'account_name': 'primary.sim2.account_name',
                'second_name': 'Мурманск',
                '_id': 41,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск Пархоменко',
                'middle_name': 'Пархоменко',
                'times_contacted': 0,
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 10,
                'account_name': 'WhatsApp',
                'second_name': 'Мурманск',
                '_id': 42,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск Пархоменко',
                'middle_name': 'Пархоменко',
                'times_contacted': 0,
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'account_type': 'com.whatsapp',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 10,
                'account_name': '872adf6db7ba4b0ee30239329203d7c8@gmail.com',
                'second_name': 'Мурманск',
                '_id': 43,
                'first_name': 'Егор',
                'display_name': 'Егор Мурманск Пархоменко',
                'middle_name': 'Пархоменко',
                'times_contacted': 0,
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'account_type': 'com.google',
            },
        ],
        'phones': [
            {
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'phone': '+74694831964',
                '_id': 40,
                'type': 'mobile',
                'account_type': 'com.skype.raider',
            },
            {
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'phone': '+74694831964',
                '_id': 41,
                'type': 'mobile',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'phone': '+74694831964',
                '_id': 42,
                'type': 'mobile',
                'account_type': 'com.whatsapp',
            },
            {
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'phone': '+74694831964',
                '_id': 43,
                'type': 'mobile',
                'account_type': 'com.google',
            },
            {
                'lookup_key': 'b28f7f625a8c6fa6ff0c9',
                'phone': '+76439704739',
                '_id': 44,
                'type': 'mobile',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'phone': '+76223099129',
                '_id': 596,
                'type': 'mobile',
                'account_type': 'com.skype.raider',
            },
            {
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'phone': '+76223099129',
                '_id': 597,
                'type': 'mobile',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'phone': '+76223099129',
                '_id': 598,
                'type': 'mobile',
                'account_type': 'com.whatsapp',
            },
            {
                'lookup_key': 'eab9dad60848f4f41a0e6',
                'phone': '+76223099129',
                '_id': 599,
                'type': 'mobile',
                'account_type': 'com.google',
            },
        ],
    },
    'status': 'ok',
}

ThreeSashas = {
    'data': {
        'is_known_uuid': True,
        'contacts': [
            {
                'last_time_contacted': 0,
                'contact_id': 0,
                'account_name': 'primary.sim2.account_name',
                'second_name': '',
                '_id': 0,
                'first_name': 'Саша',
                'display_name': 'Саша',
                'middle_name': '',
                'times_contacted': 0,
                'lookup_key_index': 0,
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 1,
                'account_name': 'primary.sim2.account_name',
                'second_name': 'Белый',
                '_id': 1,
                'first_name': 'Саша',
                'display_name': 'Саша 2 Белый',
                'middle_name': '2',
                'times_contacted': 0,
                'lookup_key_index': 1,
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'last_time_contacted': 0,
                'contact_id': 2,
                'account_name': 'primary.sim2.account_name',
                'second_name': 'Белый',
                '_id': 2,
                'first_name': 'Саша',
                'display_name': 'Саша Белый',
                'middle_name': '',
                'times_contacted': 0,
                'lookup_key_index': 2,
                'account_type': 'vnd.sec.contact.sim2',
            },
        ],
        'phones': [
            {
                'lookup_key_index': 0,
                'phone': '+70439814931',
                '_id': 0,
                'type': 'mobile',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'lookup_key_index': 1,
                'phone': '+7123123123',
                '_id': 1,
                'type': 'mobile',
                'account_type': 'vnd.sec.contact.sim2',
            },
            {
                'lookup_key_index': 2,
                'phone': '88005553535',
                '_id': 2,
                'type': 'mobile',
                'account_type': 'vnd.sec.contact.sim2',
            },
        ],
        'lookup_key_map_serialized': 'SDRzSUFBQUFBQUFBQS1OaTUySk9UazRXWU9KaTVXSk9URXprQXZLVGtwSUVHQUdpQ2pjWEdRQUFBQSws',
    },
    'status': 'ok',
}
