hny.general:
  nlu:
    - алиса как праздник
    - ты будешь праздновать новый год
    - алиса ты празднуешь новый год
    - а ты отмечаешь новый год
    - как отмечать будешь
    - новый год отмечаешь алиса
    - с наступающим новым годом тебя
    - алиса с наступающим новым годом
    - как отмечаешь
    - как отдыхаем как отдыхаем на новый год
    - как у тебя новый год прошел
    - алиса а ты как нибудь отмечаешь новый год
    - алиса как ты проводишь свой новый год
    - алиса как новый год с правила
    - а как ты новый год отпраздновала
    - Как новый год
    - а как ты празднуешь новый год
    - как отдыхаем в новый год
    - спасибо как будет проходить этот новый год
    - как ты празднуешь новый год
    - Как к новому году готовитесь
    - как новый год будешь праздновать
    - как отдыхаем на новый год
    - что на новый год то будем делать
    - алиса как на новый год будем отмечать
    - как будешь отмечать новый год
    - как справить этот новый год
    - как нам встретить новый год
    - что делать на новый год
    - как подготовиться к новому году
    - как отпраздновать новый год
    - как отметить новый год
    - как встретить новый год
    - что делать в новый год
    - что делать на новый год
    - как отметить праздник новый год
    - как провести праздник новый год
    - как встретить новый год
    - новый год
    - чо блядь новый год
    - чо блять новый год
    - че там с новым годом
    - что там с новым годом
    - что делать на новый год епта
    - как отметить новый год епта
    - слышь чо делать на новый год
    - как тусить на новый год
    - как зажигать в новый год
    - как не проебать новый год
    - как не про-ебать новый год
    - слышь как отметить новый год
    - как отметить праздник новый год
    - как не пропустить новый год
    - что делать в праздники
    - что делать на праздники
    - чем заняться на праздниках
    - как провести время на праздниках
    - что мне делать в праздники
    - что нам делать на праздники
    - как провести время на праздниках
    - чем занять себя на праздниках
    - как будем отдыхать на новогодние праздники
    - что делать на праздниках когда скучно
    - что ты делаешь на праздниках
    - алиса чем заняться на праздниках
    - что делать на праздниках
    - как провести новогодние праздники
    - чем заняться на новогодних праздниках
    - что делать в новогодние праздники
    - как провести каникулы
    - что делать на каникулах
    - чем заняться на каникулах
    - как провести время на каникулах
    - как провести время на каникулах
    - чем занять себя на каникулах
    - как будем отдыхать на новогодних каникулах
    - что делать на каникулах когда скучно
    - что ты делаешь на каникулах
    - алиса чем заняться на каникулах
    - что делать на каникулах
    - как провести новогодние каникулы
    - чем заняться на новогодних каникулах
    - что делать в новогодние каникулы
    - что мне делать на каникулах
    - что нам делать на каникулах
  nlg:
    - Вы по адресу — я приготовила кое-что особенное. Знаменитый режиссёр посоветует вам новогодние фильмы, популярная певица поделится своей любимой музыкой, а самый известный российский техноблогер поможет выбрать подарки. Осторожно — это затягивает.
    - С наступающим! Вы по адресу — я успела задать этот вопрос звёздам и блогерам, которые отлично разбираются в музыке, еде, нарядах и других важных новогодних вещах. Даже думать не нужно — выбирайте!
    - Вы по адресу. Я тут времени зря не теряла — собрала звёзд и блогеров, которые отлично разбираются в музыке, еде, нарядах и других важных новогодних вещах. Ответ на ваш вопрос где-то здесь.

hny.have_fun:
  nlu:
    - куда сгонять на праздниках
    - куда пойти на праздники
    - куда сходить на праздниках
    - куда сгонять на каникулах
    - куда пойти на каникулах
    - куда сходить на каникулах
    - где провести новый год
    - где можно встретить новый год
    - что можно посетить на праздниках
    - подскажи куда сходить во время новогодних каникул
    - а куда можно пойти на новогодних каникулах
    - а куда можно пойти на каникулах
    - куда можно пойти на новый год
    - куда сходить на новый год
    - что посетить на новый год
    - какие места на новый год
    - какие места посетить на новый год
    - какие места можно посетить на новый год
    - места для нового года
    - посетить места на праздниках
    - посетить на праздниках
    - куда нам сходить на новый год
    - куда нам сходить на праздниках
    - куда мне сходить на праздники
    - куда мне сходить на новый год
    - где бы отметить новый год
    - где отметить новый год
    - где отмечать новый год
    - где можно отмечать новый год
    - лучшие места для нового года
    - лучшие места для праздников
    - лучшие места чтобы развлечься на новый год
    - лучшие места чтобы отметить новый год
    - посоветуй лучшие места чтобы отметить новый год
    - посоветуй лучшие места для нового года
    - посоветуй лучшие места для нового года
    - хочу пойти на праздники
    - хочу куда нибудь пойти на праздники
    - хочу куда нибудь сходить на праздники
    - хочу куда нибудь сходить на новый год
    - хочу интересные места на новый год
    - хочу интересные места на новогодних каникулах
    - подскажи интересные места на новогодних каникулах
    - подскажи интересные места на новый год
  nlg:
    - Самое главное — провести праздник с теми, кого любите. А идеи я уже собрала. Причём не простые!

hny.cook:
  nlu:
    - что приготовить на новый год
    - чем кормить гостей на новый год
    - что сожрать на новый год
    - чего бы похавать на новый год
    - что похавать на новый год
    - новогодние салаты
    - что подать на новый год
    - что подать к новогоднему столу
    - что поесть на новый год
    - что захомячить на новый год
    - чем закусить на новый год
    - чем удивить гостей на новый год
    - что интересного приготовить на новый год
    - что пожрать на новый год
    - что сожрать на новый год
    - что бы такого съесть на новый год
    - чего бы такого съесть на новый год
    - чего бы такого приготовить на новый год
    - рецепт новогоднего салата
    - что еще приготовить
    - еще что приготовить
    - что едят на новый год
    - что готовить на новый год
    - что приготовить на новый год две тысячи девятнадцать
    - что можно приготовить на новый год
    - Чем угощать
    - Что приготовить на Новый год
    - Рецепт новогодних блюд
    - Новогодние рецепты
    - Что приготовить на праздники
    - что поесть на праздники
    - что покушать на праздники
    - что приготовить на праздники
    - чем кормить гостей на праздники
    - что сожрать на праздники
    - чего бы похавать на праздники
    - что похавать на праздники
    - праздничные салаты
    - что подать на праздники
    - что подать к праздничному столу
    - что поесть на праздники
    - что захомячить на праздники
    - чем закусить на праздники
    - чем удивить гостей на праздники
    - что интересного приготовить на праздники
    - что пожрать на праздники
    - что сожрать на праздники
    - что бы такого съесть на праздники
    - чего бы такого съесть на праздники
    - чего бы такого приготовить на праздники
    - рецепты праздничных блюд
    - что еще приготовить на праздники
    - еще что приготовить на новый год
    - что едят на  праздники
    - что готовить на праздники
    - что приготовить на праздники две тысячи девятнадцать
    - что можно приготовить на праздники
    - Чем угощать друзей
    - чем угощать семью
    - Что приготовить на праздники
    - Рецепт  праздничных блюд
    - Праздничные рецепты
    - Что приготовить на праздники
  nlg:
    - Вам что, оливье уже надоел? Шутка. У меня тут есть кое-что, смотрите.

hny.decorate:
  nlu:
    - как украсить дом на новый год
    - чем украсить дом на новый год
    - а ты украшаешь елку на новый год
    - как красиво украсить комнату
    - как украсить зал
    - как украсить дверь в прихожей
    - как мне украсить комнату
    - пример как украсить елку
    - чем можно украсить комнату на новый год
    - как украсить новый дом к новому году
    - Чем украсить дом зимой
    - Чем украсить дом
    - как украсить комнату
    - как украсить елку
    - украшения на новый год
    - праздничные украшения
    - украшения на праздник
    - новогодний декор
    - праздничный декор
    - как красиво украсить дом
    - как красиво украсить квартиру
    - как украсить комнату
    - как украсить гостинную
    - как украсить зал
    - как красиво украсить дом на новый год
    - как красиво украсить квартиру на новый год
    - как украсить комнату на новый год
    - как украсить гостинную на новый год
    - как украсить зал на новый год
    - чем красиво украсить дом
    - чем красиво украсить квартиру
    - чем украсить комнату
    - чем украсить гостинную
    - чем украсить зал
    - чем красиво украсить дом на новый год
    - чем красиво украсить квартиру на новый год
    - чем украсить комнату на новый год
    - чем украсить гостинную на новый год
    - чем украсить зал на новый год
    - как украшать елку
    - как украсить елку
    - какие украшения повесить на елку
    - как подготовить квартиру к празднику
    - как подготовить дом к празднику
    - как подготовить комнату к празднику
    - как подготовить зал к празднику
    - как подготовить гостинную к празднику
    - как украшать елку на новый год
    - как украсить елку на новый год
    - какие украшения повесить на елку на новый год
    - как подготовить квартиру к празднику на новый год
    - как подготовить дом к празднику на новый год
    - как подготовить комнату к празднику на новый год
    - как подготовить зал к празднику на новый год
    - как подготовить гостинную к празднику на новый год
  nlg:
    - Я в дизайне не сильна. Зато знакома с людьми, которые умеют создать новогодний уют.

hny.wear:
  nlu:
    - в чем встретить новый год
    - что надеть на новогоднюю ночь
    - что надеть в новогодню ночь
    - что надеть на корпоратив
    - что надеть на корпорат
    - что одеть на новогоднюю ночь
    - что одеть в новогодню ночь
    - что одеть на корпоратив
    - что одеть на корпорат
    - как нарядиться
    - во что нарядиться
    - как выбрать наряд
    - какой выбрать наряд
    - какой одеть наряд
    - какой надеть наряд
    - как выбрать костюм
    - какой выбрать костюм
    - какой одеть костюм
    - какой надеть костюм
    - как нарядиться
    - во что нарядиться
    - как выбрать наряд на новый год
    - какой выбрать наряд на новый год
    - какой одеть наряд на новый год
    - какой надеть наряд на новый год
    - как выбрать костюм на новый год
    - какой выбрать костюм на новый год
    - какой одеть костюм на новый год
    - какой надеть костюм на новый год
    - как нарядиться на праздник
    - во что нарядиться на праздник
    - как выбрать наряд на праздник
    - какой выбрать наряд на праздник
    - какой одеть наряд на праздник
    - какой надеть наряд на праздник
    - как выбрать костюм на праздник
    - какой выбрать костюм на праздник
    - какой одеть костюм на праздник
    - какой надеть костюм на праздник
    - как одеться на корпоратив
    - в чем пойти на новогоднюю вечеринку
    - в чем пойти на новогодний праздник
    - какое платье в этом году одеть на новый год
    - что мне одеть на новый год
    - новогодний карнавальный костюм
    - костюм на новый год девочкам
    - что одеть на корпоратив
    - костюмы на новый год
    - что одеть на новый год 2019
    - что одеть на новый год
    - Новогодний наряд
    - В чём встретить Новый год
    - Что надеть
    - Новогодний наряд
    - Что надеть на новый год
  nlg:
    - 'Зависит от вашей фантазии. Или от того, какие идеи вы найдёте здесь. Предупреждаю: будет красиво.'

hny.offer:
  nlu:
    - что подарить на новый год
    - алиса посоветуй подарок на новый год
    - алиса что подарить на новый год
    - что можно подарить маме на новый год
    - что дарить нужно
    - алиса что подарить родителям на новый год
    - а на новый год что подарить на новый год
    - что можно подарить ребенку на новый год
    - алиса подскажи подарок на новый год
    - алиса что подарить бабушке на новый год
    - алиса что можно подарить на новый год
    - а что жене подарить на новый год
    - алиса что подарить жене на новый год
    - что подарить на новый год мужу
    - что подарить надо
    - а что дарить
    - что подарить детям на новый год
    - алиса какой подарок подарить
    - что подарить девушке на новый год
    - а что подарить
    - что подарить маме на новый год
    - алиса что подарить
    - что подарить жене на новый год
    - что подарить
    - что подарить ребенку на новый год
    - что подарить подруге на новый год
    - Что тебе на Новый год подарить
    - что можно подарить на новый год
    - что подарить на новый год не знаю
    - что подарить сестре на новый год
    - что мне подарить другу на новый год
    - что подарить бабушке на новый год
    - ну что дарить
    - что подарить парню на новый год
    - что подарить на новый год
    - алиса что подарить на новый год
    - что дарить
    - Что подарить на Новый год
    - подскажи подарок
    - подарки на новый год
    - Что подарить на новый год
  nlg:
    - Важно, чтобы подарок был от сердца. А что выбрать, расскажут компетентные люди.

hny.varlamov:
  nlu:
    - илья варламов
    - варламов
    - коллекция ильи варламова
    - коллекция варламова
    - коллекция от ильи варламова
    - коллекция от варламова
  nlg:
    - Илья Варламов.

hny.suhov:
  nlu:
    - сухов
    - сергей сухов
    - коллекция сухова
    - коллекция сергея сухова
    - коллекция от сухова
    - коллекция от сергея сухова
  nlg:
    - Сергей Сухов.

hny.trubenkova:
  nlu:
    - полина трубенкова
    - коллекция полины трубенковой
    - коллекция от полины трубенковой
  nlg:
    - Полина Трубенкова.

hny.may:
  nlu:
    - энни мэй
    - Anny May
    - коллекция энни мэй
    - коллекция от энни мэй
  nlg:
    - Anny May.

hny.bubenitta:
  nlu:
    - bubenitta
    - бубенитта
    - коллекция бубенитта
    - коллекция бубенитты
    - коллекция bubenitta
    - коллекция от бубенитта
    - коллекция от бубенитты
    - коллекция от bubenitta
  nlg:
    - Bubenitta.

hny.wylsacom:
  nlu:
    - wylsacom
    - вилсы
    - вилсаком
    - вилсакома
    - коллекция вилсакома
    - коллекция вилсы
    - коллекция wylsacom
    - вилса
  nlg:
    - Wylsacom.

hny.smetana:
  nlu:
    - сметана тв
    - коллекция сметана тв
    - коллекция от сметана тв
  nlg:
    - Сметана ТВ.

hny.slivki:
  nlu:
    - сливки шоу
    - коллекция сливки шоу
    - коллекция от сливки шоу
  nlg:
    - SlivkiShow.

hny.semenihin:
  nlu:
    - денис семенихин
    - коллекция дениса семенихина
    - коллекция от дениса семенихина
  nlg:
    - Денис Семенихин.

hny.pokashevarim:
  nlu:
    - покашеварим
    - коллекция покашеварим
  nlg:
    - Покашеварим.

hny.anohina:
  nlu:
    - айза анохина
    - коллекция айзы анохиной
    - коллекция от айзы анохиной
  nlg:
    - Айза Анохина.

hny.lisovec:
  nlu:
    - влад лисовец
    - коллекция влада лисовца
    - коллекция от влада лисовца
  nlg:
    - Владислав Лисовец.

hny.viskunova:
  nlu:
    - мария вискунова
    - маша вискунова
    - коллекция марии вискуновой
    - коллекция маши вискуновой
    - коллекция от марии вискуновой
    - коллекция от маши вискуновой
  nlg:
    - Мария Вискунова.

hny.jarahov:
  nlu:
    - джарахов
    - Эльдар Джарахов
    - коллекция джарахова
    - коллекция Эльдар Джарахов
    - коллекция от джарахова
    - коллекция от Эльдар Джарахова
  nlg:
    - Эльдар Джарахов.

hny.gagarina:
  nlu:
    - полина гагарина
    - коллекция полины гагариной
    - коллекция от полины гагариной
  nlg:
    - Полина Гагарина.

hny.dakota:
  nlu:
    - рита дакота
    - коллекция риты дакота
    - коллекция от риты дакота
  nlg:
    - Рита Дакота.

hny.review:
  nlu:
    - chuck review
    - чак ревью
    - коллекция чака ревью
    - коллекция чак ревью
    - коллекция chuck review
    - коллекция от чак ревью
    - коллекция от chuck review
  nlg:
    - Chuck Review.

hny.bekmambetov:
  nlu:
    - тимур бекмамбетов
    - бекмамбетов
    - коллекция тимура бекмамбетова
    - коллекция бекмамбетова
    - коллекция от тимура бекмамбетова
    - коллекция от бекмамбетова
  nlg:
    - Тимур Бекмамбетов.

hny.parfenon:
  nlu:
    - парфенон
    - парфенов
    - леонид парфенов
    - коллекция парфенона
    - коллекция леонида парфенона
    - коллекция парфенова
    - коллекция от парфенона
    - коллекция от парфенова
  nlg:
    - Леонид Парфенов.

hny.grilkov:
  nlu:
    - грильков
    - коллекция грилькова
    - коллекция от грилькова
  nlg:
    - Грильков.

hny.badcomedian:
  nlu:
    - bad comedian
    - бэд комедиан
    - badcomedian
    - коллекция bad comedian
    - коллекция от bad comedian
  nlg:
    - BadComedian.

hny.present:
  nlu:
    - с новым годом
    - ну ладно с наступающим
    - у тебя с новым годом
    - Класс с наступающим
    - с наступающим праздником
    - Всегда пожалуйста с наступающим
    - с новым здоровье и счастье
    - ну с праздником
    - с праздником
    - с праздником алиса
    - алиса с праздником
    - отлично с наступающим вас
    - с новым годом поздравляю тебя с новым годом поздравляю тебя
    - ну ладно с наступающим вас
    - алиса с наступающим праздником
    - алиса с праздником тебя с новым счастьем удачи
    - с праздником наступающим
    - поздравь меня с новым годом
    - круто с наступающим год
    - поздравляю с новым
    - ладно с наступающим
    - поздравляю тебя с наступающим
    - почему ты алиса с новым годом
    - с наступающим праздником тебя
    - с праздником с наступающим тебя
    - Поздравляю с праздником
    - с наступающим тебя алиса
    - с наступающим алиса
    - с наступающим
    - с наступившим
    - с новым годом что с новым годом
    - С наступающим новым годом
    - тост с новым годом
    - короче алиса с новым годом
    - привет с новым годом
    - с новым годом тебя желаю
    - новый год с тобой
    - алиса поздравляю тебя с новым годом
    - ну с новым годом тогда
    - поздравляю с новым годом
    - с еврейским новым годом
    - с новым годом говорю
    - с новым годом тебя
    - алиса с новым годом тебя
    - скажи с новым годом
    - с новым годом пожалуйста
    - поздравление с новым годом
    - ну все с новым годом
    - с новым годом всего новым годом
    - поздравь с новым годом
    - с новым годом тоже
    - с новым годом алиса
  nlg:
    - С Новым годом!
