LIBRARY()

OWNER(
    g:hollywood
)

PEERDIR(
    alice/hollywood/library/scenarios/alarm
    alice/hollywood/library/scenarios/alice_show
    alice/hollywood/library/scenarios/blueprints
    alice/hollywood/library/scenarios/bluetooth
    alice/hollywood/library/scenarios/bugreport
    alice/hollywood/library/scenarios/cec_commands
    alice/hollywood/library/scenarios/count_aloud
    alice/hollywood/library/scenarios/do_nothing
    alice/hollywood/library/scenarios/draw_picture
    alice/hollywood/library/scenarios/equalizer
    alice/hollywood/library/scenarios/fast_command
    alice/hollywood/library/scenarios/food
    alice/hollywood/library/scenarios/get_date
    alice/hollywood/library/scenarios/get_time
    alice/hollywood/library/scenarios/goods
    alice/hollywood/library/scenarios/goodwin
    alice/hollywood/library/scenarios/happy_new_year
    alice/hollywood/library/scenarios/hardcoded_response
    alice/hollywood/library/scenarios/how_to_spell
    alice/hollywood/library/scenarios/image_what_is_this
    alice/hollywood/library/scenarios/link_a_remote
    alice/hollywood/library/scenarios/maps_download_offline
    alice/hollywood/library/scenarios/market
    alice/hollywood/library/scenarios/market/how_much
    alice/hollywood/library/scenarios/messenger_call
    alice/hollywood/library/scenarios/metronome
    alice/hollywood/library/scenarios/mordovia_video_selection
    alice/hollywood/library/scenarios/music
    alice/hollywood/library/scenarios/music_what_is_playing
    alice/hollywood/library/scenarios/news
    alice/hollywood/library/scenarios/notifications
    alice/hollywood/library/scenarios/onboarding
    alice/hollywood/library/scenarios/onboarding_critical_update
    alice/hollywood/library/scenarios/order
    alice/hollywood/library/scenarios/random_number
    alice/hollywood/library/scenarios/reask
    alice/hollywood/library/scenarios/reminders
    alice/hollywood/library/scenarios/repeat
    alice/hollywood/library/scenarios/repeat_after_me
    alice/hollywood/library/scenarios/route_manager
    alice/hollywood/library/scenarios/search
    alice/hollywood/library/scenarios/settings
    alice/hollywood/library/scenarios/show_gif
    alice/hollywood/library/scenarios/show_traffic_bass
    alice/hollywood/library/scenarios/smart_device/external_app
    alice/hollywood/library/scenarios/sssss
    alice/hollywood/library/scenarios/subscriptions_manager
    alice/hollywood/library/scenarios/taximeter
    alice/hollywood/library/scenarios/test_scenario
    alice/hollywood/library/scenarios/time_capsule
    alice/hollywood/library/scenarios/tr_navi/add_point
    alice/hollywood/library/scenarios/tr_navi/find_poi
    alice/hollywood/library/scenarios/tr_navi/general_conversation
    alice/hollywood/library/scenarios/tr_navi/get_my_location
    alice/hollywood/library/scenarios/tr_navi/get_weather
    alice/hollywood/library/scenarios/tr_navi/handcrafted
    alice/hollywood/library/scenarios/tr_navi/navi_external_confirmation
    alice/hollywood/library/scenarios/tr_navi/show_route
    alice/hollywood/library/scenarios/tr_navi/switch_layer
    alice/hollywood/library/scenarios/transform_face
    alice/hollywood/library/scenarios/tv_channels
    alice/hollywood/library/scenarios/tv_channels_efir
    alice/hollywood/library/scenarios/tv_controls
    alice/hollywood/library/scenarios/video
    alice/hollywood/library/scenarios/video_musical_clips
    alice/hollywood/library/scenarios/video_rater
    alice/hollywood/library/scenarios/video_recommendation
    alice/hollywood/library/scenarios/vins
    alice/hollywood/library/scenarios/voice
    alice/hollywood/library/scenarios/voiceprint
    alice/hollywood/library/scenarios/watch_list
    alice/hollywood/library/scenarios/weather
    alice/hollywood/library/scenarios/zen_search
    alice/hollywood/library/scenarios/zero_testing
)

END()
