saas-daemon-port: ${SAAS_DAEMON_PORT:19024}
tv-channel-indexer.saas-indexer.url: http://localhost:${saas-daemon-port}/push/smart_tv_channels
tv-channel-indexer.saas-indexer.connect_timeout: 30
tv-channel-indexer.saas-indexer.timeout: 1000
tv-channel-indexer.saas-indexer.max_connections: 150

tv-channel-indexer.saas-search.url: http://saas-searchproxy-prestable.yandex.net:17000/
tv-channel-indexer.saas-search.service-name: smart_tv_channels
tv-channel-indexer.saas-search.timeout: 1000
tv-channel-indexer.saas-search.connect_timeout: 30
tv-channel-indexer.saas-search.max_connections: 50

tv-channel.plus-image:
tv-channels.vh-url: https://frontend.vh.yandex.ru/
tv-channels.vh-read-timeout: 3000
tv-channels.vh-connect-timeout: 30
tv-channels.vh-max-connections: 50
