paskillsConfig.database.multihost: ${PG_MULTI_HOST}
paskillsConfig.database.databaseName: ${PG_DATABASENAME}
paskillsConfig.database.user: ${PG_USER}
paskillsConfig.database.pass: ${PG_PASSWORD}
paskillsConfig.database.poolSizeIdle: ${PG_POOL_SIZE_IDLE:1}
paskillsConfig.database.poolSizeMax: ${PG_POOL_SIZE_MAX:10}
thereminConfig.baseS3Url: https://dialogs.s3.yandex.net/
