status:
  port: 16301

storages:
- name: metrics_storage
  plugin: fs
  config:
    directory: /var/cache/unified_agent
    max_partition_size: 100mb

routes:
- input:
    plugin: metrics_pull
    config:
      url: http://localhost:8081/services/idm/solomon
      format:
        solomon_json: { }
      metric_name_label: sensor

      project: jupyter-cloud
      service: idm
  channel:
    channel_ref:
      name: solomon_output

channels:
- name: solomon_output
  channel:
    pipe:
    - storage_ref:
        name: metrics_storage
    output:
      plugin: metrics_pull
      config:
        port: 8900
