version: '3'
services:
  smart-home:
    container_name: smart_home
    restart: always
    build: smart_home
    ports:
      - 8000:8000
    expose:
      - 8000

  elephant:
    container_name: elephant
    restart: always
    build: elephant
    ports:
      - 8001:8001
    expose:
      - 8001

  parrot:
    container_name: parrot
    restart: always
    build: parrot
    ports:
      - 8002:8002
    expose:
      - 8002

  nginx:
    container_name: nginx
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - smart-home
      - elephant
      - parrot

  front:
    container_name: front
    restart: always
    build: front
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - nginx
      - smart-home
      - elephant
      - parrot