tvm:
  port: 18080
  service_name: iot-time-machine
  token:

worker:
  process_num: 10
  task_chunk_size: 20

pg_broker:
  hosts:
    - sas-e7hsayw7tokn8hdp.db.yandex.net
    - vla-gairo6dcdy2iy5zo.db.yandex.net
    - man-iuivdtgkxwg2oovh.db.yandex.net
  port: 6432
  db: time_machine_db
  user: time_machine
  password: password_placeholder
