tvm:
  port: 18080
  service_name: iot-time-machine-dev
  token:

worker:
  process_num: 2
  task_chunk_size: 10

pg_broker:
  hosts:
    - sas-6o10yskqt6svs0mk.db.yandex.net
  port: 6432
  db: time_machine_db
  user: time_machine
  password: password_placeholder

server:
  allowed_tvm_clients:
    - 2009295
