tvm:
  port: 18080
  service_name: iot-time-machine
  token:

worker:
  process_num: 40
  task_chunk_size: 30

pg_broker:
  hosts:
    - sas-2d2644k858cgqnii.db.yandex.net
    - vla-8c797dych3qzn5xu.db.yandex.net
    - man-1nu8c33x0g2lsbvc.db.yandex.net
  port: 6432
  db: time_machine_db
  user: time_machine
  password: password_placeholder
