RESOURCE_FILES(
    data/bad_stable_responses/input_table.json
    data/bad_stable_responses/megamind_analytics_info_checker.json
    data/bad_stable_responses/meta_checker.json
    data/bad_stable_responses/tunneller_checker.json

    data/bad_test_responses/input_table.json
    data/bad_test_responses/megamind_analytics_info_checker.json
    data/bad_test_responses/meta_checker.json
    data/bad_test_responses/tunneller_checker.json

    data/good_responses/input_table.json
    data/good_responses/megamind_analytics_info_checker.json
    data/good_responses/meta_checker.json
    data/good_responses/tunneller_checker.json
)
