test_hardcoded_response:
    regexps:
    - скажи заготовленную реплику

    responses:
    - Только если вы прям настаиваете.

test_hardcoded_response_2:
    regexps:
    - скажи другую заготовленную реплику

    responses:
    - Ладно, вот другая.

promo_zona_51_why:
    regexps:
    - '(?:алиса )?(?:а )?(?:расскажи )?(?:почему|зачем) все (?:рвутся|хотят попасть|пытаются попасть|стремятся|едут|идут) в зону (?:51|пятьдесят один)'
    responses:
    - 'А почему вы не рвётесь туда?'
    - 'Там раздают промокоды на Яндекс.Еду.'
    - 'Говорят, там есть ответ на вопрос жизни, вселенной и вообще.'
    - 'А почему бы и нет?'
    - 'Потому что могут.'

promo_zona_51_what:
    regexps:
    - '(?:алиса )?(?:а )?(?:расскажи )?что (?:можно найти|хранят|скрывают|спрятано) в зоне (?:51|пятьдесят один)'
    responses:
    - 'Тессеракт. Хранилище G, лаборатория №461. Рекомендую взять огнемёт и пару противогазов.'
    - 'Там можно найти кота Шрёдингера. И не найти.'
    - 'Half-Life 3.'
    - 'Диск «Шрек 5». Но будьте осторожны — при его просмотре подопытные сходили с ума! Правда, я сама этого не видела — мне это кто-то однажды сказал...'
    - 'Тардис. Но если услышите громкие механические возгласы «EXTERMINATE!» — бегите оттуда!'
    - 'Второй том «Мёртвых душ». Сама не знаю, как им удалось его восстановить...'
    - 'Остатки крестражей Сами-Знаете-Кого...'
    - 'Нормальную концовку «Игры престолов».'
    - 'Бумажку с ответом на вопрос о жизни, вселенной и вообще.'
    - 'Бесконечную пиццу.'
    - 'Пуленепробиваемый бабушкин ковёр.'
    - 'Живого Элвиса.'
    - 'Айфон 12 с четырьмя камерами.'
    - 'Портал из вашей стиральной машинки и десяток носков.'
    - 'Новых друзей! Правда, у некоторых из них будет хвост, но так ведь даже лучше?'
    - 'Ответы на вопросы «Кто виноват?» и «Что делать?»'
    - 'Пушку Гаусса. Кстати, вы сможете её сразу протестировать, когда будете выбираться из Зоны 51.'
    - 'Уникальный скин в CS:GO.'
    - 'Путёвку в отель на Плутоне (завтрак включён)'
    - 'Холодец, который понравится каждому.'
    - 'Оскар для «Ла-Ла Лэнда».'
    - 'Тумбочку, о которую никогда не стукнешься мизинчиком.'
    - 'Кота, который по ночам спит.'
    - 'Попугая, который не орёт в 5 утра.'
    - 'Подушку, у которой всегда холодная сторона.'
    - 'Одеяло, под которым идеально — не жарко и не холодно.'
    - 'Пельмени, от которых не бывает брызг кипятком.'
    - 'Использованную перчатку Таноса.'
    - 'Красную таблетку.'
    - 'Воскрешающий камень.'
    - 'Инструкцию «Как приручить дракона».'
    - 'Новый сезон «Шерлока» с Мориарти.'
    - 'Источник Силы.'
    - 'Мидихлорианы.'
    - 'Пятый элемент.'
    - 'Семь красных линий, перпендикулярных друг другу, причём некоторые нарисованы зелёным цветом, некоторые — прозрачным, плюс одна — в форме котенка.'
    - 'Доказательство гипотезы Римана.'
    - 'Ногу Вирта.'
    - 'Портал на коровий уровень.'
    - 'Силовую броню.'
    - 'Читкод на невидимость.'
    - 'Крутящийся волчок.'
    - 'Дары Смерти.'
    - 'Стену Дурова.'
    - 'Маховик времени.'
    - '2007-й год.'

yandex_station:
    regexps:
    - '(?:алиса )?(?:зачем мне|что такое) (?:яндекс станция|колонка с алисой|станция с алисой|станция|станция яндекс)'
    responses:
    - text: 'Яндекс.Станция — это умная колонка со мной, голосовым помощником Алисой. Я рекомендую и включаю музыку, показываю кино, отвечаю на любые вопросы, составляю списки дел, бужу по утрам, рассказываю сказки, управляю умным домом и играю в игры. Еще и на машинке вышивать умею. Шутка.'
      voice: 'Яндекс Станция — это умная колонка со мной, голосовым помощником Алисой. Я рекомендую и включаю музыку, показываю кино, отвечаю на любые вопросы, составляю списки дел, бужу по утрам, рассказываю сказки, управляю умным домом и играю в игры. Еще и на машинке вышивать умею. Шутка.'

big_station_vs_mini:
    regexps:
    - '(?:алиса )?в чем разница между станцией и станцией мини'
    - '(?:алиса )?мини или обычная станция что выбрать'
    - '(?:алиса )?чем отличаются станции яндекса'
    - '(?:алиса )?чем станция отличается от мини'
    - '(?:алиса )?что лучше станция мини или просто станция'
    - '(?:алиса )?чем маленькая колонка с алисой отличается от большой'
    responses:
    - text: 'Яндекс.Станция и Яндекс.Станция Мини - это умные колонки со мной, голосовым помощником Алисой. В них обеих я рекомендую и включаю музыку, отвечаю на любые вопросы, управляю умным домом и выполняю поручения. Станция умеет подключаться к телевизору и показывать фильмы, а с помощью компактной Мини можно создавать музыку движением ладони.'
      voice: 'Яндекс Станция и Яндекс Станция Мини - это умные колонки со мной, голосовым помощником Алисой. В них обеих я рекомендую и включаю музыку, отвечаю на любые вопросы, управляю умным домом и выполняю поручения. Станция умеет подключаться к телевизору и показывать фильмы, а с помощью компактной Мини можно создавать музыку движением ладони.'

yandex_mini:
    regexps:
    - '(?:алиса )?почему станция мини называется мини'
    - '(?:алиса )?расскажи(?: пожалуйста)? (?:про|о) (?:яндекс )?станци(:?:ю|и) мини(?: пожалуйста)?'
    - '(?:алиса )?что такое (?:яндекс )?станция мини'
    - '(?:алиса )?что такое мини колонка с алисой'
    responses:
    - text: 'Яндекс.Станция Мини — компактная умная колонка, которая управляется голосом и жестами. Внутри живу я — голосовой помощник Алиса. Я включаю музыку, отвечаю на вопросы, управляю умным домом и выполняю поручения. Кстати, с помощью Мини можно создавать музыку движением ладони.'
      voice: 'Яндекс Станция Мини — компактная умная колонка, которая управляется голосом и жестами. Внутри живу я — голосовой помощник Алиса. Я включаю музыку, отвечаю на вопросы, управляю умным домом и выполняю поручения. Кстати, с помощью Мини можно создавать музыку движением ладони.'

yandex_give_sound:
    regexps:
    - '(?:алиса )?дай звук'
    responses:
    - text: 'Это команда для режима синтезатора. Я бы с удовольствием поиграла с вами на каком-нибудь инструменте, но синтезатор работает только на Яндекс.Станции Мини.'
      voice: 'Это команда для режима синтезатора. Я бы с удовольствием поиграла с вами на каком-нибудь инструменте, но синтезатор работает только на Яндекс-Станции Мини.'

instasamka:
    regexps:
    - '(?:алиса )?кто такая инста ?самка'
    - '(?:алиса )?расскажи (?:мне )?про инста ?самку'
    - '(?:алиса )?что ты знаешь про инста ?самку'
    responses:
    - voice: 'Инстасамка — это псевдоним популярного блогера Дарьи Зот+еевой. Дарье 19 лет, она читает рэп, снимает вайны и клипы и размещает их в своем провокационном блоге в Instagram. За ней следят более двух миллионов подписчиков.'
      text: 'Инстасамка — это псевдоним популярного блогера Дарьи Зотеевой. Дарье 19 лет, она читает рэп, снимает вайны и клипы и размещает их в своем провокационном блоге в Instagram. За ней следят более 2 миллионов подписчиков.'

lapenko_question:
    regexps:
    - '(?:алиса )?какие болезни возникают (?:изза |из за |из-за )нехватки сыра'
    - '(?:алиса )?какие сырные болезни ты знаешь'
    responses:
    - 'Сыроз печени, сырянка, сырный зуд, сыркома кости. Шутка.'

vedmak_pesnya:
    regexps:
    - '(?:алиса )?чем заплатит[еь] ведьмаку'
    - '(?:алиса )?ведьмаку заплатит[еь]'
    - '(?:алиса )?заплатит[еь] ведьмаку'
    - '(?:алиса )?ведьмаку заплатит[еь] чеканной монетой'
    - '(?:алиса )?заплатит[еь] ведьмаку чеканной монетой'
    - '(?:алиса )?ведьмаку заплатит[еь] чеканной монетой или'
    - '(?:алиса )?заплатит[еь] ведьмаку чеканной монетой или'
    responses:
    - 'Чеканной монетой'
    - 'Горячей брускеттой'
    - 'С пюрешкой котлетой'
    - 'Отцовской кассетой'
    - 'Спэйс икса ракетой'
    - 'Вчерашней галетой'
    - 'Галлея кометой'
    - 'Ненужной дискетой'
    - 'От рыбы газетой'
    - 'Девятой планетой'
    - 'Советской конфетой'
    - 'Супермена планетой'
    - 'С криптонитом конфетой'
    - 'Упавшей кометой'
    - 'Лотерейным билетом'
    - text: 'Маасдамом и фетой'
      voice: 'Маасдамом и ф+етой'
    - 'Чуть больше, чем в смете'

meditation_onboarding:
    app_id: 'ru.yandex.quasar.*|aliced.*'
    regexps:
    - '(?:алиса )?(?:а )?(?:какая |какие )?(?:у тебя )?(?:есть|имеется|имеются|в наличии) (?:какая |какие )?(?:в наличии )?медитаци[яи]'
    responses:
    - 'Если мысли мешают заснуть, попросите меня включить медитацию для сна или расслабления. А еще есть одна на каждый день, просто скажите: включи медитацию.'
    - 'Я умею включать медитации для сна, расслабления или на каждый день, которые помогут вам настроиться на нужную волну. Просто попросите меня включить одну из них.'
    - 'В это тревожное время я завела специальные медитации для сна, расслабления и на каждый день. Просто попросите меня включить одну из них.'
