RECURSE(
    catboost_applier
    custom_entities
    query_wizard_features_reader
    request_normalizer
    respect_rewriter
    syntax_parser
    tf_model_applier
    tagger
    tokenizer
    utils
    vins_models_tf
)
