{
  "secretsConfigPath": "/opt/dialogovo/secrets.json",
  "storeUrl": "https://dialogs.yandex.ru/store",
  "dialogovoUrl": "https://dialogovo-testing.n.yandex-team.ru",
  "webhookClientConfig": {
    "maxResponseSize": 131072,
    "connectTimeout": 1000,
    "readTimeout": 3000,
    "fullRequestTimeout": 3200
  },
  "yaFunctions": {
    "url": "https://functions.yandexcloud.net"
  },
  "avatarsUrl": "https://avatars.mds.yandex.net",
  "redirectApi": {
    "clientId": "alice",
    "key": "523c56ec30554314e2849aa59df5f221",
    "url": "https://sba.yandex.net/redirect"
  },
  "nerApi": {
    "url": "http://paskills-common-testing.alice.yandex.net/priemka/nlu/api/ner/v1",
    "timeout": 1000,
    "connectTimeout": 200,
    "cacheTtlSeconds": 86400,
    "cacheSize": 25000
  },
  "abuseConfig": {
    "url": "http://tmu-rt-for-alice.clean-web.yandex.net",
    "timeout": 300,
    "connectTimeout": 200,
    "enabled": true,
    "cacheSize": 75000
  },
  "accountLinking": {
    "url": "https://priemka.dialogs.alice.yandex.ru/store/account_linking"
  },
  "billingConfig": {
    "url": "https://paskills-common-testing.alice.yandex.net/billing-rc",
    "timeout": 10000,
    "connectTimeout": 1000
  },
  "socialApi": {
    "url": "https://api.social-test.yandex.ru",
    "timeout": 1000,
    "connectTimeout": 100
  },
  "xivaConfig": {
    "url": "https://push.yandex.ru/",
    "timeout": 5000,
    "connectTimeout": 200
  },
  "wizard": {
    "url": "http://paskills-common-testing.alice.yandex.net/begemot-hamster/wizard",
    "timeout": 600,
    "connectTimeout": 100,
    "cacheTtlSeconds": 86400,
    "cacheSize": 2000
  },
  "appMetrica": {
    "url": "https://report.appmetrica.yandex.net",
    "timeout": 2000,
    "connectTimeout": 200
  },
  "apiConfig": {
    "url": "https://paskills-common-testing.alice.yandex.net/priemka/api/catalogue/v1/personal",
    "timeout": 2000,
    "connectTimeout": 200
  },
  "ydb": {
    "warmUpOnStart": true,
    "sessionPoolSizeMin": 20,
    "sessionPoolSizeMax": 200,
    "queryCacheSize": 218,
    "maxRetries": 5
  },
  "show": {
    "experiments": [ ],
    "yt": {
      "cluster": "hahn",
      "directory": "//home/paskills/skills-to-morning-show/test"
    },
    "skillRequestTimeout": 10000,
    "ytSaveTimeout": 100000,
    "ytTtlInHours": 168
  },
  "penguinaryConfig": {
    "url": "http://paskills-common-testing.alice.yandex.net/penguinary/",
    "timeout": 100,
    "connectTimeout": 50
  },
  "fillCachesOnStartUp": true,
  "dssmThreshold": 0.5,
  "internalFairytaleSkillId": "bd168a52-c2eb-43be-a3df-632e207cd02b",
  "webServerConfig": {
    "minThreads": 10,
    "maxThreads": 400,
    "queueSize": 400
  },
  "gamesOnboardingConfig": {
    "storeOnboardingGamesUrl": "https://priemka.dialogs.alice.yandex.ru/store/essentials#games?utm_source=Yandex_Alisa&utm_medium=onboarding"
  },
  "recommenderConfig": {
    "url": "http://skills-rec.alice.yandex.net/recommender",
    "timeout": 200,
    "connectTimeout": 50
  },
  "proactiveExitSuggestConfig": {
    "suggestExitAfterNDoNotUnderstandReplies": 2
  },
  "yandexQFactSkillId": "dd1d5a65-5c78-4cf5-a0df-873923097997",
  "enableLogSkillRequests": true,
  "mementoConfig": {
    "url": "http://paskills-common-testing.alice.yandex.net/memento",
    "timeout": 130,
    "connectTimeout": 50
  },
  "imageGalleryBaseUrl": "https://priemka.dialogs.alice.yandex.ru/gallery",
  "recipes": {
    "askForFeedback": true,
    "slowIngredientListPauseMs": 3500,
    "minTimerLengthForMusicSuggest": 600,
    "suggestMusicAfterFirstStep": false
  },
  "yandexAuthUri": "yandex-auth://?theme=light",
  "music_backend": {
    "base_url": "http://music-web-ext.music.qa.yandex.net/external-api",
    "client": {
      "connection_timeout": {
        "ms": 100
      },
      "read_timeout": {
        "ms": 1000
      },
      "max_connections": 100,
      "retry": {
        "count": 2
      }
    }
  },
  "warmup": {
    "requests": 0
  },
  "dialogovo.widgets": {
    "skillRequestTimeout": 3200,
    "skillsIds": [
      "47718ad7-ee3e-4e05-94ec-dbbd8e5c5cf7", # Олег Дулин
      "d9194f6f-7cfe-4b0f-8fb2-d96aa631a25d", # Нейрогороскоп
      "e2f823c7-48ad-4fee-945b-b6fe0d1a24da", # Стих дня,
      "84448a03-02ee-45e1-b15c-6b9286414f1c", # Комплимент дня
      "8a9e9660-7917-482b-91d9-1bd31e0ba469", # Мудрость дня
    ]
  },
  "dialogovo.teasers": {
    "skillRequestTimeout": 3200,
    "maxNumberOfTeasers": 5,
    "skillsIds": [
      "47718ad7-ee3e-4e05-94ec-dbbd8e5c5cf7", # Олег Дулин
      "d9194f6f-7cfe-4b0f-8fb2-d96aa631a25d", # Нейрогороскоп
      "84448a03-02ee-45e1-b15c-6b9286414f1c", # Комплимент дня
      "8a9e9660-7917-482b-91d9-1bd31e0ba469", # Мудрость дня
      "e2f823c7-48ad-4fee-945b-b6fe0d1a24da", # Стих дня
    ]
  }
}
