# Old AutoApp has number of hardcoded phrases in client which were sent as user utterance
#  upon some events (e.g. when connected to the Internet). Except greeting (привет), they should be silenced.
internet_appeared:
  nlu:
    - появился Интернет

  nlg:
    - ''

tired:
  nlu:
    - долго за рулем

  nlg:
    - ''

missed:
  nlu:
    - долго не было

  nlg:
    - ''

confirmation_yes:
  nlu:
    - ага
    - вижу
    - вперед
    - все правильно
    - да
    - давай
    - есть
    - нет ошибки
    - ок
    - окей
    - погнали
    - подтвердить
    - подтверждаю
    - поехали
    - правильно
    - согласен
    - сохрани
    - сохранить
    - угу
    - установить
  nlg:
    - ''

confirmation_no:
  nlu:
    - а нет стой
    - а ну стой
    - ааа нет
    - ааа стой
    - блин да нет
    - блин не то
    - блин не это хотела сказать
    - блин сам запутался стой
    - бред стой
    - все не то
    - все перепутал
    - да не
    - давай заново
    - зачем стой не надо
    - какая то хрень отменяй
    - не то
    - ненене
    - неправильно
    - нет
    - нет не так
    - нет не то отмена
    - нет нет
    - нет погоди
    - нет стоп
    - но но но
    - ну ка отмени
    - ну ка стой
    - ой
    - ой не не не туда я ошиблась
    - ой ненене
    - ой нет вернись
    - ой нет удаляй
    - ой ой ой
    - ой подожди
    - ой стоп
    - ой это я загнул
    - отмена
    - отмени
    - отменить
    - отменяй к черту
    - очисть все
    - ошибочка
    - передумал погоди
    - погодь отменяй
    - стой блин
    - стой еще раз давай
    - стой не гони
    - стой отменяй все
    - стой ошибка
    - стоп стоп стоп
    - так не слушай меня
    - так нет
    - так нет не надо
    - так нет стоп
    - не то
    - тьфу ты не так
    - нафиг это все херня
    - фигня какая то
    - не туда стоп
    - фу убери это
    - черт я ошибся
    - что я говорю совсем запутался не то
    - э нет стоп
    - это не то
    - эээ ты че нет
    - я не то имел в виду
    - я передумал стоп
    - блядь хватит болтать
  nlg:
    - ''
