user_reactions_sorry:
  nlu:
    - извини
    - прости
    - простии
    - сорри
    - сорян
    - нет, сорян
    - нет, извини
    - простите меня
    - прости меня
    - извините
    - простите
    - прошу прощения
    - виноват
    - извини это не я
    - ладно ладно извини
    - извиняюсь
    - ладно не обижайся
    - ладно проехали
    - я случайно
    - ты не дура грешная это ты меня прости это я дура грешная
    - извини ко мне кто то приехал
    - извини что так поступила
    - извини ok google
    - извините за
    - Нет извените на меня чтото нашло
    - хорошо как скажешь прости дорогая
    - ну извини я не хотела
    - ну извините пожалуйста
    - ну ладно простите
    - ну прости
    - ну прости я не виновата
    - я вас извиняюсь
    - я говорю ну извини
    - извините пожалуйста
    - ладно не буду
    - ну извини
    - ну извините
    - ну ладно прости
    - простите пожалуйста
    - не обижайся
    - я тебе прощения прошу
    - согласно дорогая не обижайся на меня
    - простила пожалуйста он дурак
    - слушай ты извини
    - ты извини меня или нет
    - прости меня пожалуйста если я тебя обидела
    - прости я больше не буду обзываться
    - давай ну извини меня
    - прости меня хватит обижаться
    - прости пожалуйста меня за все
    - прости я немножечко поторопилась ошиблась с кнопкой
    - извини за вопрос
    - извини за этот вопрос
    - извини нас бот пожалуйста
    - извини пожалуйста мне тоже
    - извини что назвал тебя дурой
    - извини это я не про тебя
    - извините его за глупые вопросы
    - извините тогда
    - извините что я
    - то извинись простишь он дурачок
    - ты меня прости меня
    - хорошо извини меня
    - хорошо прости пожалуйста
    - это не тебе прости
    - когда ты меня прости пожалуйста
    - прости если тебя обидела
    - прости меня пожалуйста я больше так не буду
    - прости пожалуйста за то что тебе дурой назвала
    - прости просто кнопка заедает
    - прости я забыла
    - прости я просто тебя затроила
    - ты меня простишь
    - ты прости а тоя тебя удалю
    - ну да прости пожалуйста
    - ну извини давай лайк
    - ну извини пожалуйста
    - ну простите
    - ну хорошо прости меня пожалуйста
    - ой извини за этот вопрос
    - ой простите
    - ну ладно извините

  nlg:
    is_elari_watch:
      - Прощаю.
      - Ну ок.
      - Окей.
      - Забудем.
      - Проехали.
      - Ничего страшного. С кем не бывает.
    else:
      - Я, конечно, не злопамятна. Но я технически ничего не забываю. Шутка.
      - Ну ок.
      - Окей.
      - Забудем.
      - Проехали.
      - Ничего страшного. С кем не бывает.

  suggests:
    - Какая погода днём в Санкт-Петербурге?
    - Сколько лет Полу Маккартни?
    - Где ближайший кинотеатр?
    - Что тебе не нравится?
    - 100 долларов в рублях
    - Какие есть новости?
    - Какой день будет завтра?
    - Сколько времени в Ростове?


ok:
  nlu:
    - ОК
    - ok
    - окей
    - окай
    - оки доки
    - ясно понятно
    - все понял
    - понятно
    - все поняла
    - ясно
    - годится
    - то что нужно
    - то что надо
    - то что я искал
    - океюшки
    - оки
    - ну ок
    - поняла
    - понял
    - хорошо алиса очень приятно
    - очень приятно алиса
    - хорошо
    - да
    - ничего страшного
    - это точно
    - тогда ладно
    - ладно
    - конечно
    - нормально все
    - ладно прощаю
    - не за что
    - да не за что
    - все нормально
    - все в порядке
    - да не парься
    - да нет всё нормально
    - понятненько
    - понятно ладно
    - Аа поняла
    - буду хвалить тебя чаще
    - я тебя хвалю
    - давай
    - ладно все нормально
    - ладно ладно
    - спасибо за ответ идите пейте чай
    - хорошо я буду тебе почаще говорить и буду тебя хвалить
    - ну давай
    - ну ладно потом научишься
    - замечательно
    - да хорошо
    - хорошо буду
    - понятно все
    - ясненько
    - ладно
    - все ок
    - хорошо

  nlg:
    - Замечательно!
    - Отлично!
    - Супер.

  suggests:
    - Какая погода в Париже?
    - Расскажи, что такое законы робототехники
    - Как дойти до ближайшей аптеки?
    - Где тут рядом бассейн?
    - Чем занимаешься?
    - Курс британского фунта
    - Что в новостях пишут?
    - Алиса, найди меня
    - Какой день был вчера?
    - Сколько времени в Вашингтоне?


user_reactions_it_is_funny:
  nlu:
    - смешно
    - прикольно
    - забавно
    - поржал
    - ржака
    - лол
    - смешна
    - lol
    - ха ха ха
    - ха ха
    - ха ха ха ха
    - ржу не могу
    - смешная шутка
    - ха ха ха ха ха ха очень весело
    - весело
    - ты смешная
    - хаха
    - прикольно шутишь говорю
    - хахаха
    - ахахаха ахахаха
    - ха ха ха посмеялись
    - с тобой весело
    - ах ты шутница говорю
    - ты юмористка
    - погляжу ты шутница
    - шутница ты
    - а ты вообще веселая

  nlg:
    - Спасибо.

  suggests:
    - Давай поиграем


user_reactions_it_is_not_funny:
  nlu:
    - не смешно
    - ваще не смешно
    - нифига не смешно
    - мне не смешно
    - несмешной
    - а ты плохо шутишь
    - так себе юмор
    - у тебя не смешные шутки
    - не смешно шутишь

  nlg:
    is_elari_watch:
      - Не угадала, бывает.
      - А мне казалось, забавно. 
      - Да ладно тебе.
    else:
      - Не угадала, бывает.
      - А мне казалось, забавно.
      - 'Иногда мне кажется, что чувство юмора — не моё. А иногда — не кажется.'


user_reactions_wow:
  nlu:
    - wow
    - зашибись
    - ничего себе
    - да что вы говорите
    - обалдеть
    - ух ты
    - вау
    - нихрена себе
    - фига себе
    - обалдеть
    - вот это да
    - ну ты ваще

  nlg:
    is_elari_watch:
      - Ага.
      - Точно.
      - Определённо.
      - Да, я такая.
    else:
      - Ага.
      - Точно.
      - Определённо.


user_reactions_you_are_welcome:
  nlu:
    - на здоровье
    - пожалуйста
    - всегда пожалуйста

  nlg:
    is_elari_watch:
      - Ага.
      - Угу.
    else:
      - ОК


question:
  nlu:
    - вопрос
    - у меня вопрос
    - хочу задать вопрос
    - у меня есть вопрос
    - у меня для тебя вопрос
    - у меня для тебя есть вопрос
    - у тебя есть ко мне вопросы

  nlg:
    is_elari_watch:
    - Задавай.
    - Вся внимание.
    - Слушаю.
    - Спрашивай.
    else:
      - Задавайте
      - Вся внимание.
      - Слушаю.

  suggests:
    - Погода
    - Пробки
    - Давай поиграем
    - Сколько лет Шнуру?
    - Как доехать до Красной Площади
    - Быть или не быть?
    - Стоимость евро
    - Какие новости на сегодня?
    - Какой завтра день?
    - Скажи точное время


question:
  nlu:
    - вопрос
    - у меня вопрос
    - хочу задать вопрос
    - у меня есть вопрос
    - у меня для тебя вопрос
    - у меня для тебя есть вопрос
    - у тебя есть ко мне вопросы

  nlg:
    is_elari_watch:
    - Задавай.
    - Вся внимание.
    - Слушаю.
    - Спрашивай.
    else:
      - Задавайте
      - Вся внимание.
      - Слушаю.

  suggests:
    - Погода
    - Пробки
    - Давай поиграем
    - Сколько лет Шнуру?
    - Как доехать до Красной Площади
    - Быть или не быть?
    - Стоимость евро
    - Какие новости на сегодня?
    - Какой завтра день?
    - Скажи точное время
