---
include:
  - extensions/crmbot_resources.yaml
  - extensions/http_status_hook.yaml
  - extensions/health_check.yaml
  - extensions/stop_action.yaml
component:
  deployPolicy: InPlace
  environmentVariables:
    RUN_COMMAND: "/home/vins/crmbot"
    VINS_ENABLE_BACKGROUND_UPDATES: "0"
    VINS_GC_TEMPERATURE: "0.95"
    VINS_GC_MAX_SUGGESTS: "5"
    VINS_GC_FORCE_QUESTION_TOP_K: "4"
    VINS_PRELOAD_APP: "beru_crm"
    VINS_SPEECHKIT_LISTEN_BY_DEFAULT: "1"
    VINS_WORKERS_COUNT: "8"
    VINS_SKILLS_ENV_TYPE: production
  diskSize: 100
  size: 32;8.0;256
  activateRecipe:
    updateWindow: 2
    updateLimit: 2
    updatePeriod: 1
    doneThreshold: "100%"
routes:
  -
    geo: "true"
    location: /webim/beru_crm/
    proxyConnectTimeout: 200ms
    proxyNextUpstream: "error timeout http_502 http_503"
    proxyPolicy: round_robin
    proxyReadTimeout: 3000ms
    proxyWriteTimeout: 1000ms
    upstreamPath: ""
    yandexErrorPage: "OFF"
    componentName: webim-beru-crm
    proxyNextUpstreamTries: 3

