action: scenario
steps:
    - action: proxycli.app.init_args
    - action: proxycli.app.init_logging_v2
    - action: proxycli.scenarios.load
    - action: proxycli.app.run
    - action: proxycli.report.aggregate
