files:
- name: /logs/current-profile_log-app_host-3000
  send_delay: 5
  topic: /alice-production/apphost
  format: eventlog
  compression-out: 0
- name: /logs/current-uniproxy-eventlog
  send_delay: 5
  topic: /alicelogs/prod/uniproxy
  format: eventlog
  compression-out: 0
- name: /logs/uniproxy.out
  send_delay: 5
  topic: /alice-production/uniproxy
  pipe: ./qloud_format
  compression-out: zstd
logger:
  file: /logs/push-client.log
  level: 5
  remote: 0
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
  proto: pq
  tvm-server-id: 2001059
  tvm-client-id: 2000496
watcher:
  state: /logs/push-client-state
