---
component:
  nanny:
    keychainId: "test-bot"
    environmentVariables:
      VINS_QLOUD_COMPONENT: "vins-bot"
      VINS_QLOUD_ENVIRONMENT: "develop"
    services:
      -
        name: "vins_bot_man"
        category: "/alice/production/vins-bot/"
        gencfg: []
      -
        name: "vins_bot_sas"
        category: "/alice/production/vins-bot/"
        gencfg: []
      -
        name: "vins_bot_vla"
        category: "/alice/production/vins-bot/"
        gencfg: []
  sandboxResources:
    # vmtouch binary
    -
      dynamic: "false"
      extract: "false"
      id: "755473355"
      task_id: "339294097"
      task_type: "HTTP_UPLOAD_2"
      resource_type: "OTHER_RESOURCE"
      localName: "vmtouch"
      symlink: "/tmp/vins/vmtouch"
  environmentVariables:
    RUN_COMMAND: "/home/vins/test_bot"
    YENV_TYPE: development
    VINS_RENDER_URL: "http://div2html.s3.yandex.net/div2.html"
    VINS_S3_RENDER_PREFIX: "src"
    VINS_S3_RENDER_BUCKET: "div2html"
    VINS_ROTOR_SERVER: "http://rotor-online.search.yandex.net:23555/"
    VINS_ROTOR_SOURCE: "vins_div2html_online"
    VINS_S3_ENDPOINT_URL: "http://s3.mds.yandex.net/"
    MONGO_HOST: man-qr3anqznmtc7qzs1.db.yandex.net:27018,sas-jxvpdl8idjuaort6.db.yandex.net:27018,vla-3y88hex1g2ysbywy.db.yandex.net:27018
    MONGO_DB: vins_bot
    VINS_MONGODB_NAME: vins_bot
    MONGO_USER: vins_bot_user
  image:
    repo: registry.yandex.net/vins/vins-all
    tag: ~
  secrets:
    -
      objectId: secret.vins-oauth-client-id
      target: VINS_OAUTH_CLIENT_ID
      used: "true"
    -
      objectId: secret.vins-oauth-client-secret
      target: VINS_OAUTH_CLIENT_SECRET
      used: "true"
    -
      objectId: secret.vins-tvm-client-id
      target: VINS_TVM_CLIENT_ID
      used: "true"
    -
      objectId: secret.vins-tvm-client-secret
      target: VINS_TVM_CLIENT_SECRET
      used: "true"
    -
      objectId: secret.vins-s3-access-key-id
      target: VINS_S3_ACCESS_KEY_ID
      used: "true"
    -
      objectId: secret.vins-s3-secret-access-key
      target: VINS_S3_SECRET_ACCESS_KEY
      used: "true"
    -
      objectId: secret.vins-test-bot-mongodb-pwd
      target: MONGO_PASSWORD
      used: "true"
    -
      objectId: secret.vins-staff-oauth-token
      target: VINS_STAFF_TOKEN
      used: "true"
  size: t1_big
  tcpPort: 1
  network: "VINS_INT_TEST_NETS"
  instanceGroups:
    -
      location: "ALL"
      units: 1
      backup: false
