status:
  port: 16301

storages:
- name: metrics_storage
  plugin: fs
  config:
    directory: /var/cache/unified_agent
    max_partition_size: 100mb

channels:
- name: solomon_output
  channel:
    pipe:
    - storage_ref:
        name: metrics_storage
    output:
      plugin: metrics_pull
      config:
        port: 8900
