RECURSE(
    action_matching
    anaphora_resolver
    annotator
    ar_dual_num
    begemot_granet
    binary_classifier
    catboost_model_interface
    contacts
    embedder
    embedding_pack
    encoder
    entity_parsing
    entity_recognition
    entity_searcher
    features_vectorizer
    frame
    fst
    fst/tests
    interval
    iot
    item_selector
    lemmatization
    nn_classifier
    normalization
    occurrence_searcher
    openfst_entities
    query_wizard_features_reader_wrapper
    request_normalizer
    rnn_tagger
    sample_features
    slot_inheritance
    tf_model_converter
    tf_nn_model
    token_aligner
    token_interval_inflector
    tokenization
    tuple_like_type
    type_parser
    ut_utils
)
