service: speechkit_ops_alice_uniproxy
title: Wsproxy config packs
ci:
  release-title-source: flow
  secret: sec-01eyzmpjy2qcp91f0vkhrqfsx7
  runtime:
    sandbox:
      owner: VOICESERV_RELEASERS
      tags:
        - ARCADIA-CI-TASK

  releases:
    pack-main-apphost:
      title: Pack main apphost configs
      flow: config-pack-flow
      flow-vars:
        title: main apphost configs
        package: alice/uniproxy/configs/split/main/apphost/package.json
        resource-type: VOICETECH_APPHOST_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/main/apphost/**'
      stages:
        build:
          title: Packing

    pack-main-cuttlefish:
      title: Pack main cuttlefish configs
      flow: config-pack-flow
      flow-vars:
        title: main cuttlefish configs
        package: alice/uniproxy/configs/split/main/cuttlefish/package.json
        resource-type: VOICETECH_CUTTLEFISH_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/main/cuttlefish/**'
      stages:
        build:
          title: Packing

    pack-main-wsproxy:
      title: Pack main wsproxy configs
      flow: config-pack-flow
      flow-vars:
        title: main wsproxy configs
        package: alice/uniproxy/configs/split/main/wsproxy/package.json
        resource-type: VOICETECH_UNIPROXY_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/main/wsproxy/**'
      stages:
        build:
          title: Packing


    pack-beta-apphost:
      title: Pack beta apphost configs
      flow: config-pack-flow
      flow-vars:
        title: beta apphost configs
        package: alice/uniproxy/configs/split/beta/apphost/package.json
        resource-type: VOICETECH_APPHOST_BETA_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/beta/apphost/**'
      stages:
        build:
          title: Packing

    pack-beta-cuttlefish:
      title: Pack beta cuttlefish configs
      flow: config-pack-flow
      flow-vars:
        title: beta cuttlefish configs
        package: alice/uniproxy/configs/split/beta/cuttlefish/package.json
        resource-type: VOICETECH_CUTTLEFISH_BETA_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/beta/cuttlefish/**'
      stages:
        build:
          title: Packing

    pack-beta-wsproxy:
      title: Pack beta wsproxy configs
      flow: config-pack-flow
      flow-vars:
        title: beta wsproxy configs
        package: alice/uniproxy/configs/split/beta/wsproxy/package.json
        resource-type: VOICETECH_UNIPROXY_BETA_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/beta/wsproxy/**'
      stages:
        build:
          title: Packing

    pack-fetch-apphost:
      title: Pack fetch apphost configs
      flow: config-pack-flow
      flow-vars:
        title: fetch apphost configs
        package: alice/uniproxy/configs/split/fetch/apphost/package.json
        resource-type: VOICETECH_APPHOST_FETCH_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/fetch/apphost/**'
      stages:
        build:
          title: Packing

    pack-fetch-cuttlefish:
      title: Pack fetch cuttlefish configs
      flow: config-pack-flow
      flow-vars:
        title: fetch cuttlefish configs
        package: alice/uniproxy/configs/split/fetch/cuttlefish/package.json
        resource-type: VOICETECH_CUTTLEFISH_FETCH_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/fetch/cuttlefish/**'
      stages:
        build:
          title: Packing

    pack-fetch-wsproxy:
      title: Pack fetch wsproxy configs
      flow: config-pack-flow
      flow-vars:
        title: fetch wsproxy configs
        package: alice/uniproxy/configs/split/fetch/wsproxy/package.json
        resource-type: VOICETECH_UNIPROXY_FETCH_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/fetch/wsproxy/**'
      stages:
        build:
          title: Packing

    pack-legacy-apphost:
      title: Pack legacy apphost configs
      flow: config-pack-flow
      flow-vars:
        title: legacy apphost configs
        package: alice/uniproxy/configs/split/legacy/apphost/package.json
        resource-type: VOICETECH_APPHOST_LEGACY_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/legacy/apphost/**'
      stages:
        build:
          title: Packing

    pack-legacy-cuttlefish:
      title: Pack legacy cuttlefish configs
      flow: config-pack-flow
      flow-vars:
        title: legacy cuttlefish configs
        package: alice/uniproxy/configs/split/legacy/cuttlefish/package.json
        resource-type: VOICETECH_CUTTLEFISH_LEGACY_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/legacy/cuttlefish/**'
      stages:
        build:
          title: Packing

    pack-legacy-wsproxy:
      title: Pack legacy wsproxy configs
      flow: config-pack-flow
      flow-vars:
        title: legacy wsproxy configs
        package: alice/uniproxy/configs/split/legacy/wsproxy/package.json
        resource-type: VOICETECH_UNIPROXY_LEGACY_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/legacy/wsproxy/**'
      stages:
        build:
          title: Packing

    pack-quasar-apphost:
      title: Pack quasar apphost configs
      flow: config-pack-flow
      flow-vars:
        title: quasar apphost configs
        package: alice/uniproxy/configs/split/quasar/apphost/package.json
        resource-type: VOICETECH_APPHOST_QUASAR_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/quasar/apphost/**'
      stages:
        build:
          title: Packing

    pack-quasar-cuttlefish:
      title: Pack quasar cuttlefish configs
      flow: config-pack-flow
      flow-vars:
        title: quasar cuttlefish configs
        package: alice/uniproxy/configs/split/quasar/cuttlefish/package.json
        resource-type: VOICETECH_CUTTLEFISH_QUASAR_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/quasar/cuttlefish/**'
      stages:
        build:
          title: Packing

    pack-quasar-wsproxy:
      title: Pack quasar wsproxy configs
      flow: config-pack-flow
      flow-vars:
        title: quasar wsproxy configs
        package: alice/uniproxy/configs/split/quasar/wsproxy/package.json
        resource-type: VOICETECH_UNIPROXY_QUASAR_CONFIGS
      auto: true
      filters:
        - sub-paths:
          - 'split/quasar/wsproxy/**'
      stages:
        build:
          title: Packing

  flows:
    config-pack-flow:
      title: Pack config files
      jobs:
        start-packing:
          title: Start packing
          task: dummy
          stage: build

        pack-config:
          title: Packing ${flow-vars.title}
          task: common/arcadia/ya_package_2
          needs: start-packing
          attempts: 3
          input:
            build_type: stable
            run_tests: False
            packages: ${flow-vars.package}
            resource_type: ${flow-vars.resource-type}
            raw_package: True
            compress_package_archive: False

        release-configs:
          title: Release all items
          task: common/releases/simple_releaser
          needs: pack-config
          input:
            config:
              deploy_system: NANNY
              release_token_yav_key: sandbox.token
              wait_for_deploy: False
              common_release_data:
                nanny_common_release_data:
                  release_stage: stable
                  release_notes: Release ${flow-vars.title} with CI
                  release_subject: ${flow-vars.title} CI release ${context.version_info.major}
            context:
              secret_uid: sec-01eyzmpjy2qcp91f0vkhrqfsx7
            release_items:
              - sandbox_release_item:
                  id: ${(tasks.pack-config.resources[?type == root().flow-vars.resource-type])[0].id}
                  type: ${flow-vars.resource-type}
