export const defaultGrammar = [
    "import: common/filler.grnt",
    "form alice.random_number:",
    "    slots:",
    "        lower_bound:",
    "            type: sys.num",
    "            source: $LowerBound",
    "        upper_bound:",
    "            type: sys.num",
    "            source: $UpperBound",
    "    root:",
    "        $Root",
    "$Root:",
    "    [$GiveMeNumber? $FullRange]",
    "    [$GiveMeNumber $PartialRange]",
    "    [$Again $Number]",
    "    [$Give $Me? $Again? $Number]",
    "$FullRange:",
    "    от $LowerBound до $UpperBound",
    "    между $LowerBound и $UpperBound",
    "$PartialRange:",
    "    до $UpperBound",
    "    больше $LowerBound",
    "    меньше $UpperBound",
    "$LowerBound:",
    "    $sys.num",
    "$UpperBound:",
    "    $sys.num",
    "$GiveMeNumber:",
    "    [$Give? $Me? $Again? $Number]",
    "$Give:",
    "    мне нужно",
    "    можешь? $Give<g:|инф>",
    "    $Give:",
    "        выбери | выдай | дай | давай | назови | скажи | загадай",
    "$Me:",
    "    мне | нам",
    "$Again:",
    "    eще одно?",
    "    eще один? (раз|разок)?",
    "$Number:",
    "    одно? $Any<g:|жен|жен,вин>? (число|цифру|цифра)",
    "$Any:",
    "    какое-нибудь | случайное | любое | произвольное | рандомное",
    "filler:",
    "    $nonsense",
    "    $Common.Filler",
    "    сейчас | короче | быстро | теперь"
].join('\n');