host: "::"
port: "80"
storage_directory: "//home/alice/logviewer"
table_granularity: "1d"
clique: "*logviewer"
cluster: "hahn"
view: "search.html"
search_solomon_buckets: [ 100, 200, 300, 400, 500, 600, 700, 800, 900,
                          1000, 1200, 1400, 1600, 1800,
                          2000, 2500, 3000, 3500, 4000, 4500,
                          5000, 6000, 7000, 8000, 9000,
                          10000, 12000, 14000, 16000, 18000,
                          20000, 25000, 30000, 35000, 40000, 45000,
                          50000, 600000 ]
skill_solomon_buckets: [ 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000 ]
logging_config:
  version: 1
  disable_existing_loggers: no
  formatters:
    deploy:
      class: "library.python.deploy_formatter.DeployFormatter"
  handlers:
    deploy:
      class: "logging.StreamHandler"
      level: "ERROR"
      formatter: "deploy"
  loggers:
    logviewer.server:
      handlers: [ "deploy" ]
      level: "ERROR"
      propagate: yes
