files:
  - name: /logs/current-megamind-analytics-log
    ident: megamind
    log_type: analytics-log
    compression-out: zstd
  - name: /logs/current-megamind-proactivity-log
    ident: megamind
    log_type: proactivity-log
logger:
  file: /logs/push-client.log
  level: 5
  mode:
    - file
network:
  master_addr: logbroker.yandex.net
  tvm-client-id: 2000464
  tvm-server-id: 2001059
  proto: pq
watcher:
  state: /logs/push-client-state
