ydb:
    endpoint: ydb-ru-prestable.yandex.net:2135
    database: /ru-prestable/alice/development/paskills_penguinary
    timeout: 30
    max_retries: 5
    root_folder: peng
    connect_params:
        use_tvm: True
        self_tvm_id: 2018023
        tvm_secret_env: TVM_SECRET

nodes_storage:
    cache_size: 256
    ttl: 600
    warm_up:
        nodes_idx: [ skill_activation ]
        sleep_time: 10

logging:
    kikimr_level: WARN
    common_level: DEBUG

dssm:
    path: ../models/qe_model
    input_name: query
    output_name: query_embedding
    empty_inputs: [ expansion ]
    cache_size: 10

model:
    thresh: 0.5
    dist_thresh_rel: lt
    metric: minkowski
    n_neighbors: 3
    p: 2

server:
    host: '[::]'
    port: '12345'
    workers: 1
    timeout: 60

redis:
    turned_on: True
    address: 'redis://localhost'
    maxsize: 100000
