listen_addr: :8080

logging:
    level: warn

yt:
  cluster: arnold
  # input: //home/iot/mavlyutov/pinger # https://yql.yandex-team.ru/Operations/XymfnyAsJQ2cVQKH3FVXIqp1sWtEGwJOVShjkhJL4zE=
  # input: //home/iot/mavlyutov/pinger_agusakov # https://yql.yandex-team.ru/Operations/Xyw8niAsJQ2cVw4106mTBZNzrxBKZgMu1OyXFkBZOWY=
  input: //home/iot/mavlyutov/pinger_light_sample # https://yql.yandex-team.ru/Operations/XzpUyxpqv72eHo7DC8QEEG0lfIVVczS4z3gr6cup460=

database:
    endpoint: ydb-ru.yandex.net:2135
    prefix: /ru/quasar/production/iotdb
    token: # envvar

tvm:
    port: 18080
    src_alias: bulbasaur
    token: token_for_local_interaction_1234

dialogs:
    tvm_alias: dialogs
    url: https://dialogs.alice.yandex.net/api

socialism:
    url: https://api.social.yandex.ru/api
    # url: http://localhost:5001/api # ssh-tunnel ftw

tuya:
    adapter_url: http://tuya.iot.quasar.yandex.net
    tvm_alias: tuya

sber:
  adapter_url: http://tuya.iot.quasar.yandex.net/sber
  tvm_alias: tuya # same tvm alias as in tuya

xiaomi:
    adapter_url: https://xiaomi.iot.yandex.net
