# This should be INCLUDEd to ya.make of every it2 tests target

DEPENDS(
    alice/hollywood/shards/all/prod/common_resources
    alice/hollywood/shards/all/prod/hw_services_resources
    alice/hollywood/shards/all/prod/fast_data
    alice/hollywood/shards/all/prod/resources
    alice/hollywood/shards/all/server
)

DATA(
    arcadia/alice/hollywood/shards/all/dev
    arcadia/alice/hollywood/shards/all/test
)
