listen_addr: :8080

ydb:
  prefix: /ru-prestable/quasar/beta/iotdb
  endpoint: ydb-ru-prestable.yandex.net:2135

history_controller:
  ydb:
    prefix: /ru-prestable/quasar/beta/iothistorydb
    endpoint: ydb-ru-prestable.yandex.net:2135
  solomon:
    cluster: beta
adapters:
  tuya:
    endpoint: http://tuya-beta.iot.quasar.yandex.net
  sber:
    endpoint: http://tuya-beta.iot.quasar.yandex.net/sber
  philips:
    endpoint: http://philips-beta.iot.quasar.yandex.net
  xiaomi:
    endpoint: https://xiaomi.iot-beta.quasar.yandex.net

begemot:
  url: http://hamzard.yandex.net:8891

takeout:
  tvm_id: 2009783

steelix:
  tvm_id: 2016207

timemachine:
  url: http://timemachine-beta.iot.yandex.net
  tvm_id: 2032560

megamind:
  bulbasaur:
    url: http://iot-beta.quasar.yandex.net
    tvm_client_id: 2009295
  vulpix:
    ydb:
      prefix: /ru-prestable/quasar/beta/vulpixdb
      endpoint: ydb-ru-prestable.yandex.net:2135
    steelix:
      url: https://dialogs.priemka.voicetech.yandex.net/api
      tvm_id: 2016207
    tuya:
      url: http://tuya-beta.iot.quasar.yandex.net/vulpix
      tvm_id: 2010596

sup:
  bulbasaur_srcrwr_url: iot-beta.quasar.yandex.ru

user_service:
  reqid_cache:
    max_size: 20
