listen_addr: :8080
apphost_listen_addr: :8888

tvm:
  port: 18080
  src_alias: bulbasaur

blackbox:
  tvm_id: 222
  url: http://blackbox.yandex.net

dialogs:
  tvm_alias: dialogs
  url: https://dialogs.alice.yandex.net

ydb:
  prefix: /ru/quasar/production/iotdb
  endpoint: ydb-ru.yandex.net:2135
  min_session_count: 300
  max_session_count: 600
  auth_type: tvm

repository:
  ignore_cache: true

socialism:
  url: https://api.social.yandex.ru/api

bass:
  url: http://bass-prod.yandex.net

begemot:
  url: http://reqwizard.yandex.net:8891

adapters:
  quasar:
    endpoint: https://quasar.yandex.ru/iot
    tvm_alias: quasar-backend
  tuya:
    endpoint: http://tuya.iot.quasar.yandex.net
    tvm_alias: tuya
  sber:
    endpoint: http://tuya.iot.quasar.yandex.net/sber
    tvm_alias: tuya # sber lives inside tuya infra and uses tuya tvm alias
  philips:
    endpoint: http://philips.iot.quasar.yandex.net
  xiaomi:
    endpoint: https://xiaomi.iot.yandex.net
  cloud_functions:
    tvm_alias: cloud

xiva:
  url: https://push.yandex.ru
  max_idle_connections: 50

sup:
  url: http://sup.yandex.net

timemachine:
  url: http://timemachine.iot.yandex.net
  tvm_id: 2021514

megamind:
  bulbasaur:
    url: http://iot.quasar.yandex.net
    tvm_client_id: 2009295
  vulpix:
    ydb:
      prefix: /ru/quasar/production/vulpixdb
      endpoint: ydb-ru.yandex.net:2135
      auth_type: tvm
    steelix:
      url: https://dialogs.yandex.net/api
      tvm_id: 2016427
    tuya:
      url: http://tuya.iot.quasar.yandex.net/vulpix
      tvm_id: 2010596
    notificator:
      url: https://notificator.alice.yandex.net
      tvm_id: 2023285

takeout:
  tvm_id: 2009785

steelix:
  tvm_id: 2016427

action_controller:
  retry_policy:
    type: UNIFORM_PARALLEL
    latency_ms: 100
    retry_count: 20

history_controller:
  ydb:
    prefix: /ru/quasar/production/iothistorydb
    endpoint: ydb-ru.yandex.net:2135
    min_session_count: 300
    max_session_count: 600
    auth_type: tvm
  solomon:
    project: alice-iot-sensors
    service_prefix: float-property
    cluster: prod
    sender_type: unified-agent
    enable_load_endpoint: false
    batch:
      send_interval: 1s
      callback_timeout: 10s
      limit: 1000
      buffer: 10000
      shutdown_timeout: 5s
    unified_agent:
      base_url: http://localhost:23445

scenario_controller:
  jitter:
    enabled: true
    left_border: 0s
    right_border: 10s
setrace:
  filepath: /logs/setrace.out
  enabled: true

memento:
  url: http://memento.alice.yandex.net/memento
  tvm_id: 2021572

iot_app:
  client_ids:
    - d275e8816b50455bb89640981dd76e07
    - c0ebe342af7d48fbbbfcf2d2eedb8f9e
    - f8cab64f154b4c8e96f92dac8becfcaa

geosuggest:
  url: http://suggest-maps.yandex.net
  client_id: iot

datasync:
  url: https://intapi.disk.yandex.net:8443
  tvm_id: 132

notificator:
  url: https://notificator.alice.yandex.net
  tvm_id: 2023285

quasar:
  url: https://quasar.yandex.net
  tvm_id: 2002637

oauth:
  url: https://oauth-internal.yandex.ru
  tvm_id: 2000235
  consumer: alice-iot

stress_handlers:
  enable: false

user_service:
  reqid_cache:
    max_size: 5000
