listen_addr: :8080

ydb:
  prefix: /ru-prestable/quasar/test/iotdb
  endpoint: ydb-ru-prestable.yandex.net:2135

adapters:
  quasar:
    endpoint: https://testing.quasar.yandex.ru/iot
    tvm_alias: quasar-backend-test

begemot:
  url: http://hamzard.yandex.net:8891

steelix:
  tvm_id: 2016205

megamind:
  bulbasaur:
    url: http://iot-test.quasar.yandex.net
    tvm_client_id: 2009295
  vulpix:
    ydb:
      prefix: /ru-prestable/quasar/development/vulpixdb
      endpoint: ydb-ru-prestable.yandex.net:2135
    steelix:
      url: https://dialogs.priemka.voicetech.yandex.net/api
      tvm_id: 2016205
    tuya:
      url: http://tuya-beta.iot.quasar.yandex.net/vulpix
      tvm_id: 2010596

quasar:
  url: https://testing.quasar.yandex.ru
  tvm_id: 2002639

history_controller:
  ydb:
    prefix: /ru-prestable/quasar/development/iothistorydb
    endpoint: ydb-ru-prestable.yandex.net:2135
  solomon:
    cluster: beta

stress_handlers:
  enable: true
