yt:
  token: 'OVERRIDE THIS'
  proxy: hahn
  mr_account: alice-dev

yql:
  token: 'OVERRIDE THIS'

sandbox:
  owner: VINS
  token: 'OVERRIDE THIS'

soy:
  token: 'OVERRIDE THIS'

nirvana:
  quota: voice-core
  project: alice_vins
  label: acceptance

alice_common:
  dialog_logs_table: '//home/voice/vins/logs/dialogs/%(date)s'
  sessions_table: '//home/voice/dialog/sessions/%(date)s'
  ya_plus_robot_token: robot-alice-vins_oauth_token
  scraper_over_yt_pool: alice
  arcanum_robot_token: robot-voice-qa_arcanum_token


acceptance_order:
  -
    - ''

check_analytics_info:
  input_table: '//home/alice/toloka/accept/ue2e_quasar/basket'
  vins_url_state_preparer: 'http://vins.hamster.alice.yandex.net/speechkit/app/pa/'
  uniproxy_url: 'wss://beta.uniproxy.alice.yandex.net/alice-uniproxy-hamster/uni.ws'
  test_vins_url: 'http://megamind-rc.alice.yandex.net/speechkit/app/pa/'
  stable_vins_url: 'http://vins.hamster.alice.yandex.net/speechkit/app/pa/'
  experiments: ['analytics_info=1', 'tunneller_analytics_info=1']
  revision: 7183819
