env:
  service: "amelie"
  type: "dev"
internal_server:
  address: ":8081"
external_server:
  address: ":8080"
db:
  kind: "disk"
telegram:
  updater:
    kind: "long_polling"
    host: "vinsbot.alice.yandex.net"
    base_path: "/amelie/stable"
logger:
  setrace:
    enabled: false
rate_limiter:
  max_rps: 1
