env:
  service: "amelie"
  type: "stable"
internal_server:
  address: ":81"
external_server:
  address: ":80"
db:
  kind: "mongo_db"
  mongo_db:
    username: "amelie"
    hosts: "man-e4caxm1maxi7e3mt.db.yandex.net:27018,sas-7zivzjc4eio2epoa.db.yandex.net:27018,vla-tcxokuacofba4gpg.db.yandex.net:27018"
    db_name: "amelie"
    replica_set: "rs01"
telegram:
  updater:
    kind: "webhook"
    host: "vinsbot.alice.yandex.net"
    base_path: "/amelie/stable"
logger:
  setrace:
    enabled: true
    logs_path: "/logs/amelie.setrace.log"
    yt_logs_path: "/logs/amelie.yt.log"
rate_limiter:
  max_rps: 1
