OWNER(g:alice_analytics)

RECURSE(
    operations
    ue2e_baskets
    utils/marty/update_pulsar_instances
    utils/marty/run_nirvana_instance
    wer
    wer/werp
    wer/g2p
    utils
    operations/timespent
    operations/timespent/timespent
    operations/timespent/timespent_precompute
    operations/timespent/timespent_second_week
    operations/timespent/heartbeats
    operations/priemka
    tasks/VA-571
    operations/core_spu
    operations/core_spu/core_spu
    new_logviewer
    tv
    ww
)
