blackbox:
  tvm_id: 239
  url: http://blackbox-mimino.yandex.net

dialogs:
  url: https://paskills-common-testing.alice.yandex.net/priemka/api

proxy:
  upstream:
    default:
      url: https://paskills-common-testing.alice.yandex.net/priemka/api
    paskills-b2b:
      url: https://paskills-common-testing.alice.yandex.net/priemka/b2b
    bulbasaur:
      url: http://iot-beta.quasar.yandex.net
    iot-api:
      url: http://iot-beta.quasar.yandex.net
    dialogovo: # unavailable
      tvm_alias: ""
      url: ""

logbroker:
  enabled: false
  requests_percent: 0
