logging:
  dev_mode: true

tvm:
  token: token_for_local_interaction_1234

blackbox:
  tvm_id: 239
  url: http://dialogs.test.voicetech.yandex.net/bm

dialogs:
  tvm_alias: paskills-priemka
  url: https://paskills-common-testing.alice.yandex.net/priemka/api

proxy:
  upstream:
    default:
      tvm_alias: paskills-priemka
      url: https://paskills-common-testing.alice.yandex.net/priemka/api
    paskills-b2b:
      url: https://paskills-common-testing.alice.yandex.net/priemka/b2b
    bulbasaur:
      url: http://iot-beta.quasar.yandex.net
    iot-api:
      url: http://iot-beta.quasar.yandex.net
    dialogovo: # unavailable
      tvm_alias: ""
      url: ""
