logging:
  dev_mode: true

tvm:
  token: token_for_local_interaction_1234

blackbox:
  tvm_id: 224
  url: http://dialogs.test.voicetech.yandex.net/bt

dialogs:
  tvm_alias: paskills-testing
  url: https://paskills.test.voicetech.yandex.net/api

proxy:
  oauth:
    client_id: 049d7f40d1d54dd78399b405d5d75b15
    client_id_b2b: 848b4560b4464f06a6a30dd2a992d8a7
  upstream:
    default:
      tvm_alias: paskills-testing
      url: https://paskills.test.voicetech.yandex.net/api
    paskills-b2b:
      url: https://paskills.test.voicetech.yandex.net/b2b
    bulbasaur: # unavailable
      tvm_alias: ""
      url: ""
    iot-api: # unavailable
      url: ""
    dialogovo: # unavailable
      tvm_alias: ""
      url: ""
