attach_profiler: true

blackbox:
  tvm_id: 226
  url: https://blackbox-stress.yandex.net

dialogs:
  url: REPLACE_ME_WITH_ENV__DIALOGS_URL

proxy:
  upstream:
    default:
      url: REPLACE_ME_WITH_ENV__UPSTREAM_URL_DEFAULT
    paskills-b2b:
      url: REPLACE_ME_WITH_ENV__UPSTREAM_URL_PASKILLS_B2B
    bulbasaur:
      url: REPLACE_ME_WITH_ENV__UPSTREAM_URL_BULBASAUR
    iot-api:
      url: REPLACE_ME_WITH_ENV__UPSTREAM_URL_BULBASAUR
    dialogovo:
      url: REPLACE_ME_WITH_ENV__UPSTREAM_URL_DIALOGOVO
