blackbox:
  tvm_id: 224
  url: http://blackbox-test.yandex.ru

dialogs:
  url: https://paskills.test.voicetech.yandex.net/api

proxy:
  oauth:
    client_id: 049d7f40d1d54dd78399b405d5d75b15
    client_id_b2b: 848b4560b4464f06a6a30dd2a992d8a7
  upstream:
    default:
      url: https://paskills.test.voicetech.yandex.net/api
    paskills-b2b:
      url: https://paskills.test.voicetech.yandex.net/b2b
    bulbasaur:
      tvm_alias: bulbasaur
      url: http://iot-test.quasar.yandex.net
    iot-api:
      url: http://iot-test.quasar.yandex.net
    dialogovo: # unavailable
      tvm_alias: ""
      url: ""
