# -*-coding: utf8 -*-

intent_to_human_readable = {
    # Поиск контента
    "alice\tvinsless\tmusic": "Включить музыку",
    "personal_assistant\tscenarios\tmusic_play": "Включить музыку",
    "personal_assistant\tscenarios\tmusic_podcast": "Включить подскаст",
    "personal_assistant\tscenarios\tmusic_ambient_sound": "Включить звуки природы",
    "personal_assistant\tscenarios\tvideo_general_scenario": "Включить видео/фильм/сериал",
    "personal_assistant\tscenarios\tvideo_play": "Включить видео/фильм/сериал",
    "personal_assistant\tscenarios\tradio_play": "Включить радио",
    "personal_assistant\tscenarios\tget_weather": "Прогноз погоды",
    "personal_assistant\tscenarios\tget_weather_nowcast": "Прогноз погоды на ближайшее время",
    "personal_assistant\tscenarios\tmusic_fairy_tale": "Включить сказку",
    "personal_assistant\tscenarios\tget_news": "Рассказать новости",
    "personal_assistant\tscenarios\ttv_stream": "Включить телевизор (канал)",
    "personal_assistant\tscenarios\ttv_broadcast": "Показать программу телеканала",
    "personal_assistant\tscenarios\tfilm_gallery": "Включить видео/фильм/сериал",
    "personal_assistant\tscenarios\topen_site_or_app": "Открыть сайт/приложение",
    "personal_assistant\tscenarios\topen_site_or_app\topen": "Открыть сайт/приложение",
    "personal_assistant\tscenarios\tmusic_sing_song": "Спеть песню",

    # Похвала/критика/оскорбления
    "personal_assistant\thandcrafted\tuser_reactions_positive_feedback": "Похвала",
    "personal_assistant\thandcrafted\tuser_reactions_negative_feedback": "Критика",

    # Навигация по Станции
    "personal_assistant\tscenarios\tquasar\tgo_forward": "Включить следующий экран",
    "personal_assistant\tscenarios\tquasar\tgo_backward": "Включить предыдущий экран",
    "personal_assistant\tscenarios\tquasar\tgo_home": "Включить домашний экран",
    "personal_assistant\tscenarios\tquasar\tgo_to_the_beginning": "Перейти в начало списка",
    "personal_assistant\tscenarios\tquasar\tgo_to_the_end": "Перейти в конец списка",
    "personal_assistant\tscenarios\tquasar\tselect_video_from_gallery": "Выбрать видео из галлереи",
    "personal_assistant\tscenarios\tquasar\tselect_video_from_gallery_by_text": "Выбрать видео из галлереи",
    "personal_assistant\tscenarios\tquasar\tgoto_video_screen": "Включить видео/фильмы/сериалы",
    "personal_assistant\tscenarios\tquasar\topen_current_video": "Включить видео/фильм/сериал",

    # Управление проигрыванием музыки и видео
    "personal_assistant\tscenarios\tplayer_pause": "Остановить воспроизведение",
    "personal_assistant\tscenarios\tplayer_continue": "Продолжить воспроизведение",
    "personal_assistant\tscenarios\tplayer_next_track": "Включить следующий трек или видео",
    "personal_assistant\tscenarios\tplayer_previous_track": "Включить предыдущий трек или видео",
    "personal_assistant\tscenarios\tplayer_rewind": "Перемотать трек или видео на начало",
    "personal_assistant\tscenarios\tplayer_replay": "Повторить трек или видео",
    "personal_assistant\tscenarios\tplayer_repeat": "Повторить трек или видео",
    "personal_assistant\tscenarios\tplayer_like": "Положительная оценка музыки/видео",
    "personal_assistant\tscenarios\tplayer_dislike": "Отрицательная оценка музыки/видео",
    "personal_assistant\tscenarios\tplayer_shuffle": "Воспроизвести в случайном порядке",
    "personal_assistant\tscenarios\tmusic_what_is_playing": "Какой трек проигрывается?",
    "personal_assistant\thandcrafted\tquasar\tfuture_skill_equaizer": "Настроить эквалайзер",
    "personal_assistant\tscenarios\tmusic_play_more": "Включить больше определённой музыки",

    # Настройки звука
    "personal_assistant\tscenarios\tsound_set_level": "Установить уровень громкости",
    "personal_assistant\tscenarios\tsound_louder": "Увеличить громкость",
    "personal_assistant\tscenarios\tsound_quiter": "Уменьшить громкость",
    "personal_assistant\tscenarios\tsound_get_level": "Какой уровень громкости",
    "personal_assistant\tscenarios\tsound_unmute": "Включить звук",
    "personal_assistant\tscenarios\tsound_mute": "Выключить звук",

    # Работа со временем
    "personal_assistant\tscenarios\tget_time": "Запрос текущего времени",
    "personal_assistant\tscenarios\tget_date": "Запрос даты",
    "personal_assistant\tscenarios\talarm_set": "Установить будильник",
    "personal_assistant\tscenarios\talarm_cancel": "Отменить будильник",
    "personal_assistant\tscenarios\talarm_show": "Показать установленные будильники",
    "personal_assistant\tscenarios\talarm_stop_playing": "Выключить играющий будильник",
    "personal_assistant\thandcrafted\tquasar\tfuture_skill_what_music_on_alarm": "Какая музыка стоит на будильнике?",
    "personal_assistant\tscenarios\ttimer_set": "Установить таймер",
    "personal_assistant\tscenarios\ttimer_show": "Показать установленные таймеры",
    "personal_assistant\tscenarios\ttimer_cancel": "Отменить таймер",
    "personal_assistant\tscenarios\ttimer_stop_playing": "Выключить играющий таймер",
    "personal_assistant\tscenarios\ttimer_pause": "Поставить таймер на паузу",
    "personal_assistant\tscenarios\ttimer_resume": "Снять таймер с паузы",
    "personal_assistant\tscenarios\tsleep_timer_set": "Установить таймер сна",
    "personal_assistant\tscenarios\tsleep_timer_time_left": "Сколько осталось времени до выключения Станции (таймер сна)",
    "personal_assistant\tscenarios\tsleep_timer_how_long": "Сколько осталось времени до выключения Станции (таймер сна)",
    "personal_assistant\tscenarios\tcreate_reminder": "Установить напоминание",
    "personal_assistant\tscenarios\tcreate_reminder\tcancel": "Отменить напоминание",
    "personal_assistant\tscenarios\tlist_reminders": "Показать установленные напоминания",
    "personal_assistant\tscenarios\tlist_reminders\tscroll_next": "Показать следующее установленное напоминание",
    "personal_assistant\tscenarios\tcreate_todo": "Создать список дел",
    "personal_assistant\tscenarios\tlist_todo": "Показать список дел",

    # Навигатор
    "personal_assistant\tscenarios\tshow_route": "Построить маршрут",
    "personal_assistant\tscenarios\tshow_route\tshow_route_on_map": "Открыть маршрут на карте",
    "personal_assistant\tscenarios\tfind_poi": "Найти точку на карте",
    "personal_assistant\tscenarios\tfind_poi\tdetails": "Показать детали работы организации",
    "personal_assistant\tscenarios\tfind_poi\tcall": "Позвонить на телефон организации",
    "personal_assistant\tscenarios\tfind_poi\tscroll\tnext": "Показать следующую организацию из списка",
    "personal_assistant\tscenarios\tfind_poi\tscroll\tprev": "Показать предыдущюю организацию из списка",
    "personal_assistant\tscenarios\tfind_poi\tscroll\tby_index": "Выбрать организацию из списка по номеру",
    "personal_assistant\tscenarios\tfind_poi\tshow_on_map": "Показать найденную точку на карте",
    "personal_assistant\tscenarios\tshow_traffic": "Показать уровень пробок",
    "personal_assistant\tscenarios\tshow_traffic\tdetails": "Показать пробки на карте",
    "personal_assistant\tscenarios\tget_my_location": "Получить текущее местоположение пользователя",
    "personal_assistant\tscenarios\tget_my_location\tdetails": "Показать текущее местоположение пользователя на карте",
    "personal_assistant\tscenarios\tremember_named_location": "Построить маршрут / найти точку на карте",

    "personal_assistant\tnavi\treset_route": "Сбросить маршрут",
    "personal_assistant\tnavi\tadd_point": "Отметить дорожное событие/точку на карте",
    "personal_assistant\tnavi\tmap_search": "Найти на карте",
    "personal_assistant\tnavi\tparking_route": "Найти ближайшую парковку",
    "personal_assistant\tnavi\tshow_layer": "Показать слой в навигаторе (пробки, карта, спутник, парковки)",
    "personal_assistant\tnavi\thide_layer": "Скрыть слой в навигаторе (пробки, карта, спутник)",
    "personal_assistant\tnavi\thow_long_to_drive": "Сколько осталось до конца маршрута?",
    "personal_assistant\tnavi\twhen_we_get_there": "Расчитать время прибытия в конечную точку маршрута",
    "personal_assistant\tnavi\thow_long_traffic_jam": "Сколько осталось до конца пробки?",
    "personal_assistant\tnavi\tshow_route_on_map": "Показать маршрут на карте",
    "personal_assistant\tnavi\tchange_voice": "Сменить голос в навигаторе",

    # Драйв
    "personal_assistant\thandcrafted\tdrive\tparking_airport_dme": "Парковка Яндекс.Драйв в аэропорту Домодедово",
    "personal_assistant\thandcrafted\tdrive\tparking_airport_vko": "Парковка Яндекс.Драйв в аэропорту Внуково",
    "personal_assistant\thandcrafted\tdrive\tparking_airport_svo": "Парковка Яндекс.Драйв в аэропорту Шереметьево",
    "personal_assistant\thandcrafted\tdrive\tparking_airport_led": "Парковка Яндекс.Драйв в аэропорту Пулково",
    "personal_assistant\thandcrafted\tdrive\tgas_station": "Как заправить автомобиль в Яндекс.Драйве",

    # onboarding
    "personal_assistant\tscenarios\tonboarding": "Рассказать, что умеет Алиса на этом устройстве",
    "personal_assistant\tscenarios\tgames_onboarding": "Предложить игры",
    "personal_assistant\tscenarios\tradio_play_onboarding": "Предложить радиостанции",
    "personal_assistant\tscenarios\twhat_can_you_do": "Рассказать, что умеет Алиса на этом устройстве",

    # Поиск
    "personal_assistant\tscenarios\tsearch": "Найти в интернете",
    "personal_assistant\tscenarios\tsearch\tserp": "Найти в интернете",
    "personal_assistant\tscenarios\tsearch\tentity_name": "Найти в интернете",
    "personal_assistant\tscenarios\tsearch\tfactoid": "Найти факт",
    "personal_assistant\tscenarios\tsearch\tfactoid_call": "Позвонить",
    "personal_assistant\tscenarios\tsearch\tcalculator": "Посчитать в калькуляторе",
    "personal_assistant\tscenarios\tsearch\tnav_url": "Открыть сайт",
    "personal_assistant\tscenarios\tsearch\tshow_on_map": "Найти на карте",
    "personal_assistant\tscenarios\tsearch\tmap_search_url": "Найти в интернете или на карте",
    "personal_assistant\tscenarios\tsearch\tmap_search_url\tshow_on_map": "Найти на карте",
    "personal_assistant\tscenarios\tsearch\tmap_search_url\tserp": "Найти в интернете",

    "personal_assistant\tinternal\thardcoded": "",
    "personal_assistant\tscenarios\texternal_skill": "Активация навыка",
    "personal_assistant\tscenarios\texternal_skill\tdeactivate": "Выключение навыка",

    "personal_assistant\thandcrafted\tcancel": "Выключение устройства",
    "personal_assistant\thandcrafted\tfast_cancel": "Выключение устройства",
    "personal_assistant\thandcrafted\trude": "Грубое оскорбление",
    "personal_assistant\tscenarios\tbluetooth_on": "Включить bluetooth",
    "personal_assistant\tscenarios\tbluetooth_off": "Выключить bluetooth",
    "personal_assistant\thandcrafted\tquasar\tcan_you_connect_bluetooth": "",
    "personal_assistant\tscenarios\ttranslate": "Перевести фразу",
    "personal_assistant\tscenarios\tconvert": "Курсы валют",
    "personal_assistant\tscenarios\trandom_num": "Выбрать случайное число",
    "personal_assistant\tgeneral_conversation\tgeneral_conversation": "Болтовня/диалог",
    "personal_assistant\tgeneral_conversation\tgeneral_conversation_dummy": "Оксорбление",
    "personal_assistant\tscenarios\ttaxi_order": "Заказать такси",
    "personal_assistant\tscenarios\trepeat": "Повторить фразу",
    "personal_assistant\tscenarios\tcall": "Позвонить",
    "alice\tiot_do": "Запрос умного дома",
    "personal_assistant\tscenarios\thow_much": "Определить стоимость",
    "personal_assistant\thandcrafted\tstation_how_much": "Стоимость Яндекс.Станции",
    "personal_assistant\tscenarios\timage_what_is_this": "Опеределить что изображено на картинке/фото",
    "personal_assistant\tscenarios\tcommon\tcancel_list": "Отменить действие",
    "personal_assistant\thandcrafted\thello": "Приветствие",
    "personal_assistant\thandcrafted\ttell_me_a_joke": "Рассказать шутку",
    "personal_assistant\thandcrafted\thow_are_you": "Рассказать как дела"
}
