classifiers/scenarios/crm_bot:
  filename: classifiers.scenarios.crm_bot
  files:
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_activate
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_activate__continuation
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_apply
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_get
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_not_recieved
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_not_recieved_b
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_not_recieved_c
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_not_recieved_ca
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_not_recieved_cb
  - classifiers/scenarios/crm_bot.scenarios.bonus_bb_not_recieved_cc
  - classifiers/scenarios/crm_bot.scenarios.bonus_greet
  - classifiers/scenarios/crm_bot.scenarios.bonus_overdue
  - classifiers/scenarios/crm_bot.scenarios.bonus_problem
  - classifiers/scenarios/crm_bot.scenarios.bonus_problem_promocode
  - classifiers/scenarios/crm_bot.scenarios.bonus_problem_ya_plus
  - classifiers/scenarios/crm_bot.scenarios.bonus_promocode
  - classifiers/scenarios/crm_bot.scenarios.bonus_return_policy
  - classifiers/scenarios/crm_bot.scenarios.bonus_sbrf_thankyou
  - classifiers/scenarios/crm_bot.scenarios.bonus_sbrf_thankyou_get
  - classifiers/scenarios/crm_bot.scenarios.bonus_sbrf_thankyou_how_to
  - classifiers/scenarios/crm_bot.scenarios.bonus_sbrf_thankyou_not_available
  - classifiers/scenarios/crm_bot.scenarios.bonus_sbrf_thankyou_problem
  - classifiers/scenarios/crm_bot.scenarios.bonus_ya_plus
  - classifiers/scenarios/crm_bot.scenarios.bye
  - classifiers/scenarios/crm_bot.scenarios.bye_narrow
  - classifiers/scenarios/crm_bot.scenarios.call_me
  - classifiers/scenarios/crm_bot.scenarios.cashback
  - classifiers/scenarios/crm_bot.scenarios.cashback_problems
  - classifiers/scenarios/crm_bot.scenarios.choose_for_me
  - classifiers/scenarios/crm_bot.scenarios.complaints_call_center
  - classifiers/scenarios/crm_bot.scenarios.complaints_cancel
  - classifiers/scenarios/crm_bot.scenarios.complaints_delivery_price
  - classifiers/scenarios/crm_bot.scenarios.complaints_delivery_rescheduled
  - classifiers/scenarios/crm_bot.scenarios.complaints_issue_status
  - classifiers/scenarios/crm_bot.scenarios.complaints_other
  - classifiers/scenarios/crm_bot.scenarios.complaints_packaging
  - classifiers/scenarios/crm_bot.scenarios.complaints_personel
  - classifiers/scenarios/crm_bot.scenarios.credit
  - classifiers/scenarios/crm_bot.scenarios.credit_conditions
  - classifiers/scenarios/crm_bot.scenarios.credit_how_to
  - classifiers/scenarios/crm_bot.scenarios.credit_not_available
  - classifiers/scenarios/crm_bot.scenarios.delivery_cityname
  - classifiers/scenarios/crm_bot.scenarios.delivery_courier_contacts
  - classifiers/scenarios/crm_bot.scenarios.delivery_deadline
  - classifiers/scenarios/crm_bot.scenarios.delivery_deadline__have_order_already
  - classifiers/scenarios/crm_bot.scenarios.delivery_free
  - classifiers/scenarios/crm_bot.scenarios.delivery_incomplete_package
  - classifiers/scenarios/crm_bot.scenarios.delivery_nooption
  - classifiers/scenarios/crm_bot.scenarios.delivery_options
  - classifiers/scenarios/crm_bot.scenarios.delivery_options__deadline_button
  - classifiers/scenarios/crm_bot.scenarios.delivery_options__price_button
  - classifiers/scenarios/crm_bot.scenarios.delivery_price
  - classifiers/scenarios/crm_bot.scenarios.delivery_price_differs_in_cart
  - classifiers/scenarios/crm_bot.scenarios.delivery_procedure
  - classifiers/scenarios/crm_bot.scenarios.delivery_tracking
  - classifiers/scenarios/crm_bot.scenarios.delivery_wrong_package
  - classifiers/scenarios/crm_bot.scenarios.feedback_negative
  - classifiers/scenarios/crm_bot.scenarios.feedback_negative_bad_classifier
  - classifiers/scenarios/crm_bot.scenarios.feedback_negative_bad_content
  - classifiers/scenarios/crm_bot.scenarios.feedback_positive
  - classifiers/scenarios/crm_bot.scenarios.feedback_positive__continuation
  - classifiers/scenarios/crm_bot.scenarios.file_input__continuation
  - classifiers/scenarios/crm_bot.scenarios.garbage
  - classifiers/scenarios/crm_bot.scenarios.hello
  - classifiers/scenarios/crm_bot.scenarios.help_me_configure
  - classifiers/scenarios/crm_bot.scenarios.lk_auth
  - classifiers/scenarios/crm_bot.scenarios.lk_auth_problem
  - classifiers/scenarios/crm_bot.scenarios.lk_edit
  - classifiers/scenarios/crm_bot.scenarios.lk_order_connect
  - classifiers/scenarios/crm_bot.scenarios.lk_register
  - classifiers/scenarios/crm_bot.scenarios.lk_register_problem
  - classifiers/scenarios/crm_bot.scenarios.lk_sbrf_auth
  - classifiers/scenarios/crm_bot.scenarios.operator_redirect
  - classifiers/scenarios/crm_bot.scenarios.operator_redirect_verbose_continuation
  - classifiers/scenarios/crm_bot.scenarios.order_alice
  - classifiers/scenarios/crm_bot.scenarios.order_cancel
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_accident
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_accident__already_paid
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_deadline
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_deadline__redirect
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me__bought_cheaper
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me__changed_mind
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me__data
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me__placed_other_order
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me__reason
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me__refused_delivery
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_for_me_finish
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_we_did
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_we_did__continuation
  - classifiers/scenarios/crm_bot.scenarios.order_cancel_we_did__data
  - classifiers/scenarios/crm_bot.scenarios.order_change
  - classifiers/scenarios/crm_bot.scenarios.order_change_goods
  - classifiers/scenarios/crm_bot.scenarios.order_error
  - classifiers/scenarios/crm_bot.scenarios.order_for_me
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective__after_a_while
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective__after_a_while__no_sc
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective__after_a_while__not_fixable
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective__after_a_while__rejected
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective__after_a_while__thanks
  - classifiers/scenarios/crm_bot.scenarios.order_got_defective__right_after
  - classifiers/scenarios/crm_bot.scenarios.order_how_to
  - classifiers/scenarios/crm_bot.scenarios.order_prolong_storage
  - classifiers/scenarios/crm_bot.scenarios.order_return
  - classifiers/scenarios/crm_bot.scenarios.order_return_complications
  - classifiers/scenarios/crm_bot.scenarios.order_return_complications__fill_problems
  - classifiers/scenarios/crm_bot.scenarios.order_return_complications__no_auth
  - classifiers/scenarios/crm_bot.scenarios.order_return_complications__problems_other
  - classifiers/scenarios/crm_bot.scenarios.order_return_fine
  - classifiers/scenarios/crm_bot.scenarios.order_return_fine__14days
  - classifiers/scenarios/crm_bot.scenarios.order_return_fine__7days
  - classifiers/scenarios/crm_bot.scenarios.order_return_fine__forbidden
  - classifiers/scenarios/crm_bot.scenarios.order_return_policy
  - classifiers/scenarios/crm_bot.scenarios.order_status
  - classifiers/scenarios/crm_bot.scenarios.order_status__change_address
  - classifiers/scenarios/crm_bot.scenarios.order_status__continuation
  - classifiers/scenarios/crm_bot.scenarios.order_status__data
  - classifiers/scenarios/crm_bot.scenarios.order_status__not_delivered
  - classifiers/scenarios/crm_bot.scenarios.order_status__where_is_pickup_location
  - classifiers/scenarios/crm_bot.scenarios.other_b2b
  - classifiers/scenarios/crm_bot.scenarios.payment_issues
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_a
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_aa
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_ab
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_ac
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_b
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_c
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_ca
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_caa
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_cab
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_cb
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_cc
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_cd
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_ce
  - classifiers/scenarios/crm_bot.scenarios.payment_issues_cf
  - classifiers/scenarios/crm_bot.scenarios.payment_legal_entity
  - classifiers/scenarios/crm_bot.scenarios.payment_options
  - classifiers/scenarios/crm_bot.scenarios.payment_options_offline
  - classifiers/scenarios/crm_bot.scenarios.payment_options_online
  - classifiers/scenarios/crm_bot.scenarios.payment_options_online_how_to
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_cancellation
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_cancellation__card
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_cancellation__credit
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_cancellation__sbrf_thanks
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_return
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_return__card
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_return__credit
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_return__sbrf_thanks
  - classifiers/scenarios/crm_bot.scenarios.payment_return_policy_after_return__when_arrived
  - classifiers/scenarios/crm_bot.scenarios.payment_return_problem
  - classifiers/scenarios/crm_bot.scenarios.pickup_box_ya
  - classifiers/scenarios/crm_bot.scenarios.pickup_box_ya_problem
  - classifiers/scenarios/crm_bot.scenarios.pickup_location_find
  - classifiers/scenarios/crm_bot.scenarios.pickup_location_schedule
  - classifiers/scenarios/crm_bot.scenarios.preorder_approve
  - classifiers/scenarios/crm_bot.scenarios.preorder_consultation
  - classifiers/scenarios/crm_bot.scenarios.propositions
  - classifiers/scenarios/crm_bot.scenarios.sbrf_certificate
  - classifiers/scenarios/crm_bot.scenarios.search
  - classifiers/scenarios/crm_bot.scenarios.search__cant_find
  - classifiers/scenarios/crm_bot.scenarios.search__other
  - classifiers/scenarios/crm_bot.scenarios.search__problems
  - classifiers/scenarios/crm_bot.scenarios.search__where
  - classifiers/scenarios/crm_bot.scenarios.search_details
  - classifiers/scenarios/crm_bot.scenarios.search_details__no_info
  - classifiers/scenarios/crm_bot.scenarios.search_details_button
  - classifiers/scenarios/crm_bot.scenarios.search_is_legal
  - classifiers/scenarios/crm_bot.scenarios.search_warranty
  - classifiers/scenarios/crm_bot.scenarios.search_warranty_duration
  - classifiers/scenarios/crm_bot.scenarios.search_warranty_duration__no_info
  - classifiers/scenarios/crm_bot.scenarios.search_warranty_location
  - classifiers/scenarios/crm_bot.scenarios.search_warranty_paper
  - classifiers/scenarios/crm_bot.scenarios.swear
  last_update: '2020-09-30 15:51:02'
  name: classifiers/scenarios/crm_bot
  resource_id: '1750439709'
  sha256: d0726a5a34d1be3a78a831d17bda6b628072e78f4f7ab32cdb4facd44545a129
  task_id: '785364828'
classifiers/scenarios/model_meta_data:
  filename: classifiers.scenarios.model_meta_data
  files:
  - classifiers/scenarios/model_meta_data
  last_update: '2020-09-30 15:51:02'
  name: classifiers/scenarios/model_meta_data
  resource_id: '1750441615'
  sha256: 31e355ec67306594530519ed67b97201e1e7805ffd39fe4aca747a522b4d5f63
  task_id: '785365710'
custom_entities:
  filename: custom_entities
  files:
  - custom_entities/confirmation/confirmation.fst
  - custom_entities/confirmation/flags.txt
  - custom_entities/confirmation/maps.json
  - custom_entities/confirmation/sequence.txt
  - custom_entities/confirmation/symbols.sym
  - custom_entities/confirmation/weights.json
  - custom_entities/search_intents/flags.txt
  - custom_entities/search_intents/maps.json
  - custom_entities/search_intents/search_intents.fst
  - custom_entities/search_intents/sequence.txt
  - custom_entities/search_intents/symbols.sym
  - custom_entities/search_intents/weights.json
  last_update: '2020-09-30 15:51:02'
  name: custom_entities
  resource_id: '1750444033'
  sha256: 798e21bdd812068b802f9ace47284efaee3cc2c1994f5aaa2af9705b3529d60d
  task_id: '785366587'
metric_learning:
  filename: metric_learning
  files:
  - metric_learning/metric_learning_info.json
  - metric_learning/pokupki/checkpoint
  - metric_learning/pokupki/checkpoint-1100.data-00000-of-00001
  - metric_learning/pokupki/checkpoint-1100.index
  - metric_learning/pokupki/checkpoint-1300.data-00000-of-00001
  - metric_learning/pokupki/checkpoint-1300.index
  last_update: '2020-09-30 15:51:02'
  name: metric_learning
  resource_id: '1750446254'
  sha256: 9be84464692c8f3b426ccb8a40f860d45b6a52b9a720a71de8114986535ebf3f
  task_id: '785367489'
tagger/tagger.data/crm_bot:
  filename: tagger.tagger.data.crm_bot
  files:
  - tagger/tagger.data/crm_bot.scenarios.bonus_bb_activate__continuation/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.bonus_bb_activate__continuation/model_description
  - tagger/tagger.data/crm_bot.scenarios.choose_for_me/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.choose_for_me/model_description
  - tagger/tagger.data/crm_bot.scenarios.feedback_negative/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.feedback_negative/model_description
  - tagger/tagger.data/crm_bot.scenarios.feedback_positive/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.feedback_positive/model_description
  - tagger/tagger.data/crm_bot.scenarios.feedback_positive__continuation/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.feedback_positive__continuation/model_description
  - tagger/tagger.data/crm_bot.scenarios.file_input__continuation/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.file_input__continuation/model_description
  - tagger/tagger.data/crm_bot.scenarios.operator_redirect_verbose_continuation/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.operator_redirect_verbose_continuation/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_accident/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_accident/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_deadline/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_deadline/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_for_me/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_for_me/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_for_me__data/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_for_me__data/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_for_me_finish/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_for_me_finish/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_we_did/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_we_did/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_we_did__continuation/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_we_did__continuation/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_we_did__data/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_cancel_we_did__data/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_status/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_status/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_status__continuation/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_status__continuation/model_description
  - tagger/tagger.data/crm_bot.scenarios.order_status__data/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.order_status__data/model_description
  - tagger/tagger.data/crm_bot.scenarios.payment_issues_aa/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.payment_issues_aa/model_description
  - tagger/tagger.data/crm_bot.scenarios.payment_issues_ab/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.payment_issues_ab/model_description
  - tagger/tagger.data/crm_bot.scenarios.payment_issues_caa/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.payment_issues_caa/model_description
  - tagger/tagger.data/crm_bot.scenarios.search/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.search/model_description
  - tagger/tagger.data/crm_bot.scenarios.search__where/model.mmap
  - tagger/tagger.data/crm_bot.scenarios.search__where/model_description
  last_update: '2020-09-30 15:51:02'
  name: tagger/tagger.data/crm_bot
  resource_id: '1750449654'
  sha256: 99e578561dbb169e5412664aa08273205f25199043a312b54293b7c584e94880
  task_id: '785368466'
tagger/tagger.info:
  filename: tagger.tagger.info
  files:
  - tagger/tagger.info
  last_update: '2019-10-15 08:07:06'
  name: tagger/tagger.info
  resource_id: '1166784498'
  sha256: 3c43af5c05993b51560cc1ba8c6bf2bf29a953559622f89115d4f35f5d2ef1fa
  task_id: '528253215'
