children:
  classifiers:
    children:
      scenarios:
        patterns_file: 'crm_bot/config/chunk_patterns.yaml'
        prune_suffix_by: __
      search_or_converse:
        depth: 0
  custom_entities:
    depth: 0
  tagger:
    children:
      tagger.data:
        patterns_file: 'crm_bot/config/chunk_patterns.yaml'
        prune_suffix_by: __
