personal_assistant.scenarios.quasar.go_backward:
  - "^(алиса )?(выйди|выйти|выход|(вернись )?назад)$"
personal_assistant.scenarios.quasar.go_to_the_beginning:
  - "^(алиса )?(в начало|начало)$"
personal_assistant.scenarios.quasar.go_to_the_end:
  - "^(алиса )?(конец|в конец)$"
personal_assistant.scenarios.quasar.go_home:
  - "^(алиса )?(домой|главное меню|на главную|(на )?главный экран|выключи все|меню|выйди в главное меню)$"

personal_assistant.scenarios.sound_set_level:
  - "^(алиса )?((сделай |поставь )?(громкость|звук) (на )?(\\d{1,2}|минимум|максимум)|максимальная громкость|минимальная громкость)$"
personal_assistant.scenarios.sound_louder:
  - "^(алиса )?((сделай |включи )?(чуть )?(по)?громче|прибавь (звук|громкость)|(по)?громче сделай)$"
personal_assistant.scenarios.sound_quiter:
  - "^(алиса )?((сделай |включи )?(чуть )?(по)?тише|убавь (звук|громкость)|(по)?тише сделай)$"
personal_assistant.scenarios.sound_louder__ellipsis:
  - "^(алиса )?((сделай )?еще (по)?громче)$"
personal_assistant.scenarios.sound_quiter__ellipsis:
  - "^(алиса )?((сделай )?еще (по)?тише)$"
personal_assistant.scenarios.sound_unmute:
  - "^(алиса )?(включи звук)$"
personal_assistant.scenarios.sound_mute:
  - "^(алиса )?(выключи звук)$"
personal_assistant.scenarios.sound_get_level:
  - "^(алиса )?(какая (сейчас )?громкость)$"

personal_assistant.scenarios.alarm_stop_playing:
  - "^(алиса )?стоп"
personal_assistant.scenarios.timer_stop_playing:
  - "^(алиса )?стоп"

personal_assistant.scenarios.player_next_track:
  - "^(алиса )?((включи|поставь|давай) )?(следующ(ая|ую|ий|ее)|друг(ая|ой|ую|ое))( (песн[яю]|трек|сери[яю]|видео|сказк[ау]|подкаст|композици[яю]|музык[ау]))$"
  - "^(алиса )?(перемотай (дальше|вперед|далее)|перемотай|переключи( песню| трек)?|включи что нибудь другое)$"
personal_assistant.scenarios.player_previous_track:
  - "^(алиса )?((включи |поставь |давай )?(предыдущ|прошл)(ую|ая|ий)( песн[юя]| трек| сери[яю]| видео| сказк[ау]| подкаст| композици[яю]| музык[ау]))$"
personal_assistant.scenarios.player_rewind:
  - "^(алиса )?(перемотай( на)?( \\d+)? (минут[уы]?|секунды?)( вперед| назад)?|(на )?(\\d+ )?(минут[уы]?|секунды?) (вперед|назад))$"
personal_assistant.scenarios.player_pause:
  - "^(алиса )?(пауза|стоп|(выключи|останови|выключай) (музыку|песню|фильм)|(поставь )?на паузу)$"
personal_assistant.scenarios.player_replay:
  - "^(алиса )?(сначала|заново|включи сначала|повтори|включи заново|начни сначала|поставь сначала|перемотай на начало|включи еще раз)$"
personal_assistant.scenarios.player_like:
  - "^(алиса )?(лайк|поставь лайк|мне нравится|нравится|мне нравится эта песня|добавь в избранное)$"
personal_assistant.scenarios.player_dislike:
  - "^(алиса )?(дизлайк|мне не нравится|не нравится|мне не нравится эта песня)$"

personal_assistant.scenarios.common_forward:
  - "^(алиса )?(давай )?(дальше|вперед|далее)$"
  - "^(алиса )?(давай )?следующ(ая|ую|ий|ее)$"
personal_assistant.scenarios.common_backward:
  - "^(алиса )?(давай |вернись )?(предыдущ(ую|ая|ее|ий)|обратно)$"
