personal_assistant.scenarios.external_skill:
  - '^давай (?P<skill_id>поболтаем)$'
  - '^(?P<skill_id>покажи что у тебя в голове)$'
personal_assistant.scenarios.music_play:
  - '^включи (?P<epoch>вечные) хиты$'
  - '^(?:алиса )?(?P<action_request>включи|вруби|запусти|можешь включить|слушать|поставь|играй)?\s*(?: мне)?(?: пожалуйста)?(?:мое(?: любимое)?(?: яндекс)? радио|(?:яндекс )?радио мое|мою радиостанцию|(?:яндекс )?радио на моей волне)(?: пожалуйста)?$'
  - '^(?:алиса )?(?:открой|найди)(?: мне)?(?: пожалуйста)?(?: мое радио| мою радиостанцию)(?: пожалуйста)?$'
personal_assistant.scenarios.tv_stream:
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)( тв)?(?: канал| телеканал| передач.) (?P<channel>(рыболов|про рыбалку|о рыбалке|(?:наша )?рыбалка|(?:нашу )?рыбалку))'
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)(?: мне)?(?: пожалуйста)?(?: канал| телеканал)? (?P<channel>((?:мой )?(?:персональный |личный |собственный )(?:яндекс )?(?:телеканал|канал|эфир)))'
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)(?: мне)?(?: пожалуйста)?(?: канал| телеканал)? (?P<channel>((?:мой )(?:персональный |личный |собственный )?(?:яндекс )?(?:телеканал|канал|эфир)))'
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)(?: мне)?(?: пожалуйста)? (?P<channel>(яндекс (?:телеканал|канал)))'
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)(?: мне)?(?: пожалуйста)? (?P<channel>(?:трансляцию |прямую трансляцию |прямой эфир )?(?:хоккей|хоккея|кубка стэнли|кубок стенли|нхл))'
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)(?: мне)?(?: пожалуйста)? (?:телеканал |канал )?(?P<channel>концерты?).* (?:в|на) (?:яндекс |прямом )?эфире$'
  - '^(?:алиса )?(?:включи|покажи|запусти|поставь|смотреть|найди)(?: мне)?(?: пожалуйста)? (?:телеканал |канал )?(?P<channel>театры?) (?:в|на) (?:яндекс |прямом )?эфире$'

personal_assistant.scenarios.avia__ask_to:
  - '^(?:в )?(?P<geo_to>санкт петербург)$'

personal_assistant.scenarios.voiceprint_enroll__collect_voice:
  - '^.*(?:называй меня|мое имя|меня зовут|зови меня) (?P<user_name>.*)$'

# блокируем варианты "моего кота зовут" "называй мою сестру"
# также блокируем "не называй меня вася" или "меня зовут не вадим"
personal_assistant.scenarios.set_my_name:
  - '^(?!.*(?:\W|^)мою фамилию(?:\W|$)).*(?:\W|^)(?P<distractor>моего|мою|нашего|нашу|не)(?:\W|$).*$'

personal_assistant.scenarios.show_route__ellipsis:
  - '^(?P<confirmation>.*)$'

personal_assistant.scenarios.messaging:
  - '(напиши|отправь) (в )?(?P<client>смс|(в.(тс|ц)апп?|whatsapp)) (?P<recipient>.+)((с текстом |текст)?о том что|что) (?P<text>.+)'
  - '(напиши|отправь) (?P<recipient>.+?) (в )?(?P<client>смс|(в.(тс|ц)апп?|whatsapp)) ((с текстом |текст)?о том что|что) (?P<text>.+)'
  - '(напиши|отправь) (?P<recipient>.+?) (текст|сообщение) (что )?(?P<text>.+) в (?P<client>смс|(в.(тс|ц)апп?|whatsapp))'
  - '(напиши|отправь) сообщение (?P<recipient>.+?) (о том что |что )?(?P<text>.+?) (в )?(?P<client>смс|смской|(в.(тс|ц)апп?|whatsapp))'
  - '(напиши|отправь) (?P<client>смс) на короткий номер (?P<recipient>\d+) с текстом (?P<text>.+)'
  - '(напиши|отправь) сообщение (?P<recipient>.+?) (о том что|что) (?P<text>.+)'
  - '(напиши|отправь) (в )?(?P<client>смс|(в.(тс|ц)апп?|whatsapp)) ((с текстом |текст )?о том что|что) (?P<text>.+)'
  - '(напиши|отправь) (?P<recipient>.+?) (?P<client>смс|смска)'

personal_assistant.scenarios.messaging__client:
- '(?P<client>(sms|смс)|(?:в.(?:тс|ц)апп?|whatsapp)|(в(ай|и)бер|viber)|(вк|vk|(в ?)?контакт(ик)?)|(телег(а|у|рамм?)|telegram))'

personal_assistant.scenarios.messaging__text:
- '(?P<text>.+)'
