OWNER(g:paskills)

JAVA_PROGRAM(kronstadt-shard-runner)


WITH_JDK()
WITH_KOTLIN()
JDK_VERSION(17)

INCLUDE(${ARCADIA_ROOT}/alice/paskills/dialogovo/ya.make.dependency_management.inc)

PEERDIR(
    alice/library/java/vaultclient
    alice/kronstadt/server
    alice/kronstadt/core
)

IF(${KRONSTADT_SCENARIO_INC})
    # file is generated by run_generator.sh
    INCLUDE(${ARCADIA_ROOT}/${KRONSTADT_SCENARIO_INC})
ENDIF()

JAVA_SRCS(PACKAGE_PREFIX ru.yandex.alice.kronstadt.runner SRCDIR src/main/kotlin **/*)
JAVA_SRCS(SRCDIR src/main/resources **/*)

LINT(extended)

JAVA_DEPENDENCIES_CONFIGURATION(
    FORBID_DIRECT_PEERDIRS
    FORBID_DEFAULT_VERSIONS
#FORBID_CONFLICT_DM_RECENT
)

KOTLINC_FLAGS(
    -Xjvm-default=all
    -java-parameters
)

JAVAC_FLAGS(
    -parameters
)

EXCLUDE(
    contrib/java/com/google/protobuf/protobuf-javalite
    contrib/java/ch/qos/logback
    contrib/java/org/apache/logging/log4j/log4j-to-slf4j
    contrib/java/org/apache/tomcat/embed/tomcat-embed-websocket
    contrib/java/org/springframework/boot/spring-boot-starter-tomcat
    contrib/java/io/micrometer/micrometer-core
)

END()
