files:
  - name: /logs/matrix_scheduler.evlog
    send_delay: 5
    topic: /matrix/scheduler/prod/eventlog
    format: eventlog
  - name: /logs/matrix_scheduler.rtlog
    send_delay: 5
    topic: /matrix/scheduler/prod/rtlog
    format: eventlog
logger:
  file: /logs/push-client.log
  level: 5
  remote: 0
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
  proto: pq
  tvm-server-id: 2001059
  tvm-client-id: 2023285
watcher:
  state: push-client-state
