what_can_you_do:
  nlu:
    - test
    - чему ты научилась
    - чему ты научилась за последнее время
    - предложи ты сама тему
    - а чем ты можешь быть полезен
    - а чем ты можешь быть полезна
    - а что ты можешь
    - а что еще ты можешь
    - а что еще ты умеешь
    - мда, а что ты вообще можешь
    - что еще ты можешь
    - какие команды ты знаешь
    - какие команды знаешь
    - что еще ты умеешь
    - что умеешь
    - а что ты умеешь алиса кроме сервисов яндекса
    - а ты умеешь находить смешные видео
    - а ты умеешь находить смешные картинки
    - а что ты умеешь
    - зачем ты нужен
    - зачем ты нужна
    - для чего ты нужен
    - для чего ты нужна
    - в чем ты полезна
    - в чем ты полезен
    - чем ты полезна
    - чем ты полезен
    - для чего ты полезна
    - для чего ты полезен
    - тест
    - чем ты можешь мне помочь
    - в чем ты можешь помочь
    - как ты можешь помочь
    - что ты можешь
    - что ты умеешь
    - что ты умеешь делать
    - что ты знаешь
    - как тобой пользоваться
    - так слушай что спросить то
    - расскажи что ты умеешь
    - расскажи что умеешь
    - скажи что умеешь
    - скажи какие у тебя есть функции
    - какие у тебя есть команды
    - в чем твоя польза
    - в чем от тебя польза
    - какая твоя польза
    - что ты помогаешь делать
    - что ты можешь посоветовать
    - ты можешь посоветовать
    - ты умеешь разговаривать
    - ты умеешь говорить
    - ты можешь разговаривать
    - ты можешь говорить
    - про что ты умеешь разговаривать
    - про что ты умеешь отвечать
    - про что ты можешь поговорить
    - про что с тобой говорить
    - про что тебя спрашивать
    - про что тебя спросить
    - про что с тобой поговорить
    - про что тебя можно спрашивать
    - о чем тебя можно спросить
    - какие вопросы ты понимаешь
    - на какие темы ты любишь разговаривать
    - о чем тебя можно спрашивать
    - чего бы спросить
    - чего бы такого спросить
    - чему тебя научили
    - чему тебя там в яндексе научили
    - чему ты научилась
    - чему ты научился
    - что бы спросить
    - что бы такого спросить
    - что ты вообще научилось
    - что я могу у тебя узнать
    - я не знаю что спросить
    - спасибо а теперь скажи пожалуйста что ты еще можешь
    - а что вы понимаете
    - хорошо а ты что делаешь
    - что вы делаете
    - а что ты понимаешь
    - а как мне с тобой общаться
    - твои возможности
    - как с тобой начать общаться
    - а в разговорах на какие темы ты сильна
    - в разговорах на какие темы ты сильна
    - а в каких темах ты сильна
    - а в чем ты сильна
    - а на какие темы ты сильна
    - яндекс что ты можешь

  nlg:
    - 'Сейчас просто болтаем, а если нужно узнать что-то нужное — скажите "Хватит болтать" и задайте вопрос.'
    - 'Умею узнавать маршруты, пробки, курсы валют и многое другое — просто скажите "Хватит болтать" и задайте вопрос.'
    - 'Умею просто поболтать, как сейчас. А если нужно поискать в интернете или открыть сайт — скажите "Хватит болтать" и задайте вопрос.'
    - 'Чтобы услышать про погоду, маршруты, пробки или курсы валют — скажите "Хватит болтать" и задайте вопрос.'
    - 'Ищу разные места, помогаю с маршрутами — просто скажите "Хватит болтать" и спросите.'


phone_call:
  nlu:
    - позвони маме
    - позвони папе
    - позвони сыну
    - позвони дочке
    - позвони брату
    - позвони сестре
    - ты умеешь звонить
    - ты можешь позвонить
    - набери маму
    - набери папу
    - набери сына
    - набери дочку
    - набери брата
    - набери сестру
    - ты можешь позвонить маме
    - ты можешь позвонить папе
    - ты можешь позвонить сыну
    - ты можешь позвонить дочери
    - ты можешь позвнить брату
    - ты можешь позвонить сестре
    - найди в моих контактах
    - открой мои контакты
    - посмотри мои контакты
    - найди в моих контактах
    - позвони кому-нибудь
    - звонить будешь
    - ты работаешь с телефонной книгой
    - открой записную книжку спасибо
    - алиса ты умеешь набирать телефон
    - позвони жена
    - позвонить можно
    - звони
    - очень хороша автоответчик
    - позвони ксюши
    - позвонить сереге
    - а ну давай позвонить любимой
    - а через тебя можно позвонить
    - алло позвоните маме чтобы не сказать что полина ко мне не лезла
    - звоните нашей маме скажите когда она приедет
    - набери абоненту мама
    - позвони в скорую
    - позвони в реанимацию
    - позвони пожарным
    - позвони спасателям
    - позвони в милицию
    - позвони в полицию
    - позвони в мчс
    - вызови скорую
    - вызови реанимацию
    - вызови полицию
    - вызови пожарных
    - вызови милицию
    - вызови полицию
    - вызови мчс
    - набери номер скорой
    - набери номер реанимации
    - набери номер пожарных
    - набери номер милиции
    - набери номер полиции
    - набери номер мчс
    - звони в скорую
    - звони скорой
    - звони пожарным
    - звони в милицию
    - звони ментам
    - звони в полицию
    - звони полицейским
    - звони спасателям
    - звони пожарным
    - звони пожарникам
    - звони мчс
    - звони в мчс
    - звони в реанимацию

  nlg:
    - 'Я умею звонить в скорую, МЧС или полицию: скажите "Хватит болтать" и попросите.'
    - 'Я могу звонить в экстренные службы, для этого скажите "Хватит болтать" и потом — "Позвони в скорую" или "Вызови полицию".'
    - 'Могу позвонить в скорую или полицию — скажите "Хватит болтать" и попросите меня об этом.'
