OWNER(g:alice)

RECURSE(
    api
    entities_collector
    entities_collector/ut
    feature_aggregator
    feature_extractor
    fixlist_index
    fixlist_index/data
    fixlist_index/ut
    frame_filler
    frame_aggregator
    fresh_options
    fst
    fst/data
    item_selector
    locale
    query_normalizer
    microintents_index
    normalization
    polyglot_merge_response
    rule_utils
    sample_features_converter
    session_conversion
    tagger
    trivial_tagger
    trivial_tagger/ut
    type_parser
    user_entities
    utils/ut
    zeliboba_utils
)
