PY2_LIBRARY()

OWNER(
    g:alice
    g:alice_quality
)

PEERDIR(
    alice/bitbucket/pynorm
    alice/megamind/protos/scenarios
    alice/nlu/py_libs/custom_entities
    alice/nlu/py_libs/query_wizard_features_reader/lib
    alice/nlu/py_libs/vins_models_tf/lib
    alice/nlu/py_libs/tagger
    alice/nlu/py_libs/utils
    alice/rtlog/client/python/lib
    alice/vins/core/vins_core/nlg
    alice/vins/core/vins_core/utils
    alice/vins_contrib/crfsuitex
    alice/vins_contrib/yandex-normalizer-general-0.1.1
    bindings/python/light_syntax_lib
    catboost/python-package/lib
    contrib/libs/tf/python
    contrib/python/PyYAML
    contrib/python/attrs
    contrib/python/boto3
    contrib/python/dateutil
    contrib/python/emoji
    contrib/python/enum34
    contrib/python/fasteners
    contrib/python/jsonschema
    contrib/python/marisa_trie
    contrib/python/numpy
    contrib/python/pandas
    contrib/python/python-crfsuite
    contrib/python/pymongo
    contrib/python/pymorphy2
    contrib/python/requests
    contrib/python/scikit-learn
    contrib/python/scipy
    contrib/python/tqdm
    contrib/python/typing
    contrib/python/h5py
    yt/python/client
    geobase/python/static
    library/python/func
    library/python/hnsw/lib
    library/python/ylog
    library/python/resource
    library/python/svn_version
)

RESOURCE_FILES(
    vins_core/nlu/data/poi_activity_ru.txt
    vins_core/nlu/data/country.txt
    vins_core/nlu/data/poi_ru.txt
    vins_core/nlu/data/region_ru.txt
    vins_core/nlu/data/first_name_ru.txt
    vins_core/nlu/data/yandex_search_query.txt
    vins_core/nlu/data/currency.txt
    vins_core/nlu/data/abs_time_ru.txt
    vins_core/nlu/data/last_name_ru.txt
    vins_core/nlu/data/rel_time_ru.txt
    vins_core/nlu/data/address_ru.txt
    vins_core/nlu/data/day_of_week_ru.txt
    vins_core/nlu/data/date_ru.txt
    vins_core/nlu/data/middle_name_ru.txt
    vins_core/nlu/data/city_ru.txt
    vins_core/nlg/macros/json_macro.jinja
)

NO_WERROR()

PY_SRCS(
    TOP_LEVEL
    vins_core/__init__.py
    vins_core/app_utils.py
    vins_core/exceptions.py
    vins_core/common/__init__.py
    vins_core/common/annotations/__init__.py
    vins_core/common/annotations/base.py
    vins_core/common/annotations/entitysearch.py
    vins_core/common/annotations/flag.py
    vins_core/common/annotations/ner.py
    vins_core/common/annotations/wizard.py
    vins_core/common/annotations/extra.py
    vins_core/common/entity.py
    vins_core/common/experiments.py
    vins_core/common/knn_cache.py
    vins_core/common/sample.py
    vins_core/common/slots_map_utils.py
    vins_core/common/utterance.py
    vins_core/config/__init__.py
    vins_core/config/app_config.py
    vins_core/config/intent_config_loaders.py
    vins_core/config/schemas.py
    vins_core/dm/__init__.py
    vins_core/dm/dialog_history.py
    vins_core/dm/form_filler/__init__.py
    vins_core/dm/form_filler/base.py
    vins_core/dm/form_filler/dialog_manager.py
    vins_core/dm/form_filler/events.py
    vins_core/dm/form_filler/feature_updater.py
    vins_core/dm/form_filler/form_candidate.py
    vins_core/dm/form_filler/models.py
    vins_core/dm/form_filler/nlu_postprocessor.py
    vins_core/dm/formats.py
    vins_core/dm/frame_scoring/__init__.py
    vins_core/dm/frame_scoring/base.py
    vins_core/dm/frame_scoring/multislot_scoring.py
    vins_core/dm/frame_scoring/slot_type.py
    vins_core/dm/frame_scoring/tagger_score.py
    vins_core/dm/intent.py
    vins_core/dm/nlu_sources.py
    vins_core/dm/request.py
    vins_core/dm/request_events.py
    vins_core/dm/response.py
    vins_core/dm/session.py
    vins_core/ext/__init__.py
    vins_core/ext/base.py
    vins_core/ext/entitysearch.py
    vins_core/ext/general_conversation.py
    vins_core/ext/geobase.py
    vins_core/ext/language_model.py
    vins_core/ext/s3.py
    vins_core/ext/sandbox.py
    vins_core/ext/speechkit_api.py
    vins_core/ext/voice_synth.py
    vins_core/ext/wizard_api.py
    vins_core/ext/yt.py
    vins_core/logger/__init__.py
    vins_core/logger/color_formatter.py
    vins_core/logger/default_log.py
    vins_core/logger/dialog_log.py
    vins_core/logger/qloud_formatter.py
    vins_core/logger/utils.py
    vins_core/ner/__init__.py
    vins_core/ner/custom.py
    vins_core/ner/fst_base.py
    vins_core/ner/fst_calc.py
    vins_core/ner/fst_custom.py
    vins_core/ner/fst_datetime_range.py
    vins_core/ner/fst_datetime_ru.py
    vins_core/ner/fst_float.py
    vins_core/ner/fst_geo.py
    vins_core/ner/fst_normalizer.py
    vins_core/ner/fst_num.py
    vins_core/ner/fst_parser.py
    vins_core/ner/fst_post.py
    vins_core/ner/fst_presets.py
    vins_core/ner/fst_time.py
    vins_core/ner/fst_units.py
    vins_core/ner/fst_weekdays.py
    vins_core/ner/fst_wizard.py
    vins_core/ner/ner_mixin.py
    vins_core/ner/wizard.py
    vins_core/nlu/__init__.py
    vins_core/nlu/anaphora/__init__.py
    vins_core/nlu/anaphora/annotation_utils.py
    vins_core/nlu/anaphora/context.py
    vins_core/nlu/anaphora/factory.py
    vins_core/nlu/anaphora/features/__init__.py
    vins_core/nlu/anaphora/features/base.py
    vins_core/nlu/anaphora/features/basic.py
    vins_core/nlu/anaphora/features/phrase_level.py
    vins_core/nlu/anaphora/matcher/__init__.py
    vins_core/nlu/anaphora/matcher/base.py
    vins_core/nlu/anaphora/matcher/catboost_based.py
    vins_core/nlu/anaphora/matcher/rule_based.py
    vins_core/nlu/anaphora/mention.py
    vins_core/nlu/anaphora/resolver.py
    vins_core/nlu/base_nlu.py
    vins_core/nlu/classifier.py
    vins_core/nlu/classifiers_cascade.py
    vins_core/nlu/combine_scores_classifier.py
    vins_core/nlu/combine_scores_tagger.py
    vins_core/nlu/custom_entities_tools.py
    vins_core/nlu/dirty_lang_classifier.py
    vins_core/nlu/exact_match_classifier.py
    vins_core/nlu/exact_match_token_tagger.py
    vins_core/nlu/features/__init__.py
    vins_core/nlu/features/base.py
    vins_core/nlu/features/cache/__init__.py
    vins_core/nlu/features/cache/base.py
    vins_core/nlu/features/cache/factory.py
    vins_core/nlu/features/cache/picklecache.py
    vins_core/nlu/features/cache/protobufcache.py
    vins_core/nlu/features/extractor/__init__.py
    vins_core/nlu/features/extractor/base.py
    vins_core/nlu/features/extractor/classifier.py
    vins_core/nlu/features/extractor/custom_serialization.py
    vins_core/nlu/features/extractor/granet.py
    vins_core/nlu/features/extractor/dssm/__init__.py
    vins_core/nlu/features/extractor/dssm/config.py
    vins_core/nlu/features/extractor/dssm/dssm_embeddings.py
    vins_core/nlu/features/extractor/dssm/preprocessor.py
    vins_core/nlu/features/extractor/dssm/utils.py
    vins_core/nlu/features/extractor/embeddings.py
    vins_core/nlu/features/extractor/embeddings_ids.py
    vins_core/nlu/features/extractor/entitysearch.py
    vins_core/nlu/features/extractor/morphology.py
    vins_core/nlu/features/extractor/music.py
    vins_core/nlu/features/extractor/ner.py
    vins_core/nlu/features/extractor/ngram.py
    vins_core/nlu/features/extractor/nlu_extra.py
    vins_core/nlu/features/extractor/regexp.py
    vins_core/nlu/features/extractor/serp.py
    vins_core/nlu/features/extractor/wizard.py
    vins_core/nlu/features/post_processor/__init__.py
    vins_core/nlu/features/post_processor/base.py
    vins_core/nlu/features/post_processor/char_indexer.py
    vins_core/nlu/features/post_processor/dense_features_guard.py
    vins_core/nlu/features/post_processor/selector.py
    vins_core/nlu/features/post_processor/sparse_indexer.py
    vins_core/nlu/features/post_processor/splicer.py
    vins_core/nlu/features/post_processor/std_normalizer.py
    vins_core/nlu/features/post_processor/vectorizer.py
    vins_core/nlu/features_extractor.py
    vins_core/nlu/flow_nlu.py
    vins_core/nlu/flow_nlu_factory/__init__.py
    vins_core/nlu/flow_nlu_factory/transition_model.py
    vins_core/nlu/granet_classifier.py
    vins_core/nlu/granet_token_tagger.py
    vins_core/nlu/input_source_classifier.py
    vins_core/nlu/intent_candidate.py
    vins_core/nlu/irrelevant_classifier.py
    vins_core/nlu/knn/knn.pyx=vins_core.nlu.knn
    vins_core/nlu/lookup_classifier.py
    vins_core/nlu/neural/__init__.py
    vins_core/nlu/neural/metric_learning/__init__.py
    vins_core/nlu/neural/metric_learning/callbacks/__init__.py
    vins_core/nlu/neural/metric_learning/callbacks/base_callback.py
    vins_core/nlu/neural/metric_learning/callbacks/batch_schedule.py
    vins_core/nlu/neural/metric_learning/config.py
    vins_core/nlu/neural/metric_learning/encoders/__init__.py
    vins_core/nlu/neural/metric_learning/encoders/stack_sequential.py
    vins_core/nlu/neural/metric_learning/helpers.py
    vins_core/nlu/neural/metric_learning/losses.py
    vins_core/nlu/neural/metric_learning/metric_learning.py
    vins_core/nlu/neural/metric_learning/model.py
    vins_core/nlu/neural/metric_learning/sample_features_preprocessor.py
    vins_core/nlu/neural/metric_learning/trainer.py
    vins_core/nlu/nlu_data_cache.py
    vins_core/nlu/nlu_utils.py
    vins_core/nlu/nontrainable_combine_scores_classifier.py
    vins_core/nlu/nontrainable_token_classifier.py
    vins_core/nlu/protocol_semantic_frame_classifier.py
    vins_core/nlu/protocol_semantic_frame_tagger.py
    vins_core/nlu/reranker/__init__.py
    vins_core/nlu/reranker/catboost_model.py
    vins_core/nlu/reranker/factor_calcer.py
    vins_core/nlu/reranker/factors.py
    vins_core/nlu/reranker/reranker.py
    vins_core/nlu/sample_processors/__init__.py
    vins_core/nlu/sample_processors/base.py
    vins_core/nlu/sample_processors/clip.py
    vins_core/nlu/sample_processors/drop_censored.py
    vins_core/nlu/sample_processors/entitysearch.py
    vins_core/nlu/sample_processors/expected_value.py
    vins_core/nlu/sample_processors/misspell.py
    vins_core/nlu/sample_processors/normalize.py
    vins_core/nlu/sample_processors/registry.py
    vins_core/nlu/sample_processors/strip_activation.py
    vins_core/nlu/sample_processors/wizard.py
    vins_core/nlu/samples_extractor.py
    vins_core/nlu/sklearn_utils.py
    vins_core/nlu/syntax.py
    vins_core/nlu/template_entities.py
    vins_core/nlu/text_to_source.py
    vins_core/nlu/token_classifier.py
    vins_core/nlu/token_tagger.py
    vins_core/schema/__init__.py
    vins_core/schema/interface.py
    vins_core/schema/features.proto
)

END()

RECURSE_FOR_TESTS(ut)
