files:
  - name: /logs/server-log.err
    pipe: ./nanny-json-pipe.py --env experiments
    ident: gamma
    log_type: server-log
logger:
  file: /logs/push-client.log
  level: 5
  mode: file
network:
  master_addr: logbroker.yandex.net
watcher:
  state: /logs/push-client-state