files:
- name: /logs/uniproxy.out
  send_delay: 5
  topic: /alice-production/messenger/uniproxy
  pipe: ./qloud_format
- name: /logs/uniproxy.err
  send_delay: 5
  topic: /alice-production/messenger/uniproxy
  pipe: ./qloud_format
logger:
  file: /logs/push-client.log
  level: 5
  remote: 0
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
  proto: pq
  tvm-server-id: 2001059
  tvm-client-id: 2000496
watcher:
  state: push-client-state
