alice4-business-config.timeout: 200
alice4-business-config.getDeviceLockStateTimeout: 200
alice4-business-config.connectTimeout: 50
alice4-business-config.cacheUnlockedDeviceState: false
alice4-business-config.pgReadWriteDatabaseUrl: ${ALICE4_BUSINESS_PG_READ_WRITE_DATABASE_URL}
alice4-business-config.pgReadOnlyDatabaseUrl: ${ALICE4_BUSINESS_PG_READ_ONLY_DATABASE_URL}
alice4-business-config.pgUser: ${ALICE4_BUSINESS_PG_USER}
alice4-business-config.pgPassword: ${ALICE4_BUSINESS_PG_PASSWORD}
alice4-business-config.poolSizeIdle: ${ALICE4_BUSINESS_PG_POOL_SIZE_IDLE:1}
alice4-business-config.poolSizeMax: ${ALICE4_BUSINESS_PG_POOL_SIZE_MAX:10}
alice4-business-config.poolConnectTimeout: 1000
alice4-business-config.poolConnectionMaxLifetime: 300000
alice4-business-config.poolConnectionIdleTimeout: 180000
alice4-business-config.activationCodeCollisionRepeats: 5
alice4-business-config.fillCachesOnStartUp: true
alice4-business-config.pgSslEnable: true

customer-activation-operation.codeRefreshInterval: 180000
