files:
- name: /logs/current-vins-rtlog
  send_delay: 5
  topic: alicelogs/prod/vins
  format: eventlog
  compression-out: 0
files:
- name: /logs/vins.push_client.out
  send_delay: 5
  topic: vins/qloud-runtime-log
  pipe: ./row_id.py
files:
- name: /logs/vins-features.log
  send_delay: 5
  topic: vins/vins-features
logger:
  file: /logs/push-client.log
  level: 5
  mode:
  - file
network:
  master_addr: logbroker.yandex.net
watcher:
  state: /logs/push-client-state
