"""Add user settings field

Revision ID: e93183fcc25e
Revises: f96a31a74bff
Create Date: 2021-01-21 21:09:09.505906

"""
import jupyterhub.orm
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e93183fcc25e'
down_revision = 'f96a31a74bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', jupyterhub.orm.JSONDict(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
