"""Added users table

Revision ID: eab2ab022148
Revises:
Create Date: 2019-07-05 19:33:37.516022

"""
import jupyterhub
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'eab2ab022148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.Unicode(length=255), nullable=True),
        sa.Column('idm_state', jupyterhub.orm.JSONDict(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
