#pragma once

//////////////////////////////////////////////////////////////////////
// WARNING: this code was automatically generated by alice/json_schema_builder/tool,
// don't edit it manually.
//////////////////////////////////////////////////////////////////////

#include <alice/json_schema_builder/runtime/runtime.h>

namespace NAlice::NJsonSchemaBuilder::NDiv2 {

enum class EDivFontWeight {
    Light = 0 /* "light" */,
    Medium = 1 /* "medium" */,
    Regular = 2 /* "regular" */,
    Bold = 3 /* "bold" */,
};

enum class EDivImageScale {
    Fill = 0 /* "fill" */,
    NoScale = 1 /* "no_scale" */,
    Fit = 2 /* "fit" */,
};

enum class EDivAlignmentVertical {
    Top = 0 /* "top" */,
    Center = 1 /* "center" */,
    Bottom = 2 /* "bottom" */,
};

enum class EDivAlignmentHorizontal {
    Left = 0 /* "left" */,
    Center = 1 /* "center" */,
    Right = 2 /* "right" */,
};

enum class EDivSeparatorStyleOrientation {
    Vertical = 0 /* "vertical" */,
    Horizontal = 1 /* "horizontal" */,
};

enum class EDivFixedSizeUnit {
    Dp = 0 /* "dp" */,
    Sp = 1 /* "sp" */,
};

enum class EDivContainerOrientation {
    Vertical = 0 /* "vertical" */,
    Horizontal = 1 /* "horizontal" */,
    Overlap = 2 /* "overlap" */,
};

enum class EDivLineStyle {
    None = 0 /* "none" */,
    Single = 1 /* "single" */,
};

enum class EDivTextTruncate {
    None = 0 /* "none" */,
    Start = 1 /* "start" */,
    End = 2 /* "end" */,
    Middle = 3 /* "middle" */,
    Marquee = 4 /* "marquee" */,
};

enum class EDivGalleryCrossContentAlignment {
    Start = 0 /* "start" */,
    Center = 1 /* "center" */,
    End = 2 /* "end" */,
};

enum class EDivGalleryScrollMode {
    Paging = 0 /* "paging" */,
    Default = 1 /* "default" */,
};

}  // namespace NAlice::NJsonSchemaBuilder::NDiv2
