//////////////////////////////////////////////////////////////////////
// WARNING: this code was automatically generated by alice/json_schema_builder/tool,
// don't edit it manually.
//////////////////////////////////////////////////////////////////////

#include "log_id_filler.h"

namespace NAlice::NJsonSchemaBuilder::NDiv2 {

}  // namespace NAlice::NJsonSchemaBuilder::NDiv2
